### ISSUE TITLE
Can't install now cli on Linux

### ISSUE THREAD

**Issue by Rafaell416** [vercel/vercel#1012]
Hello, i've been a long time trying to install now cli on Manjaro (Arch Linux)
node version: 8.9.1
npm vesion: 5.5.1

the error log is: 

```
npm install -g now
/root/.nvm/versions/node/v8.9.1/bin/now -> /root/.nvm/versions/node/v8.9.1/lib/node_modules/now/download/dist/now

> now@8.5.4 postinstall /root/.nvm/versions/node/v8.9.1/lib/node_modules/now
> node download/install.js

module.js:473
      throw err;
      ^

Error: Cannot find module '/root/.nvm/versions/node/v8.9.1/lib/node_modules/now/download/install.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! now@8.5.4 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the now@8.5.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-29T05_04_30_014Z-debug.log
```

**Comment by Qix-** [comment]
Hi - curious, why are you trying to install as root?

Further, I can't reproduce on either Node 8.9.1 or 9.1.0 with npm@5.5.1.

```console
junon@devdev:~$ node --version
v9.1.0
junon@devdev:~$ n 8

     install : node-v8.9.1
       mkdir : /usr/local/n/versions/node/8.9.1
       fetch : https://nodejs.org/dist/v8.9.1/node-v8.9.1-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v8.9.1

junon@devdev:~$ npm i -g now
/usr/local/bin/now -> /usr/local/lib/node_modules/now/download/dist/now

> now@8.5.4 postinstall /usr/local/lib/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 8.5.4 [====================] 100%

+ now@8.5.4
added 1 package in 24.779s
junon@devdev:~$ now --version
8.5.4
junon@devdev:~$ npm --version
5.5.1
```

First inclination is that this is a problem with your nvm setup. Whenever I see `/root` though I get a bit suspicious.

**Comment by Rafaell416** [comment]
I don't know why i didn't try it before, thanks a lot!  I installed it without being root and it worked
