### ISSUE TITLE
'Error: Not snapshotted yet' when aliasing a deployment to an external domain

### ISSUE THREAD

**Issue by nickdandakis** [vercel/vercel#1031]
The external domain currently points to an existing `now` deployment. However, I get the following error when attempting to alias a new deployment to the external domain. `now --version` is 8.5.4.

```
> Scaling deployment to match current scale.
> [debug] #1 POST /deployments/H2ozyadVlC41BmJV2NyGwrIo/instances: 481.726ms
> [debug] Retrying: Error: Not snapshotted yet.
Error: Not snapshotted yet.
    at module.exports.EventEmitter.setScale.scale.retry (/snapshot/now-cli/dist/now.js:1074:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #2 POST /deployments/H2ozyadVlC41BmJV2NyGwrIo/instances: 592.420ms
> [debug] Retrying: Error: Not snapshotted yet.
Error: Not snapshotted yet.
    at module.exports.EventEmitter.setScale.scale.retry (/snapshot/now-cli/dist/now.js:1074:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #3 POST /deployments/H2ozyadVlC41BmJV2NyGwrIo/instances: 633.948ms
> [debug] Retrying: Error: Not snapshotted yet.
Error: Not snapshotted yet.
    at module.exports.EventEmitter.setScale.scale.retry (/snapshot/now-cli/dist/now.js:1074:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #4 POST /deployments/H2ozyadVlC41BmJV2NyGwrIo/instances: 543.843ms
> [debug] Retrying: Error: Not snapshotted yet.
Error: Not snapshotted yet.
    at module.exports.EventEmitter.setScale.scale.retry (/snapshot/now-cli/dist/now.js:1074:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by andyburke** [comment]
seeing this trying to scale an instance, too....
