### ISSUE TITLE
Deployment errors, invalid JSON at https://api.zeit.co/plan

### ISSUE THREAD

**Issue by donmccurdy** [vercel/vercel#1055]
Trying to deploy a static folder containing HTML with `now --static`, I get this error:

```
> Deploying ~/Desktop/bug-gltf-specgloss-shadows under donmccurdy
> Error! An unexpected error occurred!
  FetchError: invalid json response body at https://api.zeit.co/plan reason: Unexpected token < in JSON at position 0
    at /snapshot/now-cli/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) FetchError: invalid json response body at https://api.zeit.co/plan reason: Unexpected token < in JSON at position 0
    at /snapshot/now-cli/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Using now-cli v9.0.1, on macOS. I'm on the Premium plan if that matters, sure why a plan-related error would appear?

**Comment by timneutkens** [comment]
@donmccurdy Please see https://twitter.com/zeit_status, there's currently an ongoing outage.
