### ISSUE TITLE
aws deploy throws on canary

### ISSUE THREAD

**Issue by 2075** [vercel/vercel#1074]
hey there

i have tried to do a simple lambda deploy from macos, but lack some more config options i assume.
when using 9.1.0. and the latest 10.0.0-canary i receive the same issues, first throwing a BadRequestException: Description cannot be an empty string and then idling on Creating API resources:

`me@machine  ~/dev/zeit/lambda  now
> Deploying "~/dev/zeit/lambda" (aws) (us-west-1)
✔ Build generated a 679.06KB zip [3s]
⠴ Creating API resources> Error! An unexpected error occurred in deploy: BadRequestException: Description cannot be an empty string
    at Object.extractError (/snapshot/now-cli/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/snapshot/now-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:45:8)
    at Request.callListeners (/snapshot/now-cli/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/snapshot/now-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/now-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/now-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/snapshot/now-cli/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/snapshot/now-cli/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/snapshot/now-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /snapshot/now-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/snapshot/now-cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/snapshot/now-cli/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/snapshot/now-cli/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/snapshot/now-cli/node_modules/aws-sdk/lib/event_listeners.js:269:13)
    at emitNone (events.js:120:20)
⠸ Creating API resources`

anything i can do to make it work or support?

besides that i have noticed, when using multiple account credentials in your .aws dir, it is not clear how to select which account and which region to use when launching a lambda.

now aws ls throws, too on both versions. is this known or maybe my environment?

**Comment by 2075** [comment]
okay, it was not clear to me, that a now.json is required to make it work. after adding that, it worked like a charm and answered all my questions above.

`{
	"name": "now-demo",
	"description": "a now based lambda",
	"type": "nodejs",
	"regions": ["eu-central-1"]
}`

the region seems to be ignored, though. i have set it in now.json and in my aws defaults but the deployment ends up on us-west-1.

and as mentioned in [#914](https://github.com/zeit/now-cli/issues/914), the lambdas are not versioned, which might be because of the hash in the name (?). maybe bumping the package version string on patch level instead of adding the hash would help here, too?

**Comment by rauchg** [comment]
Yep. This is a work in progress, currently in an experimental phase. We'll update the README accordingly. Thank you for reporting!
