### ISSUE TITLE
Can't create cert:  Attemp to renew a non-existing certificate for

### ISSUE THREAD

**Issue by luqmaan** [vercel/vercel#1101]
I'm having trouble creating a custom cert. It seems like its trying to renew the cert instead of create a new cert:

```
$ now certs create cdn.kickdb.com --debug
> [debug] /now/certs #1: 395.989ms
> [debug] Retrying: Error: Attemp to renew a non-existing certificate for cdn.kickdb.com
Error: Attemp to renew a non-existing certificate for cdn.kickdb.com
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:940:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] /now/certs #2: 152.166ms
> [debug] Retrying: Error: Attemp to renew a non-existing certificate for cdn.kickdb.com
Error: Attemp to renew a non-existing certificate for cdn.kickdb.com
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:940:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] /now/certs #3: 188.373ms
> [debug] Retrying: Error: Attemp to renew a non-existing certificate for cdn.kickdb.com
Error: Attemp to renew a non-existing certificate for cdn.kickdb.com
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:940:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] /now/certs #4: 467.282ms
> Error! Unexpected error. Please try again later. (Attemp to renew a non-existing certificate for cdn.kickdb.com)
```

I'm using now `9.2.7`.

Also, there's a typo in the error message: it should say `Attempt` instead of `Attemp`.

**Comment by iamkevingreen** [comment]
this is still happening for me on 11.1 I'm attempting to add www. which currently isn't working on my site.

Same error where it's attempting to renew a cert that is not created.

**Comment by leo** [comment]
This should not be happening!

**Comment by TooTallNate** [comment]
Closing because `now certs create` is no longer a valid command. Please create a new issue if you are still experiencing any certificate problems.
