### ISSUE TITLE
No network when using Docker?

### ISSUE THREAD

**Issue by galman33** [vercel/vercel#1103]
When trying to perform http requests from a Docker container I receive 
```
{ Error: getaddrinfo EAI_AGAIN www.google.com:80
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'www.google.com',
  host: 'www.google.com',
  port: 80 }
```

For example:

```javascript
// index.js

const express = require('express')
var request = require('request');
const app = express()

app.get('/', (req, res) => {
    request('http://google.com/', function (error, response, body) {
        if(error)
            res.send(error)
        else
            res.send(body)
      });
})

app.listen(3000, () => console.log('Example app listening on port 3000!'))
```

```dockerfile
# Dockerfile

FROM node:carbon

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]

```

When deploying the same code without docker it works fine...
Am I missing something?

**Comment by matheuss** [comment]
Thanks for reporting! We've identified an issue with new Docker deployments under the OSS plan – fix coming shortly.

**Comment by matheuss** [comment]
@galman33 Should be fixed! Could you try to re-deploy and confirm, please?
