### ISSUE TITLE
 Error: File size limit exceeded (1 MB)

### ISSUE THREAD

**Issue by sr2ds** [vercel/vercel#1127]
I have this problem, does anyone know how to solve it?

```
> Deploying ~/meteor under myemail@mail.com
> [debug] Detected `deploymentType` = `npm`
> [debug] Detected `deploymentName` = "centric"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/.gitignore"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/dev_bundle/lib/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/dev_bundle/server-lib/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/build/programs/server/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/dev_bundle/include/node/config.gypi"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/build/programs/server/npm/node_modules"
> [debug] locating files /mnt/ext/home/dsilva/meteor: 53.537ms
> [debug] Getting files: 56.181ms
> [debug] Computing hashes: 665.781ms
> [debug] get files ready for deployment: 21.850ms
> [debug] v3/now/deployments: 1830.479ms
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> [debug] Detected `deploymentType` = `npm`
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/.gitignore"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/dev_bundle/lib/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/dev_bundle/server-lib/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/build/programs/server/node_modules"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/dev_bundle/include/node/config.gypi"
> [debug] ignoring "/mnt/ext/home/dsilva/meteor/.meteor/local/build/programs/server/npm/node_modules"
> [debug] locating files /mnt/ext/home/dsilva/meteor: 67.201ms
> [debug] Getting files: 70.449ms
> [debug] Computing hashes: 619.374ms
> [debug] get files ready for deployment: 31.001ms
> [debug] v3/now/deployments: 5527.077ms
> [debug] total files 1458, 16 changed. 
> [debug] Will upload 16 files
> [debug] v2/now/files #1 /mnt/ext/home/dsilva/meteor/.meteor/local/bundler-cache/linker/c3610265850dca5bf90fd76c70a3194776908e2f_1a538b81a8fad71a4749d68e22abda10fe1b8221.cache: 3660.293ms
> [debug] bailing on creating due to 400
> Error! Upload failed
> Error! An unexpected error occurred!
  Error: File size limit exceeded (1 MB)
    at responseError (/snapshot/now-cli/dist/now.js:199:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) Error: File size limit exceeded (1 MB)
    at responseError (/snapshot/now-cli/dist/now.js:199:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by sreeramjayan** [comment]
@srdavidsilva 
Based on https://zeit.co/pricing, since you're on the OSS plan the maximum file size is 1MB.

**Comment by BurkovBA** [comment]
Guys, I enjoy your service a lot, but could you provide a more detailed error message about this file size:

Which file exactly was too big?

**Comment by OlliV** [comment]
This is duplicate to #1111
