### ISSUE TITLE
Module not found: Error: Can't resolve 'antd' in '/home/nowuser/src/components'

### ISSUE THREAD

**Issue by ateufel** [vercel/vercel#1176]
i am trying to use now to deploy a next app with antd, and while this works perfectly fine in another project with the same setup (really, there should be no difference at all), and while the local build works perfectly fine, i get the following error with now:

```
> Failed to build
> { Error: (client) ./components/CustomHeader.js
> Module not found: Error: Can't resolve 'antd' in '/home/nowuser/src/components'
> resolve 'antd' in '/home/nowuser/src/components'
>   Parsed request is a module
>   using description file: /home/nowuser/src/package.json (relative path: ./components)
>     Field 'browser' doesn't contain a valid alias configuration
>   after using description file: /home/nowuser/src/package.json (relative path: ./components)
>     resolve as module
>       looking for modules in /home/nowuser/src/node_modules/next/node_modules
>         using description file: /home/nowuser/src/node_modules/next/package.json (relative path: ./node_modules)
>           Field 'browser' doesn't contain a valid alias configuration
>         after using description file: /home/nowuser/src/node_modules/next/package.json (relative path: ./node_modules)
>           using description file: /home/nowuser/src/node_modules/next/package.json (relative path: ./node_modules/antd)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/antd doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/antd.js doesn't exist
>             .jsx
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/antd.jsx doesn't exist
>             .json
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/next/node_modules/antd.json doesn't exist
>             as directory
>               /home/nowuser/src/node_modules/next/node_modules/antd doesn't exist
>       /home/nowuser/src/components/node_modules doesn't exist or is not a directory
>       /home/nowuser/node_modules doesn't exist or is not a directory
>       /home/node_modules doesn't exist or is not a directory
>       /node_modules doesn't exist or is not a directory
>       looking for modules in /home/nowuser/src/node_modules
>         using description file: /home/nowuser/src/package.json (relative path: ./node_modules)
>           Field 'browser' doesn't contain a valid alias configuration
>         after using description file: /home/nowuser/src/package.json (relative path: ./node_modules)
>           using description file: /home/nowuser/src/package.json (relative path: ./node_modules/antd)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/antd doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/antd.js doesn't exist
>             .jsx
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/antd.jsx doesn't exist
>             .json
>               Field 'browser' doesn't contain a valid alias configuration
>               /home/nowuser/src/node_modules/antd.json doesn't exist
>             as directory
>               /home/nowuser/src/node_modules/antd doesn't exist
> [/home/nowuser/src/node_modules/next/node_modules/antd]
> [/home/nowuser/src/node_modules/next/node_modules/antd.js]
> [/home/nowuser/src/node_modules/next/node_modules/antd.jsx]
> [/home/nowuser/src/node_modules/next/node_modules/antd.json]
> [/home/nowuser/src/node_modules/next/node_modules/antd]
> [/home/nowuser/src/components/node_modules]
> [/home/nowuser/node_modules]
> [/home/node_modules]
> [/node_modules]
> [/home/nowuser/src/node_modules/antd]
> [/home/nowuser/src/node_modules/antd.js]
> [/home/nowuser/src/node_modules/antd.jsx]
> [/home/nowuser/src/node_modules/antd.json]
> [/home/nowuser/src/node_modules/antd]
>  @ ./components/CustomHeader.js 16:0-52
>  @ ./layouts/main.js
>  @ ./pages/index.js
>  @ multi ./pages/index.js
>     at /home/nowuser/src/node_modules/next/dist/server/build/index.js:207:31
>     at runWithDependencies (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:154:4)
>     at /home/nowuser/src/node_modules/async/dist/async.js:1126:9
>     at /home/nowuser/src/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/home/nowuser/src/node_modules/async/dist/async.js:1050:13)
>     at /home/nowuser/src/node_modules/async/dist/async.js:958:16
>     at /home/nowuser/src/node_modules/async/dist/async.js:1123:13
>     at runCompilers (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:96:47)
>     at fn (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:101:6)
>     at compiler.run (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:150:5)
>     at emitRecords.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:265:13)
>     at Compiler.emitRecords (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:371:38)
>     at emitAssets.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:258:10)
>     at applyPluginsAsyncSeries1.err (/home/nowuser/src/node_modules/webpack/lib/Compiler.js:364:12)
>     at next (/home/nowuser/src/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/home/nowuser/src/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
```

If i remove CustomHeader.js, i get the same error for CustomFooter.js, and that one is really simple (and, again, the same as in another project):

```
import React from 'react';
import {Layout} from 'antd';
const {Footer} = Layout;

const CustomFooter = () => {
	return (
		<Footer style={{textAlign: 'center'}}>
			©2018 by <a href="https://www.xxx.com">xxx</a>
		</Footer>
	);
};

export default CustomFooter;
```
Whenever i try to import antd, this happens.

**Comment by timneutkens** [comment]
talking about it on zeit.chat, but just in case:

> Sounds a lot like you have a stale lockfile, try removing package-lock.json yarn.lock

**Comment by ateufel** [comment]
thanx for the tip, that was indeed the problem!
