### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by suntong** [vercel/vercel#1201]
I'm getting the `Cannot convert undefined or null to object` when following the get-started demo at
https://zeit.co/now#get-started

My now-cli is freshly installed just now.

```sh
> now@10.2.0 postinstall /usr/lib/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 10.2.0 [====================] 100%

+ now@10.2.0
updated 1 package in 32.948s

$ now -h 

  ð« now [options] <command | path>

  Commands:

    Cloud

      deploy               [path]      Performs a deployment (default)
      ls | list            [app]       List deployments
. . .
```

here are all my files:

```
$ head * 
==> index.js <==
module.exports = () => 'Ahoy, world!'
==> package.json <==
{
  "scripts": {
    "start": "micro"
  },
  "dependencies": {
    "micro": "latest"
  }
}
```

and when run `now`, I get:

```
$ now
> Deploying /.../my-project under myid
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> > NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> Using Node.js 8.10.0 (default)
> Ready! https://prj1-hsvfazntgc.now.sh [1s]
> Initializingâ¦
> Building
> â² npm install
> â Installed 13 modules [492ms]
> â§ Installing 1 main dependencyâ¦
> â² npm start
> @ start /home/nowuser/src
> micro
> micro: Accepting connections on port 3000
> Error! An unexpected error occurred!
  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Logger.logger.on (/snapshot/repo/dist/now.js:6278:26)
    at Logger.emit (events.js:159:13)
    at Logger.onComplete (/snapshot/repo/dist/now.js:11518:10)
    at Logger.onState (/snapshot/repo/dist/now.js:11466:12)
    at Socket.Emitter.emit (/snapshot/repo/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/snapshot/repo/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/snapshot/repo/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.module.exports (/snapshot/repo/node_modules/component-bind/index.js:0:0)
    at Manager.Emitter.emit (/snapshot/repo/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/snapshot/repo/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.module.exports (/snapshot/repo/node_modules/component-bind/index.js:0:0)
    at Decoder.Emitter.emit (/snapshot/repo/node_modules/socket.io-parser/node_modules/component-emitter/index.js:0:0)
    at Decoder.add (/snapshot/repo/node_modules/socket.io-parser/index.js:246:12)
    at Manager.ondata (/snapshot/repo/node_modules/socket.io-client/lib/manager.js:322:16)
    at Socket.module.exports (/snapshot/repo/node_modules/component-bind/index.js:0:0) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Logger.logger.on (/snapshot/repo/dist/now.js:6278:26)
    at Logger.emit (events.js:159:13)
    at Logger.onComplete (/snapshot/repo/dist/now.js:11518:10)
    at Logger.onState (/snapshot/repo/dist/now.js:11466:12)
    at Socket.Emitter.emit (/snapshot/repo/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/snapshot/repo/node_modules/socket.io-client/lib/socket.js:270:10)
    at Socket.onpacket (/snapshot/repo/node_modules/socket.io-client/lib/socket.js:228:12)
    at Manager.module.exports (/snapshot/repo/node_modules/component-bind/index.js:0:0)
    at Manager.Emitter.emit (/snapshot/repo/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/snapshot/repo/node_modules/socket.io-client/lib/manager.js:332:8)
    at Decoder.module.exports (/snapshot/repo/node_modules/component-bind/index.js:0:0)
    at Decoder.Emitter.emit (/snapshot/repo/node_modules/socket.io-parser/node_modules/component-emitter/index.js:0:0)
    at Decoder.add (/snapshot/repo/node_modules/socket.io-parser/index.js:246:12)
    at Manager.ondata (/snapshot/repo/node_modules/socket.io-client/lib/manager.js:322:16)
    at Socket.module.exports (/snapshot/repo/node_modules/component-bind/index.js:0:0)
```
what's wrong? 
How can I make it working? 

Thx!

**Comment by rauchg** [comment]
Can you share the output of `now --version`? Are you using canary by any chance?

**Comment by suntong** [comment]
BTW, why it is saying `> Using Node.js 8.10.0 (default)` while my node is `v9.4.0`:

```sh
$ node -v
v9.4.0
```

**Comment by suntong** [comment]
```
$ now --version
10.2.0
```

I don't know what is canary. I installed `now-cli` using `npm` into my Ubuntu:

 ```
lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

**Comment by TooTallNate** [comment]
Hey there @suntong, thank you for the report. This was fixed in v10.2.1.

**Comment by TooTallNate** [comment]
If you need tips on upgrading your version, the docs are here: https://zeit.co/docs/guides/updating-now-cli

**Comment by rauchg** [comment]
> BTW, why it is saying > Using Node.js 8.10.0 (default) while my node is v9.4.0:

@suntong this is the version it will execute in the Cloud. We default to stable Node.js. You can override it via the `engines` setting:

https://zeit.co/docs/deployment-types/node#custom-node.js-configuration

**Comment by suntong** [comment]
WOW!!! That was FAST!!!
and thanks for the update link too!

Have a nice evening everyone!
