### ISSUE TITLE
HTTP/2 issues

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1243]
This is only experienced in canary, where we enable http/2 for testing.

Occasionally commands have uncaughts like this:

```
> Error! An unexpected error occurred!
  TypeError: Cannot read property 'readStop' of undefined
    at ClientHttp2Stream.streamOnPause (internal/http2/core.js:1156:17)
    at ClientHttp2Stream.emit (events.js:159:13)
    at ClientHttp2Stream.Readable.pause (_stream_readable.js:841:10)
    at ClientHttp2Stream.ondata (_stream_readable.js:655:11)
    at ClientHttp2Stream.emit (events.js:159:13)
    at ClientHttp2Stream.Readable.read (_stream_readable.js:478:10)
    at flow (_stream_readable.js:849:34)
    at Gunzip.<anonymous> (_stream_readable.js:710:7)
    at Gunzip.emit (events.js:159:13)
    at onwriteDrain (_stream_writable.js:465:12)
    at afterWrite (_stream_writable.js:453:5)
    at onwrite (_stream_writable.js:446:7)
    at Gunzip.afterTransform (_stream_transform.js:89:3)
    at Zlib.processCallback (zlib.js:572:8) TypeError: Cannot read property 'readStop' of undefined
    at ClientHttp2Stream.streamOnPause (internal/http2/core.js:1156:17)
    at ClientHttp2Stream.emit (events.js:159:13)
    at ClientHttp2Stream.Readable.pause (_stream_readable.js:841:10)
    at ClientHttp2Stream.ondata (_stream_readable.js:655:11)
    at ClientHttp2Stream.emit (events.js:159:13)
    at ClientHttp2Stream.Readable.read (_stream_readable.js:478:10)
    at flow (_stream_readable.js:849:34)
    at Gunzip.<anonymous> (_stream_readable.js:710:7)
    at Gunzip.emit (events.js:159:13)
    at onwriteDrain (_stream_writable.js:465:12)
    at afterWrite (_stream_writable.js:453:5)
    at onwrite (_stream_writable.js:446:7)
    at Gunzip.afterTransform (_stream_transform.js:89:3)
    at Zlib.processCallback (zlib.js:572:8)
```

**Comment by pranaygp** [comment]
Do you remember what command you ran that caused this?

I seem to not be running into this issue on latest canary with Node 10.0.0

**Comment by leo** [comment]
All good since Now CLI 12.0.0!
