### ISSUE TITLE
Error! An unexpected error occurred in alias: TypeError: Cannot read property 'bru1' of undefined

### ISSUE THREAD

**Issue by danrasmuson** [vercel/vercel#1244]
I have two deployments fo my frontend

```
  mainsite-wxittscntc.now.sh                          labelbox.io                                 4h
  mainsite-antpxtfwmv.now.sh                          www.labelbox.io                             5h
```

And I'm trying to have they point at the same deployment, but I get this error.

```
➜  frontend git:(master) export DEBUG="*"
➜  frontend git:(master) now alias mainsite-wxittscntc.now.sh www.labelbox.io
  now:main start +0ms
  now:main falling back to default now provider 'sh' +14ms
  now:main user supplied known subcommand alias +0ms
> Asigning alias www.labelbox.io to deployment mainsite-wxittscntc.now.sh
> Error! An unexpected error occurred in alias: TypeError: Cannot read property 'bru1' of undefined
    at getScaleForDC (/snapshot/repo/dist/now.js:3801:35)
    at shouldCopyScalingAttributes (/snapshot/repo/dist/now.js:3806:10)
    at assignAlias (/snapshot/repo/dist/now.js:4431:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by manuaero** [comment]
i made it work after updating the now cli to 11.0.1

**Comment by leo** [comment]
This seems to be working with the latest release of Now CLI.

Let us know if you're experiencing any other issues!
