### ISSUE TITLE
Internal Error when code has async/await (transpiled)

### ISSUE THREAD

**Issue by knownasilya** [vercel/vercel#125]
Seeing the following error when I have `async/await` code present, even though it's transpiled..

```
 ▲ ~/sandbox/community-group-backend now --docker --debug                                                                      master :: 14h36m :: ⬡
> [debug] Checking for updates.
> [debug] Up to date (0.28.1).
> Deploying ~/sandbox/community-group-backend
> [debug] Forcing `deploymentType` = `docker`
> No `name` LABEL in `Dockerfile`, using community-group-backend
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/.git"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/.gitignore"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/dist/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-4aNNgLwK.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-Ghw8uQMk.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-Q12alTnz.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-ZWvk6pLF.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-cBA7SHFF.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-nsZJ2nVy.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-qbtjPlrs.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-output_path-syZ3rtVD.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-07rjW7vC.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-0JtgZEB1.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-1iIFtQ0K.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-2IYdh7Wu.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-45qyBbsL.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-4SC8q879.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-4jY9DL73.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-64I5TBGn.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-6khwLeqL.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-9q5IKxYb.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-A24udRFs.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-CZUg5Z13.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-DrIPYjZy.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-DskePeVg.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-E9Un5BhG.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-HbXHHHw2.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-KkdsMIha.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-MS6mLL05.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-NN5damQl.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-OHk9D7Yp.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-Q1uS6h2o.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-TwTNAeMb.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-U4fnEvH5.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-UqK3VLJ3.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-V8ooQdXE.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-VlThZ6qJ.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-X74euIuW.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-YEAWUiFJ.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-YWyt4hjt.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-Ye6A8abP.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-ZCo24iBX.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-a5ZovsUi.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-agpOj9bK.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-bXoPPD1G.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-bqoBLb6y.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-ddKqAqqC.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-e3zhzLAl.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-fzVdar7r.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-gVyF82k3.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-iLbOhVxX.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-iS33AJi8.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-jGAz06cl.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-jV9kVooS.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-nFRCFlvE.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-nGSe2HdX.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-oRt8ftHz.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-r4kP4J5l.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-rEDtmSn6.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-s8od4uVF.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-smuxc66e.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-tsoLQmeO.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-ttDEjjTo.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-uo1DOvnL.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-vFO3ZXKr.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-vaUbH1Bg.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/funnel-output_path-zO8t1Luf.tmp/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KEl9Ly0W.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-KiKBj2S1.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-Z3EzgwaQ.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-eLph9yDv.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-iqAZsaLh.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-n8fZxx9j.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-nKw9QbFt.tmp/7/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/1/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/2/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/3/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/4/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/5/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/6/node_modules"
> [debug] ignoring "/Users/iradchenko/sandbox/community-group-backend/tmp/broccoli_merge_trees-input_base_path-uUNkAbfx.tmp/7/node_modules"
> [debug] locating files /Users/iradchenko/sandbox/community-group-backend: 4010.462ms
> [debug] Getting files: 4425.453ms
> [debug] Computing hashes: 1304.584ms
> [debug] /now/create: 2628.661ms
> [debug] Retrying: Error: An unexpected internal error occurred
    at Now._callee$ (/usr/local/lib/node_modules/now/build/lib/index.js:389:35)
    at tryCatch (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
> [debug] /now/create: 2105.969ms
> [debug] Retrying: Error: An unexpected internal error occurred
    at Now._callee$ (/usr/local/lib/node_modules/now/build/lib/index.js:389:35)
    at tryCatch (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
> [debug] /now/create: 2018.853ms
> [debug] Retrying: Error: An unexpected internal error occurred
    at Now._callee$ (/usr/local/lib/node_modules/now/build/lib/index.js:389:35)
    at tryCatch (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
> [debug] /now/create: 2023.291ms
> [debug] error: Error: An unexpected internal error occurred
    at Now._callee$ (/usr/local/lib/node_modules/now/build/lib/index.js:389:35)
    at tryCatch (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/now/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/now/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
> Error! Unexpected error. Please try later. (An unexpected internal error occurred)
```

My Dockerfile looks like so:

```Dockerfile
FROM node:6.9

ENV PORT 80

RUN mkdir -p /usr/src/app

COPY package.json /usr/src/app/
RUN npm install --production

COPY . /usr/src/app
WORKDIR /usr/src/app

EXPOSE 80

CMD [ "npm", "start" ]
```

**Comment by knownasilya** [comment]
Also getting https://github.com/denali-js/denali/issues/219 when deploying with `now --npm`. You can find the full app here: https://github.com/loaves-and-fishes/community-groups-backend

Seems like the code is evaluated before deployment and it chokes on anything it doesn't understand.

**Comment by jamo** [comment]
Sorry for the delay with my response. 
It seems that there are two issues

With the dockerfile in the repo I'll get `sh: 1: denali: not found`
And by moving the `WORKDIR` before `npm install`
<details>

``` diff
diff --git a/Dockerfile b/Dockerfile
index 3e77780..c3f5060 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -6,10 +6,10 @@ ENV PORT 80
 RUN mkdir -p /usr/src/app

 COPY package.json /usr/src/app/
+WORKDIR /usr/src/app
 RUN npm install --production

 COPY . /usr/src/app
-WORKDIR /usr/src/app

 EXPOSE 80
```

</details>

And once that fix is applied, the app fails with following:

```
/usr/src/app/app/actions/invite.js has 2 errors and 0 warnings.
  1: Unexpected 'debugger' statement. (no-debugger) at line 7:5
    debugger;
  2: Unexpected 'debugger' statement. (no-debugger) at line 9:5
    debugger;
```

**Comment by knownasilya** [comment]
Yes, I did fix both of those, and tried docker deploy and it froze on me several times. Trying again.
On the other hand, `now --npm` should work..

**Comment by knownasilya** [comment]
Ok, so I got docker deployed. Npm still fails though, which is the reason I'm using docker.

**Comment by jamo** [comment]
The issue seen with the npm deployment seems to be related to the unconventional manner how `denali` is not distributed transpired but has a more interesting solution for live transpiration. 

I've escalated this issue to the correct internal `now` module

**Comment by leo** [comment]
@jamo Can we close this now?

**Comment by knownasilya** [comment]
I'll test this asap, but it might be a bit, since I just became a father.

**Comment by jamo** [comment]
Docker build of the project works and due to the unconventional behaviour of denali npm deployment will still fail....

**Comment by knownasilya** [comment]
Thanks
