### ISSUE TITLE
Can't make a static deployment on OSS plan

### ISSUE THREAD

**Issue by matheuss** [vercel/vercel#1252]
```
▲ test-static now login fuidhifdsuh@zeit.co
> We sent an email to fuidhifdsuh@zeit.co. Please follow the steps provided
  inside it and make sure the security code matches Famous Newt.
✔ Email confirmed
✔ Fetched your personal details
> Ready! Authentication token and personal details saved in "~/.now"
▲ test-static echo 'fdffddfsifuisdhfd' > README.md
▲ test-static now 
(node:50613) ExperimentalWarning: The http2 module is an experimental API.
isFile undefined deploymentType undefined
> Deploying ~/dev/zeit/deployments-to-test/test-static under fuidhifdsuh@zeit.co
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> > NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
isFile undefined deploymentType undefined
> https://test-static-hvjnzmilqb.now.sh [in clipboard] [4s]
> Synced 1 file (18B) [4s]
> Build completed
> Error! An unexpected error occurred!
  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at waitForScale (/Users/matheus/dev/zeit/now-cli/src/providers/sh/commands/deploy.js:888:41)
    at Promise (/Users/matheus/dev/zeit/now-cli/src/providers/sh/commands/deploy.js:873:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at waitForScale (/Users/matheus/dev/zeit/now-cli/src/providers/sh/commands/deploy.js:888:41)
    at Promise (/Users/matheus/dev/zeit/now-cli/src/providers/sh/commands/deploy.js:873:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
▲ test-static 
```

**Comment by igorklopov** [comment]
A possible solution is https://github.com/zeit/now-cli/pull/1250/files

**Comment by igorklopov** [comment]
https://github.com/zeit/now-cli/pull/1253/files
