### ISSUE TITLE
Glob patterns in package.json doesn't work

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#127]
Having a glob pattern like following in files directive of package.json results in the following error:
```
  "files": [
    "*.js"
  ],
```

```
> Deploying ~/test
[debug] `package.json` found, assuming `deploymentType` = `npm`
> [debug] error: Error: ENOENT: no such file or directory, stat '/Users/me/test/*.js'
    at Error (native)
> Error! Unexpected error. Please try later. (ENOENT: no such file or directory, stat '/Users/me/test/*.js')
```

Workaround is to install earlier release e.g. `npm i -g now@0.28.0`

**Comment by OlliV** [comment]
Actually it sill fails to sync any files. I'm still going to implement #115 in a different way.

```
> module.js:474
>     throw err;
>     ^
> Error: Cannot find module '/home/nowuser/src/index.js'
>     at Function.Module._resolveFilename (module.js:472:15)
>     at Function.Module._load (module.js:420:25)
>     at Module.runMain (module.js:607:10)
>     at run (bootstrap_node.js:382:7)
>     at startup (bootstrap_node.js:137:9)
>     at bootstrap_node.js:497:3
> Error Error: Command node index.js ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> (node:94) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command node index.js ended with code 1
> (node:94) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
