### ISSUE TITLE
`Invalid time value` when running `now logs -f <instance_id>`

### ISSUE THREAD

**Issue by sergiodxa** [vercel/vercel#1311]
`Invalid time value` when running `now logs -f <instance_id>`

```bash
> Error! An unexpected error occurred!
  RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (/snapshot/repo/dist/now.js:10586:38)
    at printEvent (/snapshot/repo/dist/now.js:10546:54)
    at Parser.onData (/snapshot/repo/dist/now.js:8759:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (/snapshot/repo/node_modules/jsonlines/lib/parser.js:37:12) RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (/snapshot/repo/dist/now.js:10586:38)
    at printEvent (/snapshot/repo/dist/now.js:10546:54)
    at Parser.onData (/snapshot/repo/dist/now.js:8759:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (/snapshot/repo/node_modules/jsonlines/lib/parser.js:37:12)
```

Reported by `maticrivo` on zeit.chat

**Comment by somadeaki** [comment]
This happens every time I run `now log -f` after about 10 seconds.

**Comment by imevro** [comment]
Very annoying, when it will be fixed?

**Comment by yhjor** [comment]
still happening

**Comment by somadeaki** [comment]
Please fix this, debugging is impossible like this.

**Comment by jch-gh** [comment]
Would definitely be nice to get some traction behind fixing this one, as others have indicated.

**Comment by sreeramjayan** [comment]
@jchappell82 @somadeaki 
Could you'll provide steps to reproduce this issue? I am unable to see this error and my version of now is 12.0.0-canary.25.

**Comment by somadeaki** [comment]
@sreeramjayan here's my best attempt:

`now` version: 11.1.7

System:

Windows 10 Pro N x64 
Version 1709 
Build 16299.125

Every time I use the command `now logs -f my-deployment`, after about 10s, I get the error.

```
> Error! An unexpected error occurred!
  RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (C:\snapshot\repo\dist\now.js:12212:38)
    at printEvent (C:\snapshot\repo\dist\now.js:12158:54)
    at Parser.onData (C:\snapshot\repo\dist\now.js:18971:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (C:\snapshot\repo\node_modules\jsonlines\lib\parser.js:37:12) RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (C:\snapshot\repo\dist\now.js:12212:38)
    at printEvent (C:\snapshot\repo\dist\now.js:12158:54)
    at Parser.onData (C:\snapshot\repo\dist\now.js:18971:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (C:\snapshot\repo\node_modules\jsonlines\lib\parser.js:37:12)
```

I'm located in Europe, and the date and time format in my system looks like this:

First day of the week: Monday
Short date: yyyy. MM. dd.
Long date: yyyy. MMMM d.
Short time: H:mm
Long time: H:mm:ss

So for example, on the system tray, I see this:  

![image](https://user-images.githubusercontent.com/5340566/39727172-f4497942-5251-11e8-942e-4e09ec18809f.png)

The system language is English. Is there any more information that could be useful?

**Comment by jch-gh** [comment]
```
❯ now logs my-node-app-deployment-here.now.sh -f
> Fetched deployment "my-node-app-deployment-here.now.sh" in my-organization [832ms]
2018-05-07T21:34:52.344Z  Scale Factor:  2
2018-05-07T21:34:52.365Z  Density:  144
> Error! An unexpected error occurred!
  RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (/snapshot/repo/dist/now.js:12212:38)
    at printEvent (/snapshot/repo/dist/now.js:12158:54)
    at Parser.onData (/snapshot/repo/dist/now.js:18971:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (/snapshot/repo/node_modules/jsonlines/lib/parser.js:37:12) RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (/snapshot/repo/dist/now.js:12212:38)
    at printEvent (/snapshot/repo/dist/now.js:12158:54)
    at Parser.onData (/snapshot/repo/dist/now.js:18971:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (/snapshot/repo/node_modules/jsonlines/lib/parser.js:37:12)
```

The error occurred after waiting approximately 15 - 20 seconds. (the entire command from execution to error took 21 seconds)


Now version info:
```
❯ now --version
11.1.7
```
Provided by the Now desktop app, version 3.8.26, which appears to be the latest stable build.

OS: macOS 10.13.4 (17E199)

**Comment by sreeramjayan** [comment]
@somadeaki  and @jchappell82  thank you for the logs.
I downgraded my version to 11.1.7 and was able to see the issue. This has been fixed with [this commit](https://github.com/zeit/now-cli/commit/c7d97e38661fbe303e385e6a747a835656f61830#diff-54f7b949eb9e033897c94894ed91ec03) in version 12.0.0-canary.25. You can either use the canary version or wait for the next release.

**Comment by jch-gh** [comment]
Perfect, thanks so much for the follow up!

**Comment by somadeaki** [comment]
@sreeramjayan error no longer occurs after upgrading to canary. Thank you for the help!

**Comment by joecohens** [comment]
We are closing this issue due to inactivity. If you still need help with this issue, please respond and we will get back to you immediately.
