### ISSUE TITLE
Puppeteer "Page crash!" error

### ISSUE THREAD

**Issue by absentees** [vercel/vercel#1319]
I'm unable to get puppeteer to take a screenshot. 
I read in another issue to use a docker deployment and found the following Dockerfile.
```
FROM node:9-alpine

# Installs latest Chromium (63) package.
RUN apk update && apk upgrade && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add --no-cache \
      chromium@edge \
      nss@edge

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

# Help prevent zombie chrome processes
ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

COPY . /app/
WORKDIR app

# Install deps for server.
RUN yarn

# Skip downloading Chromium when installing puppeteer. We'll use the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Use Puppeteer 0.11.0 b/c it bundles Chromium 63.
RUN yarn add puppeteer@0.11.0

RUN addgroup -S pptruser && adduser -S -g pptruser pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser \
    && chown -R pptruser:pptruser /app

# Run user as non privileged.
USER pptruser

EXPOSE 8080

ENTRYPOINT ["dumb-init", "--"]
CMD ["yarn", "start"]
```
and im launching puppeteer with:
```
	const browser = await puppeteer.launch({
		executablePath: '/usr/bin/chromium-browser',
		args: ['--disable-dev-shm-usage','--no-sandbox', '--headless', '--disable-gpu']
	});
```

Is there something i'm missing? All i can think of is increasing shm-size but i thought if i used `--disable-dev-shm-usage` it would use `/tmp` instead of the 64MB limit in `/dev/shm`?

Error message:
```
> (node:27) UnhandledPromiseRejectionWarning: Error: Page crashed!
>     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:92:24)
>     at Session.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:88:56)
>     at Session.emit (events.js:180:13)
>     at Session._onMessage (/app/node_modules/puppeteer/lib/Connection.js:199:12)
>     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:98:19)
>     at WebSocket.emit (events.js:180:13)
>     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47)
>     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14)
>     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12)
>     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16)
>     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10)
>     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22)
>     at Socket.emit (events.js:180:13)
>     at addChunk (_stream_readable.js:274:12)
>     at readableAddChunk (_stream_readable.js:261:11)
>     at Socket.Readable.push (_stream_readable.js:218:10)
```

**Comment by jch-gh** [comment]
I believe this is because the Alpine build of Chrome currently predates the `--disable-dev-shm-usage` flag's implementation. (I think Alpine's on v63 or v64, where that flag was not launched until v65).

Since I can't see a means of specifying custom docker runtime options, you're probably out of luck until either Zeit allows custom arguments, or Alpine's repository catches up to the current build of Chromium.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by styfle** [comment]
Please see this blog post for Now 2.0: https://zeit.co/blog/serverless-chrome
