### ISSUE TITLE
[12.0.0-canary.23] logs invalid time value

### ISSUE THREAD

**Issue by lmachens** [vercel/vercel#1322]
When I use `-f` I get this error on Windows:
```
now logs -f app

> Error! An unexpected error occurred!
  RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (C:\snapshot\repo\dist\now.js:12212:38)
    at printEvent (C:\snapshot\repo\dist\now.js:12158:54)
    at Parser.onData (C:\snapshot\repo\dist\now.js:18971:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (C:\snapshot\repo\node_modules\jsonlines\lib\parser.js:37:12) RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.printLogShort [as short] (C:\snapshot\repo\dist\now.js:12212:38)
    at printEvent (C:\snapshot\repo\dist\now.js:12158:54)
    at Parser.onData (C:\snapshot\repo\dist\now.js:18971:34)
    at Parser.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Parser.Readable.push (_stream_readable.js:209:10)
    at Parser.Transform.push (_stream_transform.js:146:32)
    at Parser._handleLines (C:\snapshot\repo\node_modules\jsonlines\lib\parser.js:37:12)
```

**Comment by lmachens** [comment]
Duplicate of https://github.com/zeit/now-cli/issues/1311
