### ISSUE TITLE
Error when running: now domains rm domain.com

### ISSUE THREAD

**Issue by tima101** [vercel/vercel#1329]
When running `now domains rm yourdomain.com`, I get following error:
```
tima@tima-HP:~$ now domains rm findharbor.com
> The following domain will be removed permanently
  findharbor.com      331d ago
> Warning! This domain's 1 alias will be removed. Run `now alias ls` to list them.
> Warning! This domain's 4 certificates will be removed. Run `now cert ls` to list them.
> Are you sure? [y/N] y
> Success! Domain findharbor.com removed [2s]
> Error! An unexpected error occurred!
  Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:133:17) Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:133:17)
```
According to Zeit dashboard, domain gets successfully removed, yet this error is still confusing.

**Comment by leo** [comment]
This is fixed now!
