### ISSUE TITLE
Error: Failed to load gRPC binary module because it was not installed for the current system

### ISSUE THREAD

**Issue by kidGodzilla** [vercel/vercel#1353]
Using Firebase, one dependency for the greater google-cloud library is gRPC (via `@google-cloud/common-grpc`).

After a recent update, I started getting build errors that seem like a configuration / now.sh image issue (unless I'm mistaken). Worked up until a few days ago on now.sh (paid acct).

Issue was resolved by moving back to `node 9.11.1`. Seemed like something that should be supported on node >=10, however. Figured I would report it & send logs.

---

Original Log output:
```
>   Build complete.
> 
> 
> ▲ Saving deployment image (110.3M)
> Build completed
> Verifying instantiation in sfo1
> [0] 
> [0] mr365-admin@1.0.0 now-start /home/nowuser/src
> [0] node index
> [0] 
> [0] /home/nowuser/src/node_modules/grpc/src/grpc_extension.js:55
> [0]     ^
> [0] 
> [0] Error: Failed to load gRPC binary module because it was not installed for the current system
> [0] Expected directory: node-v64-linux-x64-musl
> [0] Found: [node-v57-linux-x64-musl]
> [0] This problem can often be fixed by running "npm rebuild" on the current system
> [0] Original error: Cannot find module '/home/nowuser/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-musl/grpc_node.node'
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/grpc/src/grpc_extension.js:53:17)
> [0]     throw error;
> [0]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [0]     at Module.load (internal/modules/cjs/loader.js:589:32)
> [0]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [0]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [0]     at Module.require (internal/modules/cjs/loader.js:626:17)
> [0]     at require (internal/modules/cjs/helpers.js:20:18)
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/grpc/src/client.js:37:12)
> [0]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! mr365-admin@1.0.0 now-start: `node index`
> [0] npm ERR! Exit status 1
> [0] npm ERR! 
> [0] npm ERR! Failed at the mr365-admin@1.0.0 now-start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0] 
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-05-18T04_29_02_756Z-debug.log
> [0] More details: https://err.sh/now-cli/no-open-port-found
> [0] 
> [0] mr365-admin@1.0.0 now-start /home/nowuser/src
> [0] node index
> [0] 
> [0] /home/nowuser/src/node_modules/grpc/src/grpc_extension.js:55
> [0]     throw error;
> [0]     ^
> [0] 
> [0] Error: Failed to load gRPC binary module because it was not installed for the current system
> [0] Expected directory: node-v64-linux-x64-musl
> [0] Found: [node-v57-linux-x64-musl]
> [0] This problem can often be fixed by running "npm rebuild" on the current system
> [0] Original error: Cannot find module '/home/nowuser/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-musl/grpc_node.node'
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/grpc/src/grpc_extension.js:53:17)
> [0]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [0]     at Module.load (internal/modules/cjs/loader.js:589:32)
> [0]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [0]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [0]     at Module.require (internal/modules/cjs/loader.js:626:17)
> [0]     at require (internal/modules/cjs/helpers.js:20:18)
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/grpc/src/client.js:37:12)
> [0]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! mr365-admin@1.0.0 now-start: `node index`
> [0] npm ERR! Exit status 1
> [0] npm ERR! 
> [0] npm ERR! Failed at the mr365-admin@1.0.0 now-start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0] 
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-05-18T04_30_04_224Z-debug.log
> [0] More details: https://err.sh/now-cli/no-open-port-found
> [0] mr365-admin@1.0.0 now-start /home/nowuser/src
> [0] node index
> [0] 
> [0] 
> [0] /home/nowuser/src/node_modules/grpc/src/grpc_extension.js:55
> [0]     throw error;
> [0]     ^
> [0] 
> [0] Error: Failed to load gRPC binary module because it was not installed for the current system
> [0] Expected directory: node-v64-linux-x64-musl
> [0] Found: [node-v57-linux-x64-musl]
> [0] This problem can often be fixed by running "npm rebuild" on the current system
> [0] Original error: Cannot find module '/home/nowuser/src/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-musl/grpc_node.node'
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/grpc/src/grpc_extension.js:53:17)
> [0]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [0]     at Module.load (internal/modules/cjs/loader.js:589:32)
> [0]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [0]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [0]     at Module.require (internal/modules/cjs/loader.js:626:17)
> [0]     at require (internal/modules/cjs/helpers.js:20:18)
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/grpc/src/client.js:37:12)
> [0]     at Module._compile (internal/modules/cjs/loader.js:678:30)
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! mr365-admin@1.0.0 now-start: `node index`
> [0] npm ERR! Exit status 1
> [0] npm ERR! 
> [0] npm ERR! Failed at the mr365-admin@1.0.0 now-start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0] 
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-05-18T04_31_31_809Z-debug.log
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout
```

**Comment by siansell** [comment]
I am having the same problem with a next.js + firebase project, it is beyond my understanding but node v9.11.1 is fine, v10 fails as above. Let me know what diagnostics to provide and will do so.

Edit: fails on my local machine before deployment btw so not sure this is a `now` issue.

**Comment by leo** [comment]
Please deploy your application with the new [Now 2.0](https://zeit.co/blog/now-2). The error will not occur anymore!

**Comment by skaptox** [comment]
> Please deploy your application with the new [Now 2.0](https://zeit.co/blog/now-2). The error will not occur anymore!

That was not solved. 


> now.json
> {
>   "version": 2,
>   "name": "nextjs",
>   "builds": [{ "src": "next.config.js", "use": "@now/next" }]
> }


> package.json
> {
>   "name": "create-next-example-app",
>   "scripts": {
>     "dev": "next",
>     "build": "next build",
>     "start": "next start"
>   },
>   "dependencies": {
>     "@zeit/next-css": "^1.0.1",
>     "antd": "^3.19.7",
>     "babel-plugin-import": "^1.12.0",
>     "classnames": "^2.2.6",
>     "firebase-admin": "^8.2.0",
>     "firebase-functions": "^3.0.1",
>     "less": "^3.9.0",
>     "less-vars-to-js": "^1.3.0",
>     "next": "^8.1.0",
>     "next-redux-wrapper": "^3.0.0-alpha.3",
>     "null-loader": "^3.0.0",
>     "prop-types": "^15.7.2",
>     "react": "^16.8.6",
>     "react-dom": "^16.8.6",
>     "react-redux": "^7.1.0",
>     "redux": "^4.0.1",
>     "body-parser": "^1.19.0",
>     "express": "^4.17.1",
>     "express-session": "^1.16.2",
>     "firebase": "^6.2.2",
>     "isomorphic-unfetch": "3.0.0",
>     "session-file-store": "^1.3.0"
>   },
>   "devDependencies": {
>     "@zeit/next-less": "^1.0.1"
>   }
> }

And I am getting 


> { Error: Failed to load gRPC binary module because it was not installed for the current system
> Expected directory: node-v57-linux-x64-glibc
> Found: [node-v64-linux-x64-glibc]
> This problem can often be fixed by running "npm rebuild" on the current system
> Original error: Cannot find module '/home/ignisgravitas/workspace/kiwi/shopping/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node'

**Comment by Pushplaybang** [comment]
@leo this seems to be back with the latest version next / now / firebase, investigating
