### ISSUE TITLE
The deployment `readyState` is `INITIALIZING` and not `READY` isn't an  unexpected error

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#1381]
```
> Error! An unexpected error occurred in alias: Error: The deployment `readyState` is `INITIALIZING` and not `READY` (400)
```

**Comment by jamo** [comment]
```
> Error! An unexpected error occurred in alias: Error: The deployment is not yet snapshotted (400)
    at responseError (/snapshot/repo/dist/now.js:2250:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
