### ISSUE TITLE
An unexpected error occurred in alias: TypeError: (0 , _table.default) is not a function

### ISSUE THREAD

**Issue by hakimelek** [vercel/vercel#1386]
Running now alias for custom domain

> Error! An unexpected error occurred in alias: TypeError: (0 , _table.default) is not a function
    at zeitWorldTable (/snapshot/repo/dist/now.js:9571:29)
    at handleSetupDomainErrorImpl (/snapshot/repo/dist/now.js:5329:46)
    at set (/snapshot/repo/dist/now.js:5295:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

now version: 12.0.0-canary.40 or 11.2.1

**Comment by spoeken** [comment]
This happens to me as well. If i just run `now alias` (i have an alias set up in package.json), i get `> Error! Couldn't find a deployment to alias. Please provide one as an argument.`

now-cli 11.2.1

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-cli/pull/1387
