### ISSUE TITLE
Support all regions in scale property of now.json

### ISSUE THREAD

**Issue by seejamescode** [vercel/vercel#1401]
This works:
```
{
"scale": {
    "bru1": {
      "min": 1,
      "max": "auto"
    },
    "sfo1": {
      "min": 1,
      "max": "auto"
    }
  }
}
```

This throws an error:
```
{
"scale": {
    "all": {
      "min": 1,
      "max": "auto"
    }
  }
}
```

I would love to tell all regions to scale like you can with the CLI argument. However, this is the error it shows:

```
$ now
> Deploying ~/poster.tube under seejamescode
> Error! An unexpected error occurred!
  Error: You have the following errors inside `now.json` [{"keyword":"additionalProperties","dataPath":".scale","schemaPath":"#/properties/scale/additionalProperties","params":{"additionalProperty":"all"},"message":"should NOT have additional properties"}]
    at validateNowJson (/snapshot/repo/dist/now.js:17785:17)
    at readMetaData (/snapshot/repo/dist/now.js:17645:5)
    at <anonymous> Error: You have the following errors inside `now.json` [{"keyword":"additionalProperties","dataPath":".scale","schemaPath":"#/properties/scale/additionalProperties","params":{"additionalProperty":"all"},"message":"should NOT have additional properties"}]
    at validateNowJson (/snapshot/repo/dist/now.js:17785:17)
    at readMetaData (/snapshot/repo/dist/now.js:17645:5)
    at <anonymous>
error Command failed with exit code 1.
```

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
