### ISSUE TITLE
deploy failed (zero configuration project)

### ISSUE THREAD

**Issue by eavichay** [vercel/vercel#1425]
The project builds correctly on local (osx).

Failed with the following error
```
> webpack --config webpack.prod.config.js
>
> clean-webpack-plugin: /home/nowuser/src/dist has been removed.
>
> ERROR in main.bundle.js from UglifyJs
> TypeError: sym.definition is not a function
>     at may_modify (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8931:31)
>     at TreeTransformer.abort [as before] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8541:74)
>     at AST_VarDef.eval [as transform] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4586:25)
>     at doit (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:130:23)
>     at MAP (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:156:52)
>     at do_list (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4585:16)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4664:28)
>     at AST_Const.eval [as transform] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4573:17)
>     at collapse (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8617:39)
>     at tighten_body (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:8429:17)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:13689:9)
>     at AST_Function.eval [as optimize] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7682:23)
>     at Compressor.before (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7665:24)
>     at AST_Function.eval [as transform] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4586:25)
>     at doit (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:130:23)
>     at MAP (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:156:52)
>     at do_list (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4585:16)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4728:25)
>     at Compressor.before (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7660:9)
>     at AST_Array.eval [as transform] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4586:25)
>     at doit (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:130:23)
>     at MAP (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:156:52)
>     at do_list (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4585:16)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4688:21)
>     at Compressor.before (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:7660:9)
>     at AST_Call.eval [as transform] (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4570:35)
>     at eval (eval at <anonymous> (/home/nowuser/src/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:4598:31)
> npm ERR! errno 2
> npm ERR! code ELIFECYCLE
```

local node version 9.9.0
local npm version 5.6.0

Javascript error is awkward as it should not happen, it's not a network issue. Maybe environment variables?

**Comment by markozxuu** [comment]
@eavichay Hi! 👋 😸  could you give me more details of the application you were trying to deploy 🙏

**Comment by eavichay** [comment]
up-to-date repo
https://github.com/eavichay/slimjs-docs

**Comment by eavichay** [comment]
I'm not sure what details I could provide, In the repo you can find the webpack configuration and the scripts in package.json
