### ISSUE TITLE
Unable to install now package as it's being detected as a trojan by ESET antivirus on macOS

### ISSUE THREAD

**Issue by senhongo** [vercel/vercel#1433]
Installs failing when attempting to install now globally with either npm or yarn.

ESET deletes the below 3 files in the middle of installation, causing an `EACCESS` error.

![2018-07-03 15 53 32](https://user-images.githubusercontent.com/11208360/42203291-453a174a-7ed9-11e8-809e-011f2fa68e13.png)

```bash
 Error: EACCES: permission denied, open '/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/now'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at _callee2$ (/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/download.js:2675:59)
    at tryCatch (/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/download.js:2891:40)
    at Generator.invoke [as _invoke] (/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/download.js:3125:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/download.js:2943:21)
    at step (/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/download.js:3574:30)
    at _next (/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/download.js:3589:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/emp-mac-heng/.config/yarn/global/node_modules/now/download/dist/now' }
```

**Comment by alecglassford** [comment]
I'm using [Microsoft's enterprise antimalware software](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-protection) on Mac OS High Sierra, and it detects `/ur/local/bin/now` (installed via the Now.app desktop app) as `OSX/Agent.AK.trojan`.

Update: It was CLI version 11.1.2, but I updated to 11.2.5 and it's still getting flagged.

**Comment by leo** [comment]
Closing in favor of https://github.com/zeit/now-cli/issues/1444.
