### ISSUE TITLE
Babel build fails (says to add plugin, but plugin exists)

### ISSUE THREAD

**Issue by good-idea** [vercel/vercel#1469]
I'm trying to deploy but am getting a confusing error:

```
> ▲ npm run build
>
> mappslab-api@0.0.1 build /home/nowuser/src
> cross-env ENV=production babel . -d ./build
>
> { SyntaxError: /home/nowuser/src/node_modules/@babel/helper-plugin-utils/src/index.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (38:5):
>
>   36 |
>   37 |   return {
> 38 |     ...proto,
>      |     ^
>   39 |     ...api,
>   40 |   };
>   41 | }
>
> Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
```

But, `@babel/plugin-proposal-object-rest-spread` is already in my .babelrc:

```
{
	"presets": [
		"@babel/preset-flow",
		[
			"@babel/preset-env",
			{
				"targets": {
					"node": "current"
				}
			}
		]
	],
	"plugins": ["@babel/plugin-proposal-object-rest-spread"]
}
```

I've tested to make sure this file is actually being read, and it is: I removed the `@babel/preset-flow` preset and it broke on the first instance of Flow syntax, as expected.

- Tried on Node 8.x.x & 9.x.x
- Build can complete locally with no issues (OS X, node 8.10.0)

<details>
<summary>
<i>Full package.json</i>
</summary>

```
{
	"name": "my-project-api",
	"version": "0.0.1",
	"description": "Express-based central API",
	"main": "index.js",
	"author": "Joseph Thomas | Good Idea Studio",
	"license": "ISC",
	"scripts": {
		"start": "node ./build/server.js",
		"build": "cross-env ENV=production babel . -d ./build",
		"dev": "cross-env ENV=development cross-env DEBUG=api nodemon --watch . server.js --exec babel-node",
		"test": "cross-env ENV=development cross-env DEBUG=test cross-env TEST_DB=true jest --coverage",
		"test:watch": "cross-env ENV=development cross-env DEBUG=test cross-env TEST_DB=true jest --watch",
		"db:test:seed": "cross-env TEST_DB=true cross-env DEBUG=seed babel-node ./__tests__/scripts/testDatabase/seedTestDatabase.js"
	},
	"dependencies": {
		"@babel/cli": "7.0.0-beta.53",
		"@babel/core": "7.0.0-beta.53",
		"@babel/node": "7.0.0-beta.53",
		"@babel/plugin-proposal-class-properties": "^7.0.0-beta.53",
		"@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.53",
		"@babel/plugin-transform-runtime": "7.0.0-beta.53",
		"@babel/polyfill": "7.0.0-beta.53",
		"@babel/preset-env": "7.0.0-beta.53",
		"@babel/preset-flow": "7.0.0-beta.53",
		"@babel/register": "7.0.0-beta.53",
		"@babel/runtime": "7.0.0-beta.53",
		"babel-core": "7.0.0-bridge.0",
		"babel-plugin-import": "^1.7.0",
		"babel-plugin-module-resolver": "^3.1.1",
		"bcrypt": "^3.0.0",
		"crypto-promise": "^2.0.0",
		"debug": "^3.1.0",
		"dgraph-js": "^1.2.1",
		"dotenv": "^5.0.1",
		"flat": "^4.0.0",
		"graphql": "^0.13.2",
		"graphql-subscriptions": "^0.5.8",
		"graphql-tools": "^3.0.1",
		"graphql-yoga": "^1.13.1",
		"grpc": "^1.11.3",
		"joi": "^13.4.0",
		"json5": "^1.0.1",
		"jsonwebtoken": "^8.2.1",
		"lodash": "^4.17.10",
		"prop-types": "^15.6.1",
		"ramda": "^0.25.0",
		"validator": "^10.2.0"
	},
	"devDependencies": {
		"babel-core": "7.0.0-bridge.0",
		"babel-jest": "^23.4.0",
		"cross-env": "^5.2.0",
		"faker": "^4.1.0",
		"flow-bin": "^0.76.0",
		"jest": "^23.4.0"
	}
}

```

</details>

<details>
<summary>
<i>Full Now logs</i>
</summary>

```
> Deploying ~/Sites/mappslab/beta/api under good-idea
> Synced 1 file (192B) [1s]
> Using Node.js 9.11.2 (requested: `9.x.x`)
> https://mappslab-api-euvvwlzmur.now.sh [in clipboard] (sfo1) [6s]
> Building…
> ▲ npm install
> ⧗ Installing 37 main dependencies…
> Building "bcrypt@3.0.0" remotely
>     at extract (/snapshot/ace/lib/extract.js:36:11)
> Error: Error parsing `package.json` for bcrypt-3.0.0.tar
>     at <anonymous>
> ▲ npm install
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
>
> bcrypt@3.0.0 install /home/nowuser/src/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
>
> node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v59-linux-x64-musl.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.0 and node@9.11.2 (node-v59 ABI, musl) (falling back to source compile with node-gyp)
> make: Entering directory '/home/nowuser/src/node_modules/bcrypt/build'
>   CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
>   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
>   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
> [grpc] Success: "/home/nowuser/src/node_modules/grpc/src/node/extension_binary/node-v59-linux-x64-musl/grpc_node.node" is installed via remote
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN mappslab-api@0.0.1 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>
> added 1021 packages in 19.462s
> ▲ npm run build
>
> mappslab-api@0.0.1 build /home/nowuser/src
> cross-env ENV=production babel . -d ./build
>
>   SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
>   COPY Release/bcrypt_lib.node
>   COPY /home/nowuser/src/node_modules/bcrypt/lib/binding/bcrypt_lib.node
>   TOUCH Release/obj.target/action_after_build.stamp
> make: Leaving directory '/home/nowuser/src/node_modules/bcrypt/build'
>
> grpc@1.13.0 install /home/nowuser/src/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library
>
> npm WARN The package babel-core is included as both a dev and production dependency.
> { SyntaxError: /home/nowuser/src/node_modules/@babel/helper-plugin-utils/src/index.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (38:5):
>
>   36 |
>   37 |   return {
> 38 |     ...proto,
>      |     ^
>   39 |     ...api,
>   40 |   };
>   41 | }
>
> Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
>     at Parser.raise (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:3898:15)
>     at Parser.expectPlugin (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5232:18)
>     at Parser.parseObj (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:6637:14)
>     at Parser.parseExprAtom (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:6269:21)
>     at Parser.parseExprSubscripts (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5903:21)
>     at Parser.parseMaybeUnary (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5882:21)
>     at Parser.parseExprOps (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5791:21)
>     at Parser.parseMaybeConditional (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5763:21)
>     at Parser.parseMaybeAssign (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5710:21)
>     at Parser.parseExpression (/home/nowuser/src/node_modules/@babel/parser/lib/index.js:5663:21)
>   pos: 1122,
>   loc: Position { line: 38, column: 4 },
>   missingPlugin: [ 'objectRestSpread' ],
>   code: 'BABEL_PARSE_ERROR' }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mappslab-api@0.0.1 build: `cross-env ENV=production babel . -d ./build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mappslab-api@0.0.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-07-14T01_45_28_498Z-debug.log
> Error! Build failed
```

</details>

**Comment by good-idea** [comment]
Sorry, this is not a problem with Now.
My build script was `babel . -d ./build`, so it was compiling everything in `api/node_modules`. This is part of a monorepo, so, locally the install works because that project's node modules folder was pretty much empty, as yarn had installed everything at root. Oops!
