### ISSUE TITLE
Error when creating alias - Unknown error: TypeError: Cannot read property 'created' of undefined

### ISSUE THREAD

**Issue by appodeepa** [vercel/vercel#147]
I've updated to 0.31.0 and am trying to alias my deployment. I get to the cert stage and then kaput! 
Here's the tapestry of failure: 
```
> my.alias.name is a custom domain.
> Verifying the DNS settings for my.alias.name (see https://zeit.world for help)
> [debug] #1 GET /whois-ns: 754ms
> [debug] Found domain alias.name and nameservers dns1.registrar-servers.com,dns2.registrar-servers.com
> [debug] No records found for "my.alias.name"
> [debug] Trying to register a non-ZeitWorld domain .alias.name for the current user
> [debug] #1 POST /domains: 653ms
> [debug] Domain already exists (noop)
> Verification OK!
> [debug] closing agent
> [debug] /now/deployments/dEpLoYmENtID/aliases #1: 1230ms
> Provisioning certificate for my.alias.name
> [debug] /now/certs #1: 9358ms
> Error! Unknown error: TypeError: Cannot read property 'created' of undefined
    at Alias._callee5$ (C:\Users\My\AppData\Roaming\npm\node_modules\now\build\lib\alias.js:470:32)
    at tryCatch (C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\regenerator-runtime\runtime.js:63:40)

    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\regenerator-runtime\runtime.js:337:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\regenerator-runtime\runtime.js:96:21)
    at step (C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

    at run (C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:87:22)
    at C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Users\My\AppData\Roaming\npm\node_modules\now\node_modules\babel-runtime\node_modules\core-js\library\modules\_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:415:9)
```

**Comment by leo** [comment]
I think this was solved in https://github.com/zeit/now/pull/154

**Comment by manjula-dube** [comment]
Version 11.3.9 still gives me this error 

Any solution to fix this ?
