### ISSUE TITLE
EACCES: open permission denied on TypeScript Next.js application

### ISSUE THREAD

**Issue by ythecombinator** [vercel/vercel#1470]
### Description

I'm trying to deploy a PWA which, amongst other stuff, includes both next.js and TypeScript on its stack.

Turns out that I'm getting the following error when deploying to now.sh:

<img width="1363" alt="captura de tela 2018-07-13 as 18 58 49" src="https://user-images.githubusercontent.com/2644563/42719621-2fa192be-86ef-11e8-8e78-2fc6bb9169d5.png">

And this pops out a bunch of `502` errors on the browser:

<img width="496" alt="captura de tela 2018-07-13 as 22 49 45" src="https://user-images.githubusercontent.com/2644563/42719618-180726b4-86ef-11e8-88b8-b24acda59385.png">

(Besides a broken application).

On a quick search I could found plenty of issues with the very same error except for the fact that they're generally caused by:

- Unfixed your npm permissions;
- Misusage of ` build` and `start` scripts;
- Something related to the ones above;

The closest I could find was [this comment](https://github.com/zeit/now-cli/issues/175#issuecomment-346182206) but it didn't work.

Do you guys have any idea on what's going on?–I mean it seems to me that apps with our stack are quite rare in next.js so I don't really know if it's a mistake of mine or it's something with now.sh or maybe next.js.

#### Dependencies and devDependencies:

Here are the ones related to now/next:

```json
"next": "^6.1.1",
"next-compose-plugins": "^2.1.1",
"next-redux-saga": "3.0.0-beta.1",
"next-redux-wrapper": "2.0.0-beta.6",
"next-offline": "^2.7.3",
"next-progressbar": "^1.0.0",
"next-runtime-dotenv": "^1.0.1",

"babel-plugin-inline-dotenv": "^1.1.2",
"babel-plugin-module-resolver": "^3.1.1",
"babel-plugin-transform-class-properties": "^6.24.1",
"babel-plugin-transform-decorators-legacy": "^1.3.5",
"babel-plugin-transform-inline-environment-variables": "^0.4.3",

"now": "^11.2.9",
```

#### `next.config.js`:

```javascript
const withPlugins = require('next-compose-plugins');
const TypescriptPlugin = require('@zeit/next-typescript');
const ProgressBarPlugin = require('next-progressbar');
const Offline = require('next-offline');
const {PHASE_DEVELOPMENT_SERVER} = require('next/constants');

const nextConfig = {
  distDir: '../.next',
  exportPathMap: () => ({
    '/': {page: '/home'},
    '/home': {page: '/home'},
  }),
  webpack: (config, options) => {
    return config;
  },
};

module.exports = withPlugins(
  [[ProgressBarPlugin], [Offline, ['!', PHASE_DEVELOPMENT_SERVER]], [TypescriptPlugin]],
  nextConfig,
);
```
####  `server.js`:

```js
const {createServer} = require('http');
const {join} = require('path');
const {parse} = require('url');
const next = require('next');

const dev = process.env.NODE_ENV === 'development';
const app = next({dev, dir: 'src'});
const handle = app.getRequestHandler();
const port = process.env.PORT || 9001;

app.prepare().then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true);
    const {pathname} = parsedUrl;

    if (pathname === '/service-worker.js') {
      const filePath = join(__dirname, '.next', pathname);

      app.serveStatic(req, res, filePath);
    } else {
      handle(req, res, parsedUrl);
    }
  }).listen(port, () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

#### `now.json`:

Mast likely to be irrelevant here; contains just a few `alias`es.

**Comment by timothyis** [comment]
Hi @ythecombinator! So the problem here is that Now deployments are immutable. It seems to me that your application is trying to perform mutations whilst running rather than at build-time.
To get around this error, any mutations you're trying to perform should be run at build-time. This should also help bootup times! 

Our docs are lacking in this area, and I apologize for that. We are working on making them better 🙏

**Comment by ythecombinator** [comment]
Thanks for the quick reply, @timothyis! 

I get your point but it turns out that I can't really think of any possible mutation that could be happening at runtime. I know it's a not trivial question but do you have any ideas on this?

**Comment by timothyis** [comment]
@ythecombinator I could you paste the whole error (hiding any sensitive content if you wish) it could be helpful tracking that down. Looks like the touch module is the culprit, but we'll need to find out where that's being used 😅

**Comment by ythecombinator** [comment]
Sorry for the delay, @timothyis. Here's the complete log:

```log
07/14 03:33 AM (2d)
npm install
07/14 03:33 AM (2d)
✓ Using "yarn.lock"
07/14 03:33 AM (2d)
⧗ Installing 50 main dependencies…
07/14 03:33 AM (2d)
> Building "now@11.2.9" remotely
07/14 03:33 AM (2d)
    at <anonymous>
07/14 03:33 AM (2d)
Error: Error parsing `package.json` for now-11.2.9.tar
07/14 03:33 AM (2d)
    at extract (/snapshot/ace/lib/extract.js:36:11)
07/14 03:33 AM (2d)
    at process._tickCallback (internal/process/next_tick.js:188:7)
07/14 03:33 AM (2d)
exit code: 1
07/14 03:33 AM (2d)
yarn
07/14 03:33 AM (2d)
[1/4] Resolving packages...
07/14 03:33 AM (2d)
[2/4] Fetching packages...
07/14 03:33 AM (2d)
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
07/14 03:33 AM (2d)
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
07/14 03:33 AM (2d)
[3/4] Linking dependencies...
07/14 03:33 AM (2d)
warning "@zeit/next-typescript > @babel/preset-typescript > @babel/plugin-transform-typescript@7.0.0-beta.42" has unmet peer dependency "@babel/core@7.0.0-beta.42".
07/14 03:33 AM (2d)
warning "@zeit/next-typescript > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.0.0-beta.42" has unmet peer dependency "@babel/core@7.0.0-beta.42".
07/14 03:33 AM (2d)
warning "@zeit/next-typescript > @babel/preset-typescript@7.0.0-beta.42" has unmet peer dependency "@babel/core@7.0.0-beta.42".
07/14 03:33 AM (2d)
warning " > react-async-component@2.0.0" has unmet peer dependency "prop-types@^15.0.0".
07/14 03:33 AM (2d)
warning " > @babel/plugin-proposal-decorators@7.0.0-beta.52" has unmet peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
07/14 03:33 AM (2d)
warning "@babel/plugin-proposal-decorators > @babel/plugin-syntax-decorators@7.0.0-beta.52" has unmet peer dependency "@babel/core@>=7.0.0-beta.50 <7.0.0-rc.0".
07/14 03:33 AM (2d)
warning " > fork-ts-checker-webpack-plugin@0.4.3" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0 || ^4.0.0".
07/14 03:33 AM (2d)
warning "next-progressbar > webpackbar@2.6.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
07/14 03:33 AM (2d)
warning " > redux-devtools-extension@2.13.2" has incorrect peer dependency "redux@^3.1.0".
07/14 03:33 AM (2d)
[4/4] Building fresh packages...
07/14 03:33 AM (2d)
Done in 13.58s.
07/14 03:33 AM (2d)
exit code: 0
07/14 03:33 AM (2d)
npm run now-build
07/14 03:33 AM (2d)
07/14 03:33 AM (2d)
> belp@1.0.0 now-build /home/nowuser/src
07/14 03:33 AM (2d)
> echo 'Built on Buddy CI'
07/14 03:33 AM (2d)
07/14 03:33 AM (2d)
Built on Buddy CI
07/14 03:33 AM (2d)
exit code: 0
07/14 03:33 AM (2d)
Snapshotting deployment
07/14 03:33 AM (2d)
Saving deployment image (65.2M)
07/14 03:34 AM (2d)
npm start
07/14 04:50 PM (2d)
> belp@1.0.0 start /home/nowuser/src
07/14 04:50 PM (2d)
> NODE_ENV=production next src
07/14 04:50 PM (2d)
07/14 04:50 PM (2d)
Defining routes from exportPathMap
07/14 04:50 PM (2d)
[19:50:45] Compiling client
07/14 04:50 PM (2d)
[19:50:45] Compiling server
07/14 04:50 PM (2d)
> Using external babel configuration
07/14 04:50 PM (2d)
> Location: "/home/nowuser/src/.babelrc"
07/14 04:50 PM (2d)
 DONE  Compiled successfully in 12104ms19:50:57
07/14 04:50 PM (2d)
07/14 04:50 PM (2d)
[19:50:57] Compiled client in 12s
07/14 04:50 PM (2d)
[19:50:58] Compiled server in 13s
07/14 04:51 PM (2d)
> Building page: /home
07/14 04:51 PM (2d)
[19:51:07] Compiling client
07/14 04:51 PM (2d)
[19:51:07] Compiling server
07/14 04:51 PM (2d)
 DONE  Compiled successfully in 9364ms19:51:17
07/14 04:51 PM (2d)
07/14 04:51 PM (2d)
[19:51:17] Compiled client in 10s
07/14 04:51 PM (2d)
[19:51:18] Compiled server in 11s
07/14 04:51 PM (2d)
events.js:183
07/14 04:51 PM (2d)
      throw er; // Unhandled 'error' event
07/14 04:51 PM (2d)
      ^
07/14 04:51 PM (2d)
07/14 04:51 PM (2d)
Error: EACCES: permission denied, open '/home/nowuser/src/src/pages/home/index.ts'
07/14 04:51 PM (2d)
    at Object.fs.openSync (fs.js:646:18)
```

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
