### ISSUE TITLE
All commands reply with: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by vikkio88** [vercel/vercel#1552]
I have tried any version, even the most updated one, both with yarn or npm and I still get the same error, the following:
```
-> % sudo yarn global add now@12.0.0-canary.78
yarn global v0.16.1
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed now@12.0.0-canary.78 with binaries:
      - now
Done in 31.55s.
 
-> % now
> Error! An unexpected error occurred in deploy: TypeError: Cannot read property 'username' of undefined
    at getContextName (/snapshot/repo/dist/now.js:2435:48)
    at Object.main (/snapshot/repo/dist/now.js:8574:51)
    at main (/snapshot/repo/dist/now.js:15901:42)
    at <anonymous>
```

**Comment by joecohens** [comment]
Hi @vikkio88 can you please upgrade to the latest canary and retry?
