### ISSUE TITLE
While updating Now CLI to 12.0.0-canary.80, npm fails at the postinstall step

### ISSUE THREAD

**Issue by realtable** [vercel/vercel#1568]
I tried to install the new 12.0.0-canary.80 build of Now CLI, and the installation failed at this step:

```
$ npm install -g now@canary
/Users/realtable/.nvm/versions/io.js/v3.3.1/bin/now -> /Users/realtable/.nvm/versions/io.js/v3.3.1/lib/node_modules/now/download/dist/now

> now@12.0.0-canary.80 postinstall /Users/realtable/.nvm/versions/io.js/v3.3.1/lib/node_modules/now
> node download/install.js

/Users/realtable/.nvm/versions/io.js/v3.3.1/lib/node_modules/now/download/dist/download.js:8960
module.exports = (fp, opts) => {
                            ^^

SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/realtable/.nvm/versions/io.js/v3.3.1/lib/node_modules/now/download/install.js:16:1)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/realtable/.nvm/versions/io.js/v3.3.1/bin/iojs" "/Users/realtable/.nvm/versions/io.js/v3.3.1/bin/npm" "install" "-g" "now@canary"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! now@12.0.0-canary.80 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the now@12.0.0-canary.80 postinstall script 'node download/install.js'.
npm ERR! This is most likely a problem with the now package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node download/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls now
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/realtable/Documents/Other/hitsuji/npm-debug.log
```

The npm-debug.log is at this Gist:
https://gist.github.com/realtable/6526f3a8cf8ee2d93315bf9ff0276153

Does anyone know how to fix this?

**Comment by realtable** [comment]
As it turns out, I got it working using node.js instead of io.js. Maybe that should be in the documentation.
