### ISSUE TITLE
Not found while downloading 

### ISSUE THREAD

**Issue by BlueSlimee** [vercel/vercel#1592]
**OS** - Android

**NPM v** - 5.6.0

I can't download now cli. Why? Idk.
```js
> Downloading Now CLI 11.4.5 [                    ] 0%
Error: Not Found https://github.com/zeit/now-cli/releases/download/11.4.5/undefined.gz
    at _callee$ (/data/data/com.termux/files/usr/lib/node_modules/now/download/dist/download.js:2634:29)
    at tryCatch (/data/data/com.termux/files/usr/lib/node_modules/now/download/dist/download.js:2897:40)
    at Generator.invoke [as _invoke] (/data/data/com.termux/files/usr/lib/node_modules/now/download/dist/download.js:3131:22)
    at Generator.prototype.(anonymous function) [as next] (/data/data/com.termux/files/usr/lib/node_modules/now/download/dist/download.js:2949:21)
    at step (/data/data/com.termux/files/usr/lib/node_modules/now/download/dist/download.js:3580:30)
    at _next (/data/data/com.termux/files/usr/lib/node_modules/now/download/dist/download.js:3595:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by joecohens** [comment]
Hi @BlueSlimee can you share with me your device platform name? You can get it by starting node and running the next command:
``` 
$ node
``` 
```
> const { platform } = process
undefined
> platform
'darwin'
```

**Comment by wojpawlik** [comment]
Also on Termux, same issue.

```
$ node
> process.platform
'android'
```

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
