### ISSUE TITLE
Error: Unexpected response

### ISSUE THREAD

**Issue by toymachiner62** [vercel/vercel#1619]
I'm unable to deploy my docker app. Worked a couple of weeks ago. 

```
$ now -d
> Deploying ~/Sites/cremationsociety under toymachiner62
> [debug] [2018-10-14T22:40:10.862Z] Detected `deploymentType` = `docker`
> [debug] [2018-10-14T22:40:10.862Z] Detected `deploymentName` = "cremationsociety"
> [debug] [2018-10-14T22:40:10.862Z] Scale presets for deploy: {}
> [debug] [2018-10-14T22:40:10.864Z] Getting files
> [debug] [2018-10-14T22:40:10.865Z] Locating files /Users/tomcaflisch/Sites/cremationsociety
> [debug] [2018-10-14T22:40:10.866Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/.git
> [debug] [2018-10-14T22:40:10.866Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/.gitignore
> [debug] [2018-10-14T22:40:10.866Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/dragonfly.log
> [debug] [2018-10-14T22:40:10.869Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/log/capistrano.log
> [debug] [2018-10-14T22:40:10.869Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/log/development.log
> [debug] [2018-10-14T22:40:10.869Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/log/integration.log
> [debug] [2018-10-14T22:40:10.869Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/log/production.log
> [debug] [2018-10-14T22:40:10.869Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/log/skylight.log
> [debug] [2018-10-14T22:40:10.869Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/public/assets
> [debug] [2018-10-14T22:40:10.942Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/airbrussh-1.2.0/.gitignore
> [debug] [2018-10-14T22:40:10.944Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/bcrypt-3.1.11/.gitignore
> [debug] [2018-10-14T22:40:10.946Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/better_errors-2.1.1/.gitignore
> [debug] [2018-10-14T22:40:10.947Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/binding_of_caller-0.7.2/.gitignore
> [debug] [2018-10-14T22:40:10.949Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/capistrano-3.8.1/.gitignore
> [debug] [2018-10-14T22:40:10.950Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/capistrano-bundler-1.2.0/.gitignore
> [debug] [2018-10-14T22:40:10.951Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/capistrano-passenger-0.2.0/.gitignore
> [debug] [2018-10-14T22:40:10.952Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/capistrano-rails-1.2.3/.gitignore
> [debug] [2018-10-14T22:40:10.953Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/capistrano-rvm-0.1.2/.gitignore
> [debug] [2018-10-14T22:40:10.953Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/chronic-0.10.2/.gitignore
> [debug] [2018-10-14T22:40:10.955Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/.gitignore
> [debug] [2018-10-14T22:40:10.956Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/dragonfly-1.0.12/.gitignore
> [debug] [2018-10-14T22:40:10.957Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/dragonfly-activerecord-1.0.0/.gitignore
> [debug] [2018-10-14T22:40:10.957Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/dragonfly-activerecord-1.0.0/.gitmodules
> [debug] [2018-10-14T22:40:10.959Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/factory_girl-4.8.0/.gitignore
> [debug] [2018-10-14T22:40:10.961Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/guard-compat-1.2.1/.gitignore
> [debug] [2018-10-14T22:40:10.962Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/guard-rspec-4.7.3/.gitignore
> [debug] [2018-10-14T22:40:10.963Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/jquery-rails-2.0.3/.gitignore
> [debug] [2018-10-14T22:40:10.964Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/json-1.8.5/.gitignore
> [debug] [2018-10-14T22:40:10.964Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/kaminari-1.0.1/.gitignore
> [debug] [2018-10-14T22:40:10.968Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/nenv-0.3.0/.gitignore
> [debug] [2018-10-14T22:40:10.969Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/net-ssh-4.1.0/.gitignore
> [debug] [2018-10-14T22:40:10.970Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/orm_adapter-0.5.0/.gitignore
> [debug] [2018-10-14T22:40:10.971Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/public_suffix-2.0.5/.gitignore
> [debug] [2018-10-14T22:40:10.972Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/rack-test-0.6.3/.gitignore
> [debug] [2018-10-14T22:40:10.973Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/.gitignore
> [debug] [2018-10-14T22:40:10.974Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/rb-fsevent-0.9.8/.gitignore
> [debug] [2018-10-14T22:40:10.975Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/rollbar-2.14.1/.gitignore
> [debug] [2018-10-14T22:40:10.975Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/rollbar-2.14.1/.gitmodules
> [debug] [2018-10-14T22:40:10.978Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/ruby_dep-1.5.0/.gitignore
> [debug] [2018-10-14T22:40:10.979Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/sass-rails-4.0.5/.gitignore
> [debug] [2018-10-14T22:40:10.982Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/shellany-0.0.1/.gitignore
> [debug] [2018-10-14T22:40:10.985Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/slop-3.6.0/.gitignore
> [debug] [2018-10-14T22:40:10.987Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/sshkit-1.13.1/.gitignore
> [debug] [2018-10-14T22:40:10.988Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/therubyracer-0.12.3/.gitignore
> [debug] [2018-10-14T22:40:10.990Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/uglifier-3.1.9/.gitignore
> [debug] [2018-10-14T22:40:10.990Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/uglifier-3.1.9/.gitmodules
> [debug] [2018-10-14T22:40:10.991Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/whenever-0.9.7/.gitignore
> [debug] [2018-10-14T22:40:11.044Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/dragonfly-1.0.12/tmp/.gitignore
> [debug] [2018-10-14T22:40:11.066Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/thread_safe-0.3.6/spec/.gitignore
> [debug] [2018-10-14T22:40:11.104Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/capistrano-3.8.1/spec/support/.gitignore
> [debug] [2018-10-14T22:40:11.127Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/exception_notification-4.2.1/test/dummy/.gitignore
> [debug] [2018-10-14T22:40:11.139Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/font-awesome-rails-4.7.0.1/test/dummy/.gitignore
> [debug] [2018-10-14T22:40:11.162Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/rollbar-2.14.1/spec/dummyapp/.gitignore
> [debug] [2018-10-14T22:40:11.177Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/thread_safe-0.3.6/spec/support/.gitignore
> [debug] [2018-10-14T22:40:11.177Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/thread_safe-0.3.6/spec/thread_safe/.gitignore
> [debug] [2018-10-14T22:40:11.311Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/sass-rails-4.0.5/test/fixtures/alternate_config_project/.gitignore
> [debug] [2018-10-14T22:40:11.311Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/sass-rails-4.0.5/test/fixtures/engine_project/.gitignore
> [debug] [2018-10-14T22:40:11.312Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/sass-rails-4.0.5/test/fixtures/sass_project/.gitignore
> [debug] [2018-10-14T22:40:11.312Z] Ignoring /Users/tomcaflisch/Sites/cremationsociety/vendor/bundle/ruby/2.3.0/gems/sass-rails-4.0.5/test/fixtures/scss_project/.gitignore
> [debug] [2018-10-14T22:40:11.449Z] Locating files /Users/tomcaflisch/Sites/cremationsociety: 584.029ms
> [debug] [2018-10-14T22:40:11.458Z] Getting files: 593.840ms
> [debug] [2018-10-14T22:40:11.588Z] Computing hashes
> [debug] [2018-10-14T22:40:12.412Z] Computing hashes: 823.458ms
> [debug] [2018-10-14T22:40:12.586Z] Get files ready for deployment
> [debug] [2018-10-14T22:40:12.710Z] Get files ready for deployment: 123.110ms
> [debug] [2018-10-14T22:40:12.710Z] POST https://api.zeit.co/v4/now/deployments [object Object]
> [debug] [2018-10-14T22:42:15.143Z] POST https://api.zeit.co/v4/now/deployments [object Object]: 122431.678ms
> [debug] [2018-10-14T22:42:15.151Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1740:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] [2018-10-14T22:42:16.463Z] Get files ready for deployment
> [debug] [2018-10-14T22:42:16.571Z] Get files ready for deployment: 107.873ms
> [debug] [2018-10-14T22:42:16.571Z] POST https://api.zeit.co/v4/now/deployments [object Object]
> [debug] [2018-10-14T22:44:18.664Z] POST https://api.zeit.co/v4/now/deployments [object Object]: 122093.214ms
> [debug] [2018-10-14T22:44:18.668Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1740:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] [2018-10-14T22:44:20.971Z] Get files ready for deployment
> [debug] [2018-10-14T22:44:21.025Z] Get files ready for deployment: 53.364ms
> [debug] [2018-10-14T22:44:21.025Z] POST https://api.zeit.co/v4/now/deployments [object Object]
> [debug] [2018-10-14T22:46:23.294Z] POST https://api.zeit.co/v4/now/deployments [object Object]: 122267.596ms
> [debug] [2018-10-14T22:46:23.296Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1740:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] [2018-10-14T22:46:27.751Z] Get files ready for deployment
> [debug] [2018-10-14T22:46:27.886Z] Get files ready for deployment: 134.630ms
> [debug] [2018-10-14T22:46:27.886Z] POST https://api.zeit.co/v4/now/deployments [object Object]
> [debug] [2018-10-14T22:48:30.041Z] POST https://api.zeit.co/v4/now/deployments [object Object]: 122152.240ms
> [debug] [2018-10-14T22:48:30.043Z] Error: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1740:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> Error! Unexpected response
```

Now version:
```
$ now --version
11.4.6
```

**Comment by joecohens** [comment]
Hi @toymachiner62 can you share with me here or by email to support your deployment url so I can take a look?

**Comment by toymachiner62** [comment]
I never got a deployment url. It doesn’t seem to get that far. What I posted is the entire output from running `$ now -d`

**Comment by toymachiner62** [comment]
I added a `.dockerignore` file with these as the contents and it now works. 

```
spec/
test/
theme/
vendor/
```

Seems it has something to do with uploaded larger folders? Shouldn't it at least spit out a more helpful error message?

**Comment by menberg** [comment]
I'm having the same issue. Any hints on how to debug this?

Thanks!

This is my console output:

> [debug] [2018-11-01T14:06:44.304Z] Locating files /Users/menberg/dev/next/studentfilm-cms: 428.278ms
> [debug] [2018-11-01T14:06:44.309Z] Getting files: 434.003ms
> [debug] [2018-11-01T14:06:44.405Z] Computing hashes
> [debug] [2018-11-01T14:06:44.977Z] Computing hashes: 571.331ms
> [debug] [2018-11-01T14:06:45.135Z] Get files ready for deployment
> [debug] [2018-11-01T14:06:45.191Z] Get files ready for deployment: 55.744ms
> [debug] [2018-11-01T14:06:45.192Z] POST https://api.zeit.co/v4/now/deployments [object Object]
> [debug] [2018-11-01T14:08:45.673Z] POST https://api.zeit.co/v4/now/deployments [object Object]: 120461.917ms
> [debug] [2018-11-01T14:08:45.679Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1740:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Maybe related, same problem of another user:
https://spectrum.chat/thread/be1d99db-a046-4277-8feb-ba6a03216969 / https://gist.github.com/toymachiner62/e2beebae198820b3317bc89d521112da

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
