### ISSUE TITLE
Error with axios now V2.

### ISSUE THREAD

**Issue by aranajhonny** [vercel/vercel#1654]
Try add axios in a simple node.js deployment for now V2

code [repo example](https://github.com/aranajhonny/now-v2-bug.git)

index.js
```
const axios = require("axios");

module.exports = (req, res) => {
  res.end("ok");
};
```
now.json
```
{
  "version": 2,
  "builds": [
    { "src": "index.js", "use": "@now/node" }
  ]
}
```
package.json
```
{
  "name": "axios",
  "version": "1.0.0",
  "main": "index.js",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0"
  }
}
```

https://axios-19hsbrnoo.now.sh/ --> HTTP ERROR 500

logs
```
11/14 08:25 AM (0ms)
running npm install for rollup...
11/14 08:25 AM (0ms)
installing to /tmp/2c7d4910/rollup
11/14 08:25 AM (0ms)
yarn install v1.12.3
11/14 08:25 AM (0ms)
warning package.json: No license field
11/14 08:25 AM (0ms)
warning No license field
11/14 08:25 AM (0ms)
[1/4] Resolving packages...
11/14 08:25 AM (0ms)
success Already up-to-date.
11/14 08:25 AM (0ms)
Done in 0.16s.
11/14 08:25 AM (0ms)
uploading cache (1744 kb) to 139bb7314a64223ee4a0fac37d671a4e57cec81b333a7b36a16946aa2ff9f716...
11/14 08:25 AM (0ms)
finished
11/14 08:26 AM (0ms)
{ Error: Cannot find module 'supports-color'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/user/index.js:1:268)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by shabeermothi** [comment]
Am facing the same issue.

**Comment by aranajhonny** [comment]
ready fixed
