### ISSUE TITLE
node gyp and now 2

### ISSUE THREAD

**Issue by saintego** [vercel/vercel#1660]
Hi,
I'm trying now 2 with my next.js project and I'm getting error. First I'm surprised it is running yarn while I have `package-lock.json` there.  Here is the error log
```
[5/5] Building fresh packages...
11/15 12:59 AM (21m)
error /tmp/11797593/node_modules/tiny-secp256k1: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /tmp/11797593/node_modules/tiny-secp256k1
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/var/lang/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/11797593/node_modules/tiny-secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modu
11/15 12:59 AM (21m)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
11/15 12:59 AM (21m)
patching https://api-iad1.zeit.co/v2/now/deployments/dpl_Fo1JRNGAxcApmyc8qToXLGpc64PM/builds/bld_fs1248csf with {"readyState":"ERROR","errorCode":"BUILD_FAILED"}
11/15 12:59 AM (21m)
{ Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:9:62)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) reported: true }
```

**Comment by TooTallNate** [comment]
Unfortunately the builder environment doesn't contain a proper C++ compiler toolchain. Yarn obfuscates the error, but if you include a `package-lock.json` instead then the builder uses npm, which shows the actual error. For example:

```
2018-11-19T20:08:18.601Z  installing to /tmp/53bf279a/user/time
2018-11-19T20:08:19.941Z  > time@0.12.0 install /tmp/53bf279a/user/time/node_modules/time
                          > node-gyp rebuild

2018-11-19T20:08:21.334Z  make: Entering directory `/tmp/53bf279a/user/time/node_modules/time/build'
2018-11-19T20:08:21.335Z    CXX(target) Release/obj.target/time/src/time.o
2018-11-19T20:08:21.338Z  make: g++: Command not found
2018-11-19T20:08:21.338Z  make: *** [Release/obj.target/time/src/time.o] Error 127
2018-11-19T20:08:21.338Z  make: Leaving directory `/tmp/53bf279a/user/time/node_modules/time/build'
```

We will look into the possibility of including a C++ compiler, perhaps as a different builder. For now you will need to use modules that pre-compile their native binaries, which is more common these days thanks to the N-API in Node.js.

**Comment by benoror** [comment]
Having the same issue with [tiny-secp256k1](https://github.com/bitcoinjs/tiny-secp256k1) package:

https://zeit.co/benoror/sundly/9npoax2i7/logs

```
[4/4] Building fresh packages...
11/28 12:45 AM (2m)
error /tmp/dfc850/node_modules/tiny-secp256k1: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /tmp/dfc850/node_modules/tiny-secp256k1
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/var/lang/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/dfc850/node_modules/tiny-secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/no
11/28 12:45 AM (2m)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
11/28 12:45 AM (2m)
patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_3wmx5jWDJBCjYdsgTumdkRhZdRQv/builds/bld_4tl8y3scb with {"readyState":"ERROR","errorCode":"BUILD_FAILED"}
```

**Comment by anthonyjclark** [comment]
I am having the same issue with [nodehun](https://github.com/Wulf/nodehun).

@TooTallNate Was the possibility of adding g++ discussed?

```
2019-01-08T19:48:04.266Z  > nodehun@2.0.12 install /tmp/52d07d6a/user/node_modules/nodehun
                          > node-gyp rebuild
                          
2019-01-08T19:48:04.738Z  make: Entering directory `/tmp/52d07d6a/user/node_modules/nodehun/build'
2019-01-08T19:48:04.739Z    CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/affentry.o
2019-01-08T19:48:04.741Z  make: g++: Command not found
                          make: *** [Release/obj.target/hunspell/src/hunspell/src/hunspell/affentry.o] Error 127
2019-01-08T19:48:04.741Z  make: Leaving directory `/tmp/52d07d6a/user/node_modules/nodehun/build'
2019-01-08T19:48:04.743Z  gyp
2019-01-08T19:48:04.743Z   
2019-01-08T19:48:04.743Z  ERR! 
2019-01-08T19:48:04.743Z  build error 
```

**Comment by fdenzer** [comment]
I am (not successfully) building *pouchdb-server* on `Zeit Δ now`, since it requires an
```sh
npm i --python=`which python2.7`
```
to build node-gyp inside leveldown...

**Comment by orpheus** [comment]
Same problem with node-gyp. Found this thread and closed my issue: #1892 
Looks like `secp256k1@3.6.2` / `tiny-secp256k1@1.0.1` is the problem

**Comment by qaiser110** [comment]
Same issue deploying a Loopback.js API

Please reopen the issue, or suggest a fix. Thanks

```
npm ERR! iconv@2.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.3.2 install script.
```

**Comment by oogxdd** [comment]
anyone managed to solve this?
