### ISSUE TITLE
Koa app 500 error when trying to access js files

### ISSUE THREAD

**Issue by upupming** [vercel/vercel#1688]
Thanks for your great project!
I have read the documentation, but still cannot figure out how to serve my Koa app.

Here is my `app.js`:

```js
require('dotenv').config();
const Koa = require('koa');
const app = new Koa();
const bodyParser = require('koa-bodyparser');
const config = require('./config');
require('./prototypes');

app.use(bodyParser());

const router = require('./routes');
app.use(router.routes());

const server = app.listen(config.port, () => {
  console.log(`HITMers-server is running on port ${config.port}`);
});

module.exports = server;
```

And this is my `now.json`:

```json
{
  "version": 2,
  "name": "hitmers",
  "builds": [
    { "src": "src/app.js", "use": "@now/node-server" }
  ],
  "env": {
    "DATABASE_URL": "@database_url",
    "SECRET": "@secret",
    "STREAM_USERNAME": "@stream_username",
    "STREAM_PASSWORD": "@stream_password",
    "TZ": "Asia/Shanghai",
    "REGISTER_CODE": "@register_code"
  }
}
```

The problem is that after I deployed my project, I always get `HTTP ERROR 500`. I think it is because all other `js` files except `app.js` are not served, but is there any to serve the whole project?

**Comment by upupming** [comment]
Solved by using version 1 instead of version 2.

**Comment by rauchg** [comment]
@upupming Koa is possible with v2 as well, and recommended. Example:
https://github.com/zeit/now-examples/pull/157

**Comment by upupming** [comment]
Tried it, but got following error in the logs:

```
11/25 06:59 PM (29s)
Error while initializing entrypoint: { Error: EACCES: permission denied, scandir '/builddir'
    at Object.fs.readdirSync (fs.js:904:18)
    at mapDir (/var/task/user/src/app.js:38575:30)
    at dirs.forEach.dir (/var/task/user/src/app.js:38579:17)
    at Array.forEach (<anonymous>)
    at mapDir (/var/task/user/src/app.js:38578:8)
    at Object.<anonymous> (/var/task/user/src/app.js:38593:18)
    at Object.module.exports.VERSION (/var/task/user/src/app.js:38595:30)
    at __webpack_require__ (/var/task/user/src/app.js:21:30)
    at Object.<anonymous> (/var/task/user/src/app.js:34569:21)
    at __webpack_require__ (/var/task/user/src/app.js:21:30)
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/builddir' }
11/25 06:59 PM (29s)
REPORT RequestId: 2d9ee993-f0a1-11e8-a206-8da80bfd4385	Duration: 15.53 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 52 MB	
```

My app needs to read js file and map them to an object:

`src/controllers/index.js`

```js
const _ = require('lodash');
const fs = require('fs');
const path = require('path');

/**
 * map files under folder d to modules
 */
const mapDir = d => {
  const tree = {};

  // Get all folders/files under current folder
  const [dirs, files] = _(fs.readdirSync(d)).partition(p => fs.statSync(path.join(d, p)).isDirectory());

  // Map folders
  dirs.forEach(dir => {
    tree[dir] = mapDir(path.join(d, dir));
  });

  // Map files
  files.forEach(file => {
    if (path.extname(file) === '.js') {
      tree[path.basename(file, '.js')] = require(path.join(d, file));
    }
  });

  return tree;
};

// Export the mapped result
module.exports = mapDir(path.join(__dirname));
```

**Comment by archived001** [comment]
Get this error too. `fs.readdirSync` not working as expected, but it pretty useful pattern for dynamic loading. 

```
fs.readdirSync(path.join(__dirname, 'routes')).forEach(routeFileName => {
  if (/\.js$/.test(routeFileName)) {
    require(`./routes/${routeFileName}`)(app)
  }
})
```
