### ISSUE TITLE
[v2] Error while initializing entrypoint: Cannot find module '!!webpack amd options'  

### ISSUE THREAD

**Issue by benoror** [vercel/vercel#1706]
I'm getting the following error while using `@now/node` Builder with a simple `micro` service:

```
Error while initializing entrypoint: { Error: Cannot find module '!!webpack amd options'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.module.exports.parse.parse (/var/task/user/index.js:49869:18)
    at __webpack_require__ (/var/task/user/index.js:21:30)
    at /var/task/user/index.js:9116:19
    at Object.<anonymous> (/var/task/user/index.js:9126:3)
    at __webpack_require__ (/var/task/user/index.js:21:30)
    at Object.<anonymous> (/var/task/user/index.js:49822:20) code: 'MODULE_NOT_FOUND' }
```

Microservice source code: https://github.com/benoror/taxi-driver

Deployment logs: https://zeit.co/benoror/taxi-driver/iiw9mf2rh/logs

Spectrum discussion: https://spectrum.chat/zeit/now/v2-routes~1bb3d0c1-ec9d-4b1e-b069-1e6b0c79cb79?m=MTU0MzQ0OTQ1MjM3Mg==

**Comment by benoror** [comment]
Moved to https://github.com/zeit/now-builders/issues/100
