### ISSUE TITLE
Can't switch accounts after deleting team

### ISSUE THREAD

**Issue by alexlafroscia** [vercel/vercel#1721]
I started to play around with creating a Team on Now for a small project I'm working on, but decided against it. The team was active on the `now` CLI at the point that I deleted the team.

If I try to use `now`, I get the follow error:

> Error! Your team was deleted. You can switch to a different one using "now switch".

Totally reasonable, except that `now switch` throws a JavaScript exception

```
> Error! An unexpected error occurred in switch: TypeError: Cannot read property 'slug' of undefined
    at module.exports.__webpack_exports__.default.choices.findIndex.choice (/snapshot/repo/dist/index.js:42977:46)
    at Array.findIndex (<anonymous>)
    at module.exports.__webpack_exports__.default (/snapshot/repo/dist/index.js:42976:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by alexlafroscia** [comment]
I was able to get myself un-stuck by deleting `$HOME/.now` and logging in again

**Comment by colinhemphill** [comment]
I had the same issue, but @alexlafroscia's solution worked for me. Would be nice if there was a clear, built-in way to get around this.

**Comment by TooTallNate** [comment]
This is still valid. Here's the output from Now CLI v16.1.2-canary.2 after deleting the currently "scoped" team:

```
$ now team ls
⠴ Fetching teams> Error! Unauthorized

$ now switch
> Error! You are not a part of the current team anymore
```

**Comment by 10xchs** [comment]
This bug is still here and I have no idea what $HOME/.now is.

**Comment by sandren** [comment]
I was able to solve this by deleting `~/.local/share/com.vercel.cli`.
