### ISSUE TITLE
Error with require a particular package: `Cannot find module '/var/task/package.json'`

### ISSUE THREAD

**Issue by brettdh** [vercel/vercel#1736]
Easiest to show you an example:

https://github.com/brettdh/zeit-error-demo

Failing on `require('jsonapi-server')` (error goes away if I remove that line).

Error from logs when loading the deployed url:

```
    { Error: Cannot find module '/var/task/package.json'
        at webpackEmptyContext (/var/task/user/index.js:39005:9)
        at Object.module.exports.s (/var/task/user/index.js:6158:44)
        at __webpack_require__ (/var/task/user/index.js:21:30)
        at Object.module.exports.webpackEmptyContext.keys (/var/task/user/index.js:38989:14)
        at __webpack_require__ (/var/task/user/index.js:21:30)
        at module.exports.Object.defineProperty.value (/var/task/user/index.js:85:18)
        at Object.<anonymous> (/var/task/user/index.js:88:10)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32) code: 'MODULE_NOT_FOUND' }
```

This may be a problem with the `jsonapi-server` package, but I'm posting this here because I seemingly have no way to know whether that's true or not, and thus no way to proceed.

**Comment by brettdh** [comment]
Based on my findings here:

https://spectrum.chat/zeit/now/error-with-require-a-particular-package-cannot-find-module-var-task-package-json~9fdea285-e149-4fdc-ad54-3e4eced7dc86

It seems like I ought to perhaps move this to either zeit/now-builders or zeit/ncc. Which would be more appropriate?

**Comment by brettdh** [comment]
Left a comment here: https://github.com/zeit/ncc/issues/74#issuecomment-446222955

**Comment by juliangruber** [comment]
The problem is with this line:

https://github.com/holidayextras/jsonapi-server/blob/1f7a012b1d673473a7c3a9cc557c0cce14e859bd/lib/jsonApi.js#L3

Please either ask `jsonapi-server` mainteiners to change this `require` statement to something statically analyzable, or open a new issue in [zeit/ncc](https://github.com/zeit/ncc).
