### ISSUE TITLE
NPM  installation issue

### ISSUE THREAD

**Issue by KBPsystem777** [vercel/vercel#1784]
Hi guys,

Any issues right now in npm installation? I was trying to update Now-cli to latest, but after hitting `npm install -g now` on the terminal couple of times, I keep on receiving this error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'now' ]
2 info using npm@6.5.0
3 info using node@v9.10.1
4 verbose npm-session f25e3ab6825f4ce7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/now 61ms (from cache)
8 silly fetchPackageMetaData error for now@latest Unexpected end of JSON input while parsing near '...:"1.6.0","which-promi'
9 timing stage:rollbackFailedOptional Completed in 40ms
10 timing stage:runTopLevelLifecycles Completed in 2409ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...:"1.6.0","which-promi'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
11 verbose stack     at <anonymous>
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:118:7)
12 verbose cwd C:\Users\USERNAME
13 verbose Windows_NT 10.0.16299
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "now"
15 verbose node v9.10.1
16 verbose npm  v6.5.0
17 error Unexpected end of JSON input while parsing near '...:"1.6.0","which-promi'
18 verbose exit [ 1, true ]
```

Any idea? Thanks

**Comment by atherdon** [comment]
i was able to install `now` on my linux PC but i cannot login or use it too

**Comment by KudohAtsuo** [comment]
Hi @atherdon. I had the same situation and my solution is to add option '--unsafe-perm' like this:
`sudo npm install -g --unsafe-perm now`

It worked for me. Hope this might help :)

**Comment by atherdon** [comment]
@KudohAtsuo thank you for your help! i tried to install now with this flag, but it still shows me warning that i need to use `--unsave-perm` flag. I also test an assumption that now on Linux conflicts with latest node server, but when i revert it to stable LTS, clean cache and reisntall `now` - i have a same problem

**Comment by peterennis** [comment]
@KBPsystem777 

```
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Windows\system32>npm i -g now
C:\Users\peterennis\AppData\Roaming\npm\now -> C:\Users\peterennis\AppData\Roaming\npm\node_modules\now\download\dist\now

> now@12.1.14 postinstall C:\Users\peterennis\AppData\Roaming\npm\node_modules\now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 12.1.14 [====================] 100%

+ now@12.1.14
added 1 package in 2.621s

C:\Windows\system32>npm -v
6.4.1

C:\Windows\system32>node -v
v10.14.2

C:\Windows\system32>
```

You are using:

```
15 verbose node v9.10.1
16 verbose npm  v6.5.0
```

I cannot tell what version of now you are trying to install.

Now site mentions this:

![capture511](https://user-images.githubusercontent.com/140737/50663362-43c77b80-0f5e-11e9-9e73-39f5d58cd9a0.PNG)

Node shows:

![capture512](https://user-images.githubusercontent.com/140737/50663494-ae78b700-0f5e-11e9-89f7-662950499824.PNG)

Seems like the requirements may need an update.

**Comment by KBPsystem777** [comment]
Thanks everyone for your inputs. Tried to restart my machine and this seems to resolve the issue. lol
My current system versions:

```
C:\Users\USER_NAME>now --version
13.0.0

C:\Users\USER_NAME>node --version
v9.10.1

C:\Users\USER_NAME>npm --version
6.5.0
```
