### ISSUE TITLE
Include extra files in @node/now-server build

### ISSUE THREAD

**Issue by ramiel** [vercel/vercel#1788]
I'm trying to deploy a service using now v2.This service has sharp (and so a binary dependency on libvips) as dependency. The service correctly work on v1, but on v2 I have a non very clear error:

```
01/02 08:44 PM (14m)
info
01/02 08:44 PM (14m)
 
01/02 08:44 PM (14m)
sharp
01/02 08:44 PM (14m)
 Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.0/libvips-8.7.0-linux-x64.tar.gz
01/02 08:44 PM (14m)
npm
01/02 08:44 PM (14m)
 WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
01/02 08:44 PM (14m)

01/02 08:44 PM (14m)
added 917 packages in 18.119s
01/02 08:44 PM (14m)
npm
01/02 08:44 PM (14m)
 
01/02 08:44 PM (14m)
WARN using --force
01/02 08:44 PM (14m)
 I sure hope you know what you are doing.
01/02 08:44 PM (14m)
writing ncc package.json...
01/02 08:44 PM (14m)
running npm install for ncc...
01/02 08:44 PM (14m)
installing to /tmp/6071eff5/ncc
01/02 08:44 PM (14m)
using memory-fs for yarn cache
01/02 08:44 PM (14m)
yarn install v1.12.3
01/02 08:44 PM (14m)
warning package.json: No license field
01/02 08:44 PM (14m)
info No lockfile found.
01/02 08:44 PM (14m)
warning No license field
01/02 08:44 PM (14m)
[1/4] Resolving packages...
01/02 08:44 PM (14m)
[2/4] Fetching packages...
01/02 08:44 PM (14m)
[3/4] Linking dependencies...
01/02 08:44 PM (14m)
[4/4] Building fresh packages...
01/02 08:44 PM (14m)
success Saved lockfile.
01/02 08:44 PM (14m)
Done in 1.40s.
01/02 08:44 PM (14m)
running user script...
01/02 08:44 PM (14m)
preparing lambda files...
01/02 08:44 PM (14m)
compiling entrypoint with ncc...
01/02 08:44 PM (14m)
ncc: Module directory "/tmp/6071eff5/user/node_modules/node-fetch/lib" attempted to require "encoding" but could not be resolved, assuming external.
01/02 08:44 PM (14m)
patching https://api-bru1.zeit.co/v2/now/deployments/dpl_2FMQ5G675EN876seHbAijrXVS3Kt/builds/bld_arq2hvvdf with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
01/02 08:44 PM (14m)
{ Error: Hash: 56612fddcece3e2823d7
Version: webpack 4.27.0
Time: 2257ms
Built at: 2019-01-02 19:44:36
      Asset      Size  Chunks  Chunk Names
favicon.ico  1.84 KiB          
   index.js   738 KiB       0  main
 sharp.node   237 KiB          
Entrypoint main = index.js
  [0] external "path" 42 bytes {0} [built]
  [2] /tmp/6071eff5/user/node_modules/config/lib sync 160 bytes {0} [built]
  [9] /tmp/6071eff5/user/src/logger.js 339 bytes {0} [built]
 [10] external "util" 42 bytes {0} [built]
 [11] external "fs" 42 bytes {0} [built]
 [12] external "stream" 42 bytes {0} [built]
 [14] external "os" 42 bytes {0} [built]
 [15] /tmp/6071eff5/user/node_modules/micro/lib/index.js 3.75 KiB {0} [built]
 [17] /tmp/6071eff5/user/node_modules/config/lib/config.js 49.4 KiB {0} [built] [1 warning]
 [29] /tmp/6071eff5/user/node_modules/config/defer.js 539 bytes {0} [built]
 [30] external "http" 42 bytes {0} [built]
 [59] /tmp/6071eff5/user/index.js 318 bytes {0} [built]
 [60] /tmp/6071eff5/user/node_modules/config/raw.js 383 bytes {0} [built]
 [61] /tmp/6071eff5/user/node_modules/content-type/index.js 4.7 KiB {0} [built]
[125] /tmp/6071eff5/user/src/index.js 164 bytes {0} [built]
    + 190 hidden modules

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 883:15-35
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 968:12-28
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 771:8-23
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 781:21-42
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 801:19-40
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 805:19-38
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 814:21-42
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 817:13-30
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 767:21-42
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 888:28-45
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 919:16-34
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 928:14-32
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 936:14-32
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 944:13-30
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 951:13-30
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 962:16-36
Critical dependency: the request of a dependency is an expression
 @ /tmp/6071eff5/user/index.js

WARNING in /tmp/6071eff5/user/node_modules/config/lib/config.js 770:11-29
require.extensions is not supported by webpack. Use a loader in
```

**Comment by paulogdm** [comment]
Hello! Can you give us some code to investigate?

**Comment by ramiel** [comment]
Indeed. So, here the now.json configuration

```json
{
  "name": "caravaggio",
  "version": 2,
  "public": true,
  "builds": [
    {"src": "index.js", "use": "@now/node-server"}
  ]
}
```

The index.js file contains, more or less, this

```js
const config = require('config');
const micro = require('micro');
const logger = require('./src/logger');
const app = require('./src');

logger.debug(config, 'configuration:');
const port = config.get('port');

const server = micro(app);
server.listen(port);

logger.info(`Server started. Listen on port: ${port}.`);
```

So in app, as you can guess, there is the function that handles the requests.

**Comment by ramiel** [comment]
Oh, btw the project is public and available here https://gitlab.com/ramiel/caravaggio
The branch is `now-v2`. In case you want to know it deeper

**Comment by juliangruber** [comment]
When I try to build caravaggio now I get this error:

```
Error: The lambda function size (24.32mb) exceeds the configured limit (15mb). You may increase this by supplying `maxLambdaSize` to the build `config`
```

Increasing that limit to `50mb` fixed it to me:

```patch
diff --git a/now.json b/now.json
index d5a1d75..d5c5c9d 100644
--- a/now.json
+++ b/now.json
@@ -3,6 +3,10 @@
   "version": 2,
   "public": true,
   "builds": [
-    {"src": "index.js", "use": "@now/node-server"}
+    {
+      "src": "index.js",
+      "use": "@now/node-server",
+      "config": { "maxLambdaSize": "50mb" }
+    }
   ]
 }
```

Can you try this on your machine?

**Comment by ramiel** [comment]
Yes, I changed as you said and now the deployments is completed. I have another error now, related to some file is missing. This is probably related to the `config` package and the usage of webpack. The folder with the configuration, not being referenced by the code directly, is missing. I need to find a way to tell now to include it. Probably some other user had the same issue

**Comment by ramiel** [comment]
To test this you can call the deploy with `https://<deploy>.now.sh/rs_200x300_fill_auto/https://ramiel.gitlab.io/caravaggio/docs/assets/example/fill_original.png`

**Comment by ramiel** [comment]
Ok, I modified my now.json file to include static files (the configuration file). Now it looks like this

```json
{
  "name": "caravaggio",
  "version": 2,
  "public": true,
  "builds": [
    {
      "src": "index.js",
      "use": "@now/node-server",
      "config": {
        "maxLambdaSize": "50mb"
      }
    },
    {
      "src": "config/**",
      "use": "@now/static"
    },
    {
      "src": "./static",
      "use": "@now/static"
    }
  ]
}
```
Now the configuration folder is included alongside the output build.    
Nontheless the error reported is

```
03/07 08:41 AM (2m)
(output/index.js)
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
03/07 08:41 AM (2m)
(output/index.js)
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
03/07 08:41 AM (2m)
(output/index.js)
WARNING: No configurations found in configuration directory:/var/task/user/config
03/07 08:41 AM (2m)
(output/index.js)
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
03/07 08:41 AM (2m)
(output/index.js)
Error: Configuration property "logger" is not defined
    at Config.module.exports.Config.get (/var/task/user/index.js:1086:11)
    at Object.<anonymous> (/var/task/user/index.js:10229:42)
    at __webpack_require__ (/var/task/user/index.js:22:30)
    at Object.<anonymous> (/var/task/user/index.js:9012:16)
    at __webpack_require__ (/var/task/user/index.js:22:30)
    at module.exports.module.exports.Object.setPrototypeOf.__proto__ (/var/task/user/index.js:37:18)
    at Object.<anonymous> (/var/task/user/index.js:40:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

which means the configuration files are not found. The library used looks for a `./config` folder, relative to the running process as explained [here](https://github.com/lorenwest/node-config/wiki/Configuration-Files).

Maybe the process is running from a folder which is not `output`? How can I indicate the path to the output folder through environemnt variables?

**Comment by juliangruber** [comment]
@ramiel The `@now/static` builder will make static assets available to the web through static file serving, but _not_ to your node server unfortunately. Would it be possible to use a config system that uses `.js` or `.json` files, which the `@now/node-server` builder will properly include?

**Comment by ramiel** [comment]
It's not entirely clear? Should I produce a build by myself? The config system uses .js/.json files but includes them at runtime, so at build time the dependencies are not defined.
So, in general, any file included at runtime is not supported by @now/node-server?

**Comment by juliangruber** [comment]
`@now/node-server` uses [`@zeit/ncc`](https://github.com/zeit/ncc) internally, which compiles a Node.js project into a single file. For this to work it needs to be able to statically analyze your project, so it can assemble a list of files to include in the build. You're right that it uses Webpack for this. Currently, if webpack doesn't pick up your files, there's no way to include them.

You could try to build the app yourself, passing options and plugins to Webpack until it includes all the files you need.

**Comment by ramiel** [comment]
Isn't this a regression compared to "now" version 1, with which I'm able to run the very same project?

**Comment by juliangruber** [comment]
You're absolutely right that this was possible in Now 1.0 but currently isn't in Now 2.0. We're going to work on it!

**Comment by ramiel** [comment]
Great news! This is probably a case for a custom builder, but if this would be possible with current builders, it would be great.

**Comment by BarryThePenguin** [comment]
I've run into the same problem.. `node-config` [requires config files dynamically](https://github.com/lorenwest/node-config/blob/40e79b6aeac60da8344d6f72b1a721116180c6c6/lib/config.js#L773)

My guess is that now walks the dependency graph of `{"src": "index.js"}` to determine which files to include. As the config files are resolved dynamically, they aren't being included as part of the lambda bundle

My current configuration now looks like

```json
{
  "builds": [
    {
      "src": "admin/index.js",
      "use": "@now/node-server",
      "config": {
        "includeFiles": ["config/*"],
        "bundle": false,
        "maxLambdaSize": "50mb"
      }
    }
  ],
}
```

Haven't tried this deploying this yet 😬

**Comment by ramiel** [comment]
@BarryThePenguin any luck?

**Comment by BarryThePenguin** [comment]
No sorry.. I'm just experimenting at this stage, ran into other issues with the deploy

**Comment by Cretezy** [comment]
All of these don't work:
```js
          "packages/server/config/*",
          "packages/server/config/**",
          "packages/server/config/production.json"
```

Is there any solution to this? My full config looks roughly like so:
```json
    {
      "src": "packages/server/dist/index.js",
      "use": "@now/node",
      "config": {
        "includeFiles": [
          "packages/server/config/*",
          "packages/server/config/**",
          "packages/server/config/production.json"
        ]
      }
    }
```

**Comment by ramiel** [comment]
Any news on this?

**Comment by cullophid** [comment]
This would really help a lot since there are several libraries that have binary dependencies.

**Comment by ramiel** [comment]
Great, thank you!
