### ISSUE TITLE
now deploy error

### ISSUE THREAD

**Issue by simonqian** [vercel/vercel#179]
I got an error when I used `now` deploy my `next.js` demo app.

my package.json
```json
{
  "name": "next.demo",
  "dependencies": {
    "next": "*"
  },
  "scripts": {
    "start": "next"
  }
}
```

deploy info:
```
> Deploying ~/next.js.demo
> Using Node.js 7.0.0 (default)
> Ready! https://nextdemo-ydqafulcgt.now.sh (copied to clipboard) [2s]
> Upload [====================] 100% 0.0s
> Sync complete (988.09kB) [6s] 
> Initializing…
> Building
> ▲ npm install
> Installing package next@*
> (node:49) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, readlink '/home/nowuser/src/node_modules/.tmp/e80a788a-7778-4395-8e26-cb377e2482e2/node_modules/node-pre-gyp'
> (node:49) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.6.29
> node-pre-gyp info using node@7.0.0 | linux | x64
> node-pre-gyp info check checked for "/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3/lib/binding/Release/node-v51-linux-x64/fse.node" (not found)
> node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-linux-x64.tar.gz
> node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-linux-x64.tar.gz
> node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-linux-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
> node-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v51-linux-x64.tar.gz 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@7.0.0 | linux | x64
> gyp info ok 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@7.0.0 | linux | x64
> gyp http GET https://nodejs.org/download/release/v7.0.0/node-v7.0.0-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v7.0.0/node-v7.0.0-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v7.0.0/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v7.0.0/SHASUMS256.txt
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/.node-gyp/7.0.0/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/7.0.0',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info ok 
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@7.0.0 | linux | x64
> gyp info spawn make
> make: Entering directory '/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3/build'
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   SOLINK_MODULE(target) Release/obj.target/.node
>   COPY Release/.node
> make: Leaving directory '/home/nowuser/src/node_modules/dc1ba8196115775facd8a7e77d3b9c0387eea5f3/build'
> gyp info ok 
> node-pre-gyp info ok 
> ▲ npm start
> { Error: EACCES: permission denied, rmdir '/home/nowuser/src/.next'
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'rmdir',
>   path: '/home/nowuser/src/.next' }
> Error Error: Command next ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> (node:155) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command next ended with code 1
> (node:155) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```

I don't know where is wrong.
Who can help me? Thanks!

**Comment by jamo** [comment]
Checkout this: https://github.com/zeit/next.js#production-deployment

You should have the build and start scripts like this:
```
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
``

**Comment by simonqian** [comment]
@jamo
Thanks! It's work!
I was too careless...
