### ISSUE TITLE
Error: Cannot find module... [babel module-resolver + inline-react-svg]

### ISSUE THREAD

**Issue by chaance** [vercel/vercel#1797]
This error seems to be triggered by my SVG imports. Could be related to either the `module-resolver` or `inline-react-svg` plugins, but I'm not entirely sure. Pasting the error log along with my Babel & Next configs below for reference.

Note that errors are likewise thrown when I change all of the aliased imports to relative imports as well.

```
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
Error: Cannot find module '../../../static/icons/icon-x.svg' from '/tmp/661c4c3/components/organisms/disclosures-nav'
    at Function.module.exports [as sync] (/tmp/661c4c3/node_modules/resolve/lib/sync.js:58:15)
    at applyPlugin (/tmp/661c4c3/node_modules/babel-plugin-inline-react-svg/lib/index.js:64:41)
    at PluginPass.ImportDeclaration (/tmp/661c4c3/node_modules/babel-plugin-inline-react-svg/lib/index.js:168:13)
    at newFn (/tmp/661c4c3/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/tmp/661c4c3/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/tmp/661c4c3/node_modules/@babel/traverse/lib/index.js:94:17)
    at runLoaders (/tmp/661c4c3/node_modules/webpack/lib/NormalModule.js:286:20)
    at /tmp/661c4c3/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /tmp/661c4c3/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/tmp/661c4c3/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at loader.call.then.err (/tmp/661c4c3/node_modules/babel-loader/lib/index.js:45:103)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
Error: Cannot find module '../../../static/images/logo_dash.svg' from '/tmp/661c4c3/components/atoms/dash-logo'
    at Function.module.exports [as sync] (/tmp/661c4c3/node_modules/resolve/lib/sync.js:58:15)
    at applyPlugin (/tmp/661c4c3/node_modules/babel-plugin-inline-react-svg/lib/index.js:64:41)
    at PluginPass.ImportDeclaration (/tmp/661c4c3/node_modules/babel-plugin-inline-react-svg/lib/index.js:168:13)
    at newFn (/tmp/661c4c3/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/tmp/661c4c3/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/tmp/661c4c3/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/tmp/661c4c3/node_modules/@babel/traverse/lib/index.js:94:17)
    at runLoaders (/tmp/661c4c3/node_modules/webpack/lib/NormalModule
01/04 08:12 PM (13m)
> Build error occured
01/04 08:12 PM (13m)
Error: > Build failed because of webpack errors
    at Object.build [as default] (/tmp/661c4c3/node_modules/next/dist/build/index.js:42:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
01/04 08:12 PM (13m)
error Command failed with exit code 1.
01/04 08:12 PM (13m)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
01/04 08:12 PM (13m)
patching https://api-iad1.zeit.co/v2/now/deployments/dpl_7UnHA2WqfBf1yaLWT9zTW8GuQTQC/builds/bld_9aqz59qgi with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
01/04 08:12 PM (13m)
{ Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:11:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) reported: true }
```

next.config.js
```js
const dev = process.env.NODE_ENV === 'development';
const prod = process.env.NODE_ENV === 'production';
const { PHASE_PRODUCTION_SERVER } = dev
  ? {}
  : !process.env.NOW_REGION
    ? require('next/constants')
    : require('next-server/constants');

module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    return {};
  }
  const webpack = require('webpack');
  const withSass = require('@zeit/next-sass');
  require('dotenv').config({
    path: prod ? '.env.production' : '.env',
  });
  return withSass({
    sassLoaderOptions: {
      data: '@import "styles/global/global";',
    },
    serverRuntimeConfig: {
      mailgunApiKey: process.env.MAILGUN_API_KEY,
      mailgunDomain: process.env.MAILGUN_DOMAIN,
      contactFormTo: process.env.CONTACT_FORM_TO,
      contactFormFrom: process.env.CONTACT_FORM_FROM,
    },
    publicRuntimeConfig: {
      siteUrl: process.env.SITE_URL,
      wpUrl: process.env.WP_URL,
    },
    webpack: config => {
      const env = Object.keys(process.env).reduce((acc, curr) => {
        acc[`process.env.${curr}`] = JSON.stringify(process.env[curr]);
        return acc;
      }, {});
      config.plugins.push(new webpack.DefinePlugin(env));
      return config;
    },
  });
};

```

.babelrc.js
```js
module.exports = {
  presets: ['next/babel'],
  plugins: [
    [
      'inline-react-svg',
      {
        svgo: {
          plugins: [
            { removeAttrs: { attrs: '(data-name)' } },
            { cleanupIDs: true },
            { inlineStyles: true },
          ],
        },
      },
    ],
    ['transform-define'],
    [
      'module-resolver',
      {
        root: ['./'],
        alias: {
          root: './',
          context: './context',
          controllers: './controllers',
          components: './components',
          organisms: './components/organisms',
          atoms: './components/atoms',
          molecules: './components/molecules',
          templates: './components/templates',
          pages: './pages',
          styles: './styles',
          static: './static',
          images: './static/images',
          util: './util',
          data: './data',
        },
      },
    ],
  ],
};
```

**Comment by juliangruber** [comment]
@chancestrickland is it possible for you to share a self contained project that I can run on my local machine, demonstrating this error? It's tough to debug it otherwise.

**Comment by bramski** [comment]
Poke. I am having this problem as well.

**Comment by ArkeaOpenbanking** [comment]
Poke too ^^
Im' having the same problem with Create-React-App who is using svg-react-loader in the webpack config, and babel-module-resolver

**Comment by HelloMyDevWorld** [comment]
Any news ?

**Comment by mcsdevv** [comment]
Hey @patsadow2, @bramski, and @chancestrickland, I'm sorry if you are all experiencing this issue. Could one of you please provide a reproducible example so that we can take a look, please?

**Comment by bramski** [comment]
Oh a year ago! I'm sure I resolved this already or forgot about it. Sorry.

**Comment by trek** [comment]
Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
