### ISSUE TITLE
Now module not found, but I installed it

### ISSUE THREAD

**Issue by elhamdaoui** [vercel/vercel#1802]
$ node .\server.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'now'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\User\Documents\NetBeansProjects\MyApp\server.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Help please, I try in linux and windows and it's the same error

**Comment by paulogdm** [comment]
Could you give us more context?
Are you trying to install now locally as a package?

**Comment by elhamdaoui** [comment]
Hi @paulogdm ,
I try 'npm install -g now', 'npm install now'. I have this bug more than 10 days, I tried almost all the solutions on the forums.

Thanks.

**Comment by paulogdm** [comment]
We can't reproduce it.
Please, try to install `now` on your linux environment and give a screenshot of the output. `npm install -g now`.

**Comment by elhamdaoui** [comment]
Hi,
I installed it but i have:
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'now'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/MyApp/server.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by paulogdm** [comment]
Could you give me a screenshot of that? You can host it on Imgur.

**Comment by juliangruber** [comment]
closing because inactive
