### ISSUE TITLE
ENOENT: No such file directory open '/var/task/user/app/nodejs/platform.js'

### ISSUE THREAD

**Issue by haydarai** [vercel/vercel#1854]
So I'm trying to deploy my nodejs app, it was deployed but now it returns me this error.

```
{ Error: ENOENT: no such file or directory, open '/var/task/user/app/nodejs/platform.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at includeScript (/var/task/user/app/app.js:314931:28)
    at Object.<anonymous> (/var/task/user/app/app.js:314935:1)
    at __webpack_require__ (/var/task/user/app/app.js:22:30)
    at Object.module.exports.Object.defineProperty.value (/var/task/user/app/app.js:587846:8)
    at __webpack_require__ (/var/task/user/app/app.js:22:30)
    at Object.module.exports.pSlice (/var/task/user/app/app.js:549157:14)
    at __webpack_require__ (/var/task/user/app/app.js:22:30)
    at Object.<anonymous> (/var/task/user/app/app.js:420319:14)
    at __webpack_require__ (/var/task/user/app/app.js:22:30)
    at Object.<anonymous> (/var/task/user/app/app.js:170018:31)
    at __webpack_require__ (/var/task/user/app/app.js:22:30)
    at /var/task/user/app/app.js:39:18
    at Object.<anonymous> (/var/task/user/app/app.js:42:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/launcher.js:19:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/task/user/app/nodejs/platform.js' }
```

This is my `now.json`
```
{
  "version": 2,
  "builds": [
    {
      "src": "app/app.js",
      "use": "@now/node-server",
      "config": {
        "maxLambdaSize": "50mb"
      }
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "/app/app.js"
    }
  ]
}
```

Anyone have any idea of how to resolve this?

**Comment by haydarai** [comment]
decided not to go with `now` for now
