### ISSUE TITLE
Build failed cause by npm-micro-proxy

### ISSUE THREAD

**Issue by abnerlee** [vercel/vercel#1864]
Using `@now/next` cause following build errors

```
warning package.json: No license field
02/01 01:37 AM (2m)
info No lockfile found.
02/01 01:37 AM (2m)
warning store.typora.io: No license field
02/01 01:37 AM (2m)
[1/5] Validating package.json...
02/01 01:37 AM (2m)
warning store.typora.io: No license field
02/01 01:37 AM (2m)
[2/5] Resolving packages...
02/01 01:37 AM (2m)
[3/5] Fetching packages...
02/01 01:37 AM (2m)
error An unexpected error occurred: "/tmp/.cache/yarn/v4/npm-micro-proxy-1.1.0-87c8c16f7a7467f2d664423716ce415c31a284d7/node_modules/micro-proxy/.yarn-metadata.json: Unexpected end of JSON input".
02/01 01:33 AM (18s)
info If you think this is a bug, please open a bug report with the information provided in "/tmp/1719609f/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
02/01 01:33 AM (10s)
Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:14:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

I already tried 
```json
{
  "scripts": {
    "now-build": "npm uninstall micro-proxy && next build" 
  }
}
```

but still same error. Any help please?

BTW, I'm introducing micro-proxy in this way

```
"devDependencies": {
    "micro-proxy": "https://github.com/zeit/micro-proxy/archive/master.tar.gz",
}
```

change it into 
```
"devDependencies": {
    "micro-proxy": "^1.1.0",
}
```

any ideas on how to avoid this?

**Comment by abnerlee** [comment]
`micro-proxy` uses `Spread syntax` after npm install, which is not supported for node v8.1, I will use later node version
