### ISSUE TITLE
binding.open yarn cache problem

### ISSUE THREAD

**Issue by steida** [vercel/vercel#1874]
Another deploy, another error. It worked a few days ago. Now:

```
[3/5] Fetching packages...
02/04 05:10 AM (5m)
info There appears to be trouble with your network connection. Retrying...
02/04 05:11 AM (5m)
info There appears to be trouble with your network connection. Retrying...
02/04 05:11 AM (4m)
info There appears to be trouble with your network connection. Retrying...
02/04 05:12 AM (4m)
info There appears to be trouble with your network connection. Retrying...
02/04 05:12 AM (3m)
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/.cache/yarn/v4/npm-react-native-web-0.10.0-7c67a25d1262f01d462b3a11cc603aef47537d18/node_modules/react-native-web/dist/cjs/exports/StyleSheet/StyleSheetValidation.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.fs.createWriteStream.args [as createWriteStream] (/tmp/utils/node_modules/@now/build-utils/fs/bootstrap-yarn.js:30:6)
    at onfile (/var/task/bin/yarn:45435:20)
    at /var/task/bin/yarn:45467:31
    at /var/task/bin/yarn:45499:7
    at /var/task/bin/yarn:52814:26
    at FSReqWrap.oncomplete (fs.js:153:5)
02/04 05:12 AM (3m)
Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:14:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
02/04 05:12 AM (3m)
patching https://api-bru1.zeit.co/v2/now/deployments/dpl_5mejKJk65L4ac33dSx9jPtzkNf2R/builds/bld_kqvf6hmd1 with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

**Comment by igorklopov** [comment]
The issue is supposed to be fixed. Please try again. Feel free to reopen if something is still wrong.
