### ISSUE TITLE
dependency causing now cli v13.1.3 build to fail

### ISSUE THREAD

**Issue by orpheus** [vercel/vercel#1892]
I'm having troubles building my nextjs app so I decided to make the most minimal reproduction using the nextjs official walkthrough to test. It looks like it's having trouble making a C file, but I honestly don't know. 

**Steps to reproduce:** 

- https://nextjs.org/learn/basics/deploying-a-nextjs-app/setup
- clone, cd, checkout, add scripts, add now.json, etc (just run through that setup guide)

**_The single depency I added_**
 - `npm install oip-hdmw` (the core library I'm using in my real nextjs app which runs fine)

 - `now` 

Whenever installing `oip-hdmw` I see the `gyp` warnings, but it compiles, builds, and runs fine in dev/prod mode, but I don't know how to get `now` to build it. 

Also in the logs I noticed this line:
`WARNING: your application is being deployed in @now/next's legacy mode.` 
Why is this? Could this have anything to do with it?

**logs**
```
02/14 12:02 PM (21m)
normalized package.json result:  { name: 'hello-next',
  version: '1.0.0',
  description: '',
  scripts: 
   { test: 'echo "Error: no test specified" && exit 1',
     dev: 'next',
     build: 'next build',
     start: 'next start -p 8000',
     'now-build': 'NODE_OPTIONS=--max_old_space_size=3000 next build --lambdas' },
  keywords: [],
  author: '',
  license: 'ISC',
  dependencies: 
   { react: '^16.4.2',
     'react-dom': '^16.4.2',
     'next-server': 'v7.0.2-canary.49' },
  devDependencies: 
   { next: 'v7.0.2-canary.49',
     'oip-hdmw': '^1.3.24',
     'next-server': undefined } }
02/14 12:02 PM (21m)
installing dependencies...
02/14 12:02 PM (21m)
installing to /tmp/a0e44ea
02/14 12:02 PM (21m)
yarn install v1.12.3
02/14 12:02 PM (21m)
info No lockfile found.
02/14 12:02 PM (21m)
[1/4] Resolving packages...
02/14 12:02 PM (21m)
[2/4] Fetching packages...
02/14 12:03 PM (20m)
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
02/14 12:03 PM (20m)
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
02/14 12:03 PM (20m)
[3/4] Linking dependencies...
02/14 12:03 PM (20m)
[4/4] Building fresh packages...
02/14 12:03 PM (20m)
error /tmp/a0e44ea/node_modules/tiny-secp256k1: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /tmp/a0e44ea/node_modules/tiny-secp256k1
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.10.0/node-v8.10.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.10.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/var/lang/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/a0e44ea/node_modules/tiny-secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lang/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/.node-gyp/8.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/tmp/.node-gyp/8.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/var/lang/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/tmp/.node-gyp/8.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/a0e44ea/node_modules/tiny-secp256k1',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/tmp/a0e44ea/node_modules/tiny-secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/native/addon.o
make: g++: Command not found
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 127
make: Leaving directory `/tmp/a0e44ea/node_modules/tiny-secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/lang/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.94-89.73.amzn2.x86_64
gyp ERR! command "/var/lang/bin/node" "/var/lang/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/a0e44ea/node_modules/tiny-secp256k1
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
02/14 12:03 PM (20m)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
02/14 12:03 PM (20m)
Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:11:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
02/14 12:03 PM (20m)
[now] patching https://api-sfo1.zeit.co/v2/now/deployments/dpl_2LrZo32VDVw25rNZAWFMLXE8Q43J/builds/bld_ma5piosdz with {"readyState":"ERROR","errorCode":"BUILD_FAILED_2"}
```

**Comment by orpheus** [comment]
Also, in the official repo I'm trying to build, I get other log warnings like:
`error libp2p-crypto@0.16.0: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.10.0"`

I cannot seem to find in the docs where it specifies what node version `now` is using. I tried running my my install with `yarn install --ignore-engines` but it didn't do anything. So I'm not sure how I can get `now` to run a higher version of `node` if that's what I need to do.

**Comment by orpheus** [comment]
copy of #1660
