### ISSUE TITLE
14.0.0 throws error in bash on Windows

### ISSUE THREAD

**Issue by subtleGradient** [vercel/vercel#1895]
```
$ now
C:\ProgramData\nvm\v8.11.3\node_modules\now\download\dist\now.exe:1
(function (exports, require, module, __filename, __dirname) { MZ�
                                                                ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by subtleGradient** [comment]
Temporary workaround:

```
npm i -g now@13.1.3
```

works fine

**Comment by paulogdm** [comment]
Closing in favor of https://github.com/zeit/now-cli/issues/1894
