### ISSUE TITLE
Error trying to update, currently broken, can't install.

### ISSUE THREAD

**Issue by yougotashovel** [vercel/vercel#1975]
Getting the following error after trying to update now using `npm install -g now`

```
/Users/computer/.nvm/versions/node/v6.10.3/bin/now -> /Users/computer/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/now

> now@14.1.0 postinstall /Users/computer/.nvm/versions/node/v6.10.3/lib/node_modules/now
> node download/install.js

/Users/computer/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/index.js:10539
async function download() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/computer/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/install.js:16:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! now@14.1.0 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the now@14.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/computer/.npm/_logs/2019-03-16T22_33_09_367Z-debug.log
```

Can't figure out how to fix, currently can't deploy any of my sites.  Any pointers?

Thanks

**Comment by juliangruber** [comment]
@yougotashovel you need to run node version 8 or later for Now CLI to work. NVM should be able to do this
