### ISSUE TITLE
`now dev` issue with typescript

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2060]
Running into an issue with `now dev` in typescript:

```
ERROR in /Users/aaron/Library/Caches/co.zeit.now/dev/workPaths/61423409/user/server/sitemap.ts
Module build failed (from (webpack)/ncc/loaders/ts-loader.js):
Error: Cannot find module 'typescript'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1280:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function._load (/snapshot/repo/dist/index.js:1:1675574)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/aaron/Library/Caches/co.zeit.now/dev/workPaths/61423409/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:194038)
    at __webpack_require__ (/Users/aaron/Library/Caches/co.zeit.now/dev/workPaths/61423409/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:154)
    at Object.<anonymous> (/Users/aaron/Library/Caches/co.zeit.now/dev/workPaths/61423409/ncc/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js:1:113603)
```

I have typescript installed as a global dep, and as a dev-dep the parent dir of the mono-repo (where i'm running now dev), and in the project where this "sitemap.ts" file is

**Comment by cryptiklemur** [comment]
Happening on simple ts repos too, that arent mono-repos

**Comment by cryptiklemur** [comment]
After a cache clear this went away.

Ran into memory limit issues though. Had to run it a few times to finally build.

**Comment by styfle** [comment]
I confirmed that typescript works with the latest version 15.0.7

```sh
now init typescript
cd typescript
now dev
```
