### ISSUE TITLE
Can't add secrets

### ISSUE THREAD

**Issue by homerjam** [vercel/vercel#2064]
```
$ now secrets add foo "bar" --debug

> [debug] [2019-04-02T16:14:26.201Z] Found config in file /Users/jameshomer/Documents/projects/nuxtpress-now-kit/now.json
> [debug] [2019-04-02T16:14:26.208Z] Using Now CLI 15.0.1
> [debug] [2019-04-02T16:14:26.209Z] user supplied known subcommand
> [debug] [2019-04-02T16:14:26.221Z] GET https://api.zeit.co/www/user 
> [debug] [2019-04-02T16:14:26.221Z] Total requests made on socket #1: 1
> [debug] [2019-04-02T16:14:26.221Z] Concurrent requests on socket #1: 1
> [debug] [2019-04-02T16:14:26.934Z] GET https://api.zeit.co/www/user : 713.243ms
> [debug] [2019-04-02T16:14:26.941Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}
> [debug] [2019-04-02T16:14:26.941Z] Total requests made on socket #1: 1
> [debug] [2019-04-02T16:14:26.941Z] Concurrent requests on socket #1: 1
> [debug] [2019-04-02T16:14:27.615Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}: 673.200ms
> [debug] #1 POST /secrets: 674.153ms
> [debug] [2019-04-02T16:14:27.617Z] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at retry (/snapshot/repo/dist/index.js:1:446434)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> [debug] [2019-04-02T16:14:28.619Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}
> [debug] [2019-04-02T16:14:28.620Z] Total requests made on socket #1: 2
> [debug] [2019-04-02T16:14:28.620Z] Concurrent requests on socket #1: 1
> [debug] [2019-04-02T16:14:29.203Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}: 583.215ms
> [debug] #2 POST /secrets: 583.900ms
> [debug] [2019-04-02T16:14:29.205Z] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at retry (/snapshot/repo/dist/index.js:1:446434)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> [debug] [2019-04-02T16:14:31.205Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}
> [debug] [2019-04-02T16:14:31.205Z] Total requests made on socket #1: 3
> [debug] [2019-04-02T16:14:31.205Z] Concurrent requests on socket #1: 1
> [debug] [2019-04-02T16:14:31.787Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}: 582.024ms
> [debug] #3 POST /secrets: 582.468ms
> [debug] [2019-04-02T16:14:31.789Z] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at retry (/snapshot/repo/dist/index.js:1:446434)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> [debug] [2019-04-02T16:14:35.793Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}
> [debug] [2019-04-02T16:14:35.793Z] Total requests made on socket #1: 4
> [debug] [2019-04-02T16:14:35.793Z] Concurrent requests on socket #1: 1
> [debug] [2019-04-02T16:14:36.383Z] POST https://api.zeit.co/now/secrets {"name":"foo","value":"bar"}: 590.540ms
> [debug] #4 POST /secrets: 590.918ms
> Error! An unexpected internal error occurred
> [debug] [2019-04-02T16:14:36.387Z] Closing agent
> [debug] [2019-04-02T16:14:36.389Z] Closing agent
```

**Comment by paulogdm** [comment]
@homerjam The team is investigating! Thanks for the data provided...

**Comment by paulogdm** [comment]
This issue has been resolved! Thanks once again for the report.
