### ISSUE TITLE
Deployment stalling during build phase

### ISSUE THREAD

**Issue by homerjam** [vercel/vercel#2073]
Occurs during [this step](https://github.com/nuxt/now-builder/blob/master/lib/build.js#L33). Sometimes there's no error at all.

```
{ FetchError: request to https://dmmcy0pwk6bqi.cloudfront.net/15e78d181050e8b164f9c5d083d1641355404fb9 failed, reason: getaddrinfo EMFILE dmmcy0pwk6bqi.cloudfront.net:443
    at ClientRequest.<anonymous> (/var/task/worker.js:3659:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:355:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  message: 'request to https://dmmcy0pwk6bqi.cloudfront.net/15e78d181050e8b164f9c5d083d1641355404fb9 failed, reason: getaddrinfo EMFILE dmmcy0pwk6bqi.cloudfront.net:443',
  type: 'system',
  errno: 'EMFILE',
  code: 'EMFILE' }
```

**Comment by homerjam** [comment]
This is fixed by https://github.com/zeit/now-builders/pull/344
