### ISSUE TITLE
Error when installing ncc

### ISSUE THREAD

**Issue by FabienGreard** [vercel/vercel#2110]
Using `now-cli@15.0.3-canary.1`

When launching `now dev` I got an error from ncc 

```shell
error An unexpected error occurred: "There should only be one folder in a package cache (got )".
```

`ncc/yarn-error.log` output : 

```Arguments:
  /usr/local/bin/node /Users/fabiengreard/.yarn/bin/yarn.js --cwd /var/folders/nv/pzjtls3d2h38hj5q9lq6qk2r0000gn/T/co.zeit.now/dev/workPaths/5mp29jg8/ncc --prefer-offline

PATH:
  /Users/fabiengreard/.yarn/bin:/Users/fabiengreard/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version:
  1.13.0

Node version:
  10.12.0

Platform:
  darwin x64

Trace:
  Invariant Violation: There should only be one folder in a package cache (got )
      at invariant (/Users/fabiengreard/.yarn/lib/cli.js:2168:15)
      at /Users/fabiengreard/.yarn/lib/cli.js:59635:7
      at Generator.next (<anonymous>)
      at step (/Users/fabiengreard/.yarn/lib/cli.js:304:30)
      at /Users/fabiengreard/.yarn/lib/cli.js:315:13

npm manifest:
  {"license":"UNLICENSED","dependencies":{"@zeit/ncc":"0.17.3"}}

yarn manifest:
  No manifest

Lockfile:
  No lockfile
```

[Slack thread](https://zeit.slack.com/archives/CGLE0MVJR/p1554555999140600)

I did re-install `yarn`(and cleaning-up) without success.

**Comment by TooTallNate** [comment]
Try running `yarn cache clean`. I've seen the yarn cache get corrupted with error messages like these in the past.

**Comment by FabienGreard** [comment]
@TooTallNate Thanks, its worked !
