### ISSUE TITLE
Version 2.0.0 install broke `now`

### ISSUE THREAD

**Issue by vuchl** [vercel/vercel#212]
I got the message:
```bash
> UPDATE NEEDED Current: 1.0.0 – Latest 2.0.0 (released 5m ago)
> Run `npm install -g now` to update
```

I then ran
```bash
npm install -g now
```
This is the output:
```
/usr/bin/now -> /usr/lib/node_modules/now/bin/now
- babel-runtime@6.5.0 node_modules/now/node_modules/async-retry/node_modules/babel-runtime
- core-js@2.4.1 node_modules/now/node_modules/babel-runtime/node_modules/core-js
- exit-hook@1.1.1 node_modules/now/node_modules/exit-hook
- regenerator-runtime@0.10.1 node_modules/now/node_modules/regenerator-runtime
/usr/lib
└─┬ now@2.0.0 
  ├─┬ async-retry@0.2.1
  │ └── babel-runtime@6.5.0 
  ├─┬ async-to-gen@1.3.0 
  │ ├── babylon@6.14.1 
  │ └─┬ magic-string@0.19.0 
  │   └── vlq@0.2.1 
  ├─┬ ora@0.4.1 
  │ └─┬ cli-cursor@2.1.0 
  │   └─┬ restore-cursor@2.0.0 
  │     ├─┬ onetime@2.0.0 
  │     │ └── mimic-fn@1.1.0 
  │     └── signal-exit@3.0.2 
  └─┬ update-notifier@1.0.3 
    ├─┬ boxen@0.6.0 
    │ ├── ansi-align@1.1.0 
    │ ├── camelcase@2.1.1 
    │ ├── cli-boxes@1.0.0 
    │ ├── filled-array@1.1.0 
    │ ├─┬ repeating@2.0.1 
    │ │ └─┬ is-finite@1.0.2 
    │ │   └── number-is-nan@1.0.1 
    │ ├─┬ string-width@1.0.2 
    │ │ ├── code-point-at@1.1.0 
    │ │ └── is-fullwidth-code-point@1.0.0 
    │ └── widest-line@1.0.0 
    ├─┬ configstore@2.1.0 
    │ ├─┬ dot-prop@3.0.0 
    │ │ └── is-obj@1.0.1 
    │ ├── osenv@0.1.4 
    │ ├── uuid@2.0.3 
    │ └─┬ write-file-atomic@1.3.1 
    │   ├── imurmurhash@0.1.4 
    │   └── slide@1.1.6 
    ├── is-npm@1.0.0 
    ├─┬ latest-version@2.0.0 
    │ └─┬ package-json@2.4.0 
    │   ├─┬ got@5.7.1 
    │   │ ├── duplexer2@0.1.4 
    │   │ ├── node-status-codes@1.0.0 
    │   │ ├─┬ parse-json@2.2.0 
    │   │ │ └─┬ error-ex@1.3.0 
    │   │ │   └── is-arrayish@0.2.1 
    │   │ ├── read-all-stream@3.1.0 
    │   │ ├── timed-out@3.1.3 
    │   │ └── unzip-response@1.0.2 
    │   ├── registry-auth-token@3.1.0 
    │   └── registry-url@3.1.0 
    ├── lazy-req@1.1.0 
    ├─┬ semver-diff@2.1.0 
    │ └── semver@5.3.0 
    └─┬ xdg-basedir@2.0.0 
      └── os-homedir@1.0.2 
```

This happens when  running `now ls`
```bash
→ now ls                 
/usr/lib/node_modules/now/bin/now-list:72
.then(async token => {
      ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/now/node_modules/async-to-gen/register.js:40:5)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/now/bin/now:83:1)
```

or for `now help`:
```bash
/usr/lib/node_modules/now/bin/now-deploy:218
async function sync(token) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/lib/node_modules/now/node_modules/async-to-gen/register.js:40:5)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/now/bin/now:83:1)
```

**Comment by leo** [comment]
@vuchl Fixed in 2.0.1?

**Comment by vuchl** [comment]
Sadly not. Didi `npm install -g now@2.0.1`. Same error

**Comment by leo** [comment]
Fixed in the latest release!
