### ISSUE TITLE
serve: not found

### ISSUE THREAD

**Issue by johnlindquist** [vercel/vercel#215]
I've been trying to run the following for the past couple hours:

`now --static`

The output is

```
PS C:\Users\John Lindquist\projects\ramda-repl> now --static
> Deploying ~\projects\ramda-repl
> Using Node.js 7.0.0 (default)
> Ready! https://ramda-repl-ezhpeniyrp.now.sh (copied to clipboard) [1s]
> Initializing…
> Building
> ▲ npm install
> Installing package serve@latest
> ▲ npm start
> sh: serve: not found
> Error Error: Command serve ./content ended with code 127
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> (node:96) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command serve ./cont
ent ended with code 127
> (node:96) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit code.
```

Help please? 😄

**Comment by aranajhonny** [comment]
I get the same error.
version -- now 2.0.2 
![captura de pantalla 2017-01-11 a las 18 25 01](https://cloud.githubusercontent.com/assets/9091881/21869862/f747cd44-d82f-11e6-885f-a3f297f7438d.png)

**Comment by jamo** [comment]
It seems that a recent change in: https://github.com/zeit/serve/ causes this

**Comment by jamo** [comment]
Ok, this should now be fixed, please try deploying again.  
Please reopen/comment should it still fails.

Apologies for temporary regression with `now --static`

**Comment by mihaineacsu** [comment]
I'm getting this when deploying with now:
```
> Initializing…
> Building
> ▲ npm install
> ⧗ Installing 15 main dependencies…
> ✓ Installed 980 modules [2m]
> ▲ npm run build
> > cotd@0.0.1 build /home/nowuser/src
> > react-scripts build
> Creating an optimized production build...
> Compiled successfully.
> File sizes after gzip:
>   166.24 KB (-4 B)  build/static/js/main.b776bf2c.js
>   2.94 KB           build/static/css/main.baad6878.css
> The project was built assuming it is hosted at the server root.
> To override this, specify the homepage in your package.json.
> For example, add this to build it for GitHub Pages:
>   "homepage": "http://myname.github.io/myapp",
> The build folder is ready to be deployed.
> You may also serve it locally with a static server:
>   npm install -g pushstate-server
>   pushstate-server build
>   open http://localhost:9000
> ▲ npm start
> > cotd@0.0.1 start /home/nowuser/src
> > serve ./build --single
> sh: serve: not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! cotd@0.0.1 start: `serve ./build --single`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the cotd@0.0.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-06-27T22_00_53_288Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`.
```

package.json entry used:
```
"scripts": {
    "start": "serve ./build --single",
```

Any thoughts?

**Comment by leo** [comment]
`npm install serve --save`

**Comment by mihaineacsu** [comment]
Oops, thanks!

**Comment by alexverdaguer** [comment]
I got this error with now 2.5.7 and serve 6.1.0, any workaround ?

Thank you !

**Comment by iWexter** [comment]
Inside the folder build
npx serve

**Comment by lewisMachilika** [comment]
Did anyone get this working?
