### ISSUE TITLE
`@now/static-build` problem with gridsome

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#2157]
**now version**: 15.0.4-canary.6
**build**: @now/static-build

## Steps to reproduce 🐛 

```sh
git clone https://github.com/zeit/now-examples
cd gridsome
yarn install  # dependency installation
now dev # note the error output
```

I'm testing the example of **gridsome** of now-examples

logs

```Error: The module '/private/var/folders/nr/jvwl7m_j2n1gh2qlhd0ndczr0000gn/T/co.zeit.now/dev/workPaths/l41v9i98/node_modules/sharp/build/Release/sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/private/var/folders/nr/jvwl7m_j2n1gh2qlhd0ndczr0000gn/T/co.zeit.now/dev/workPaths/l41v9i98/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error! Exited with 1```

**Comment by markozxuu** [comment]
This was solved in the version: **15.0.7-canary.8**

Thank you so much @amio @leo @styfle 🙏
