### ISSUE TITLE
Next js Now build With Firebase Error

### ISSUE THREAD

**Issue by Raja0sama** [vercel/vercel#2186]
The Backstory is that I am converting my Portfolio super-sami.com to React Next js, So far i have Completed with the creation but now on build for NOW v2 serverless application i am facing this Firebase Error

./node_modules/@firebase/database/dist/index.node.cjs.js
Module not found: Can't resolve 'request' in 'E:\Development Enviroment\next-learn-demo\NextNow\nextjs\SuperSamii\node_modules\@firebase\database\dist'

My github Repo can be found here. https://github.com/dksami/SuperSamii

The Logs are here https://zeit.co/dksami/super-samiiprotfolios/c42pjz34b/logs

Anyone can guide me with this.

**Comment by paulogdm** [comment]
If you plan to use FireBase with Next.js and Now 2.0, please check: https://github.com/zeit/now-cli/issues/2186
Can you also redeploy and let me know the logs output?

**Comment by richcahill** [comment]
@paulogdm, you referenced this same issue in your comment.

**Comment by Raja0sama** [comment]
```

> hello-next@1.0.0 now-build /tmp/107705e6 > next build
--
BUILD | May 20 2019 13:56:44:137 | /package.json | Creating an optimized production build ...
BUILD | May 20 2019 13:57:04:887 | /package.json | Failed to compile.
BUILD | May 20 2019 13:57:04:887 | /package.json | ./node_modules/@firebase/database/dist/index.node.cjs.js Module not found: Can't resolve 'request' in '/tmp/107705e6/node_modules/@firebase/database/dist'
BUILD | May 20 2019 13:57:04:889 | /package.json | > Build error occurred
BUILD | May 20 2019 13:57:04:891 | /package.json | Error: > Build failed because of webpack errors     at Object.build [as default] (/tmp/107705e6/node_modules/next/dist/build/index.js:110:15)     at <anonymous>
BUILD | May 20 2019 13:57:04:905 | /package.json | npm
BUILD | May 20 2019 13:57:04:905 | /package.json | ERR! code ELIFECYCLE
BUILD | May 20 2019 13:57:04:906 | /package.json | npm ERR! errno
BUILD | May 20 2019 13:57:04:906 | /package.json | 1
BUILD | May 20 2019 13:57:04:907 | /package.json | npm
BUILD | May 20 2019 13:57:04:907 | /package.json | ERR! hello-next@1.0.0 now-build: `next build` npm
BUILD | May 20 2019 13:57:04:907 | /package.json | ERR! Exit status 1 npm
BUILD | May 20 2019 13:57:04:907 | /package.json | ERR!  npm
BUILD | May 20 2019 13:57:04:907 | /package.json | ERR! Failed at the hello-next@1.0.0 now-build script. npm
BUILD | May 20 2019 13:57:04:908 | /package.json | ERR! This is probably not a problem with npm. There is likely additional logging output above.
BUILD | May 20 2019 13:57:04:913 | /package.json | npm ERR! A complete log of this run can be found in: npm ERR!
BUILD | May 20 2019 13:57:04:913 | /package.json | /tmp/.npm/_logs/2019-05-20T08_57_04_909Z-debug.log
BUILD | May 20 2019 13:57:04:917 | /package.json | Error: Exited with 1     at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:28:24)     at emitTwo (events.js:126:13)     at ChildProcess.emit (events.js:214:7)     at maybeClose (internal/child_process.js:925:16)     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)


```
Here is the log.

**Comment by harout32** [comment]
any luck with this??

**Comment by Raja0sama** [comment]
@harout32 yes endup getting it working by a lengthy processs, i have a starter in my repo.
