### ISSUE TITLE
[now-dev] initial build error on `bash` example

### ISSUE THREAD

**Issue by amio** [vercel/vercel#2202]
To reproduce:

1. `now init bash`
2. `now dev bash --debug`

Error:

```
> Error! Command failed: /Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/bash/builder.sh index.sh
```
Full logs:

```
> [debug] [2019-04-22T02:10:20.589Z] Found config in file /Users/xilo/git/zeit/now-examples/now.json
> [debug] [2019-04-22T02:10:20.595Z] Using Now CLI 15.0.7-canary.2
> [debug] [2019-04-22T02:10:20.596Z] user supplied known subcommand
(node:97828) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [debug] [2019-04-22T02:10:20.657Z] The nsfw module is already cached, not re-downloading
> [debug] [2019-04-22T02:10:20.672Z] Reading `now.json` file
> [debug] [2019-04-22T02:10:22.686Z] Adding build match for "index.sh"
> Running initial builds
> [debug] [2019-04-22T02:10:22.687Z] Building index.sh with "@now/bash" v0.1.4 (workPath = /var/folders/r0/_2kzb3ld0bx996dpzqrxdc_w0000gp/T/co.zeit.now/dev/workPaths/dm6vqq15)
downloading files...
import: using '/usr/bin/shasum'
Caching imports in "index.sh"…
import: importing 'static-binaries@1.0.0'
import: normalized URL 'https://import.pw/static-binaries@1.0.0'
import: end of headers 'https://import.pw/static-binaries@1.0.0'
import: resolved location 'https://import.pw/static-binaries@1.0.0' -> 'https://import.pw/static-binaries@1.0.0'
import: calculated hash 'https://import.pw/static-binaries@1.0.0' -> 'a9aafe4fcee4a7168dbdf80592864593fdab5b8f'
import: creating symlink /var/folders/r0/_2kzb3ld0bx996dpzqrxdc_w0000gp/T/co.zeit.now/dev/workPaths/dm6vqq15/.import-cache/links/https://import.pw/static-binaries@1.0.0 -> ../../../data/a9aafe4fcee4a7168dbdf80592864593fdab5b8f
import: successfully imported 'https://import.pw/static-binaries@1.0.0' -> '/var/folders/r0/_2kzb3ld0bx996dpzqrxdc_w0000gp/T/co.zeit.now/dev/workPaths/dm6vqq15/.import-cache/data/a9aafe4fcee4a7168dbdf80592864593fdab5b8f'
/var/folders/r0/_2kzb3ld0bx996dpzqrxdc_w0000gp/T/co.zeit.now/dev/workPaths/dm6vqq15/.import-cache/links/https://import.pw/static-binaries@1.0.0: line 1: HTTP/2: No such file or directory
> Error! Command failed: /Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/bash/builder.sh index.sh
> [debug] [2019-04-22T02:10:30.083Z] Error: Command failed: /Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/bash/builder.sh index.sh
    at makeError (/Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Env:

```
Now     15.0.7-canary.2 (dev)
Node.js 10.15.3
MacOSX  10.14.4
```

**Comment by styfle** [comment]
I checked and it works in 15.0.7!

![image](https://user-images.githubusercontent.com/229881/56752514-6f14e700-6756-11e9-879e-08dd41f437a9.png)
