### ISSUE TITLE
[now-dev] initial build error on `go` example

### ISSUE THREAD

**Issue by amio** [vercel/vercel#2203]
### To reproduce

1. `now init go`
2. `now dev go --debug`

### Error

```
Failed to parse AST for "index.go"
> Error! spawn /Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/go/get-exported-function-name ENOENT
```

### Full logs

```
> [debug] [2019-04-22T02:29:22.720Z] Found config in file /Users/xilo/git/zeit/now-examples/go/now.json
> [debug] [2019-04-22T02:29:22.725Z] Using Now CLI 15.0.7-canary.2
> [debug] [2019-04-22T02:29:22.725Z] user supplied known subcommand
(node:98391) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [debug] [2019-04-22T02:29:22.781Z] The nsfw module is already cached, not re-downloading
> [debug] [2019-04-22T02:29:22.796Z] Reading `now.json` file
> [debug] [2019-04-22T02:29:24.940Z] Adding build match for "index.go"
> Running initial builds
> [debug] [2019-04-22T02:29:24.941Z] Building index.go with "@now/go" v0.3.0 (workPath = /var/folders/r0/_2kzb3ld0bx996dpzqrxdc_w0000gp/T/co.zeit.now/dev/workPaths/udt1ud5g)
Downloading user files...
Parsing AST for "index.go"
Failed to parse AST for "index.go"
> Error! spawn /Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/go/get-exported-function-name ENOENT
> [debug] [2019-04-22T02:29:24.959Z] Error: spawn /Users/xilo/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/go/get-exported-function-name ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Env

```
Now     15.0.7-canary.2 (dev)
Node.js 10.15.3
MacOSX  10.14.4
```

**Comment by amio** [comment]
This error occurs when user canceled while downloading go binary, which cause an incomplete runtime.

We may improve logs (let user know what we are doing, when to wait, be more patient), and speed up processes. But this is not a bug.

**Comment by markozxuu** [comment]
@amio Thanks : )
