### ISSUE TITLE
HTTP request failed: 404

### ISSUE THREAD

**Issue by Armaldio** [vercel/vercel#2282]
I'm unable to test my project with `now dev`, so I tried one of the examples.

```
λ now -v
15.0.11
λ now init express
λ cd express\
λ now dev -d                                                                                                                           
> [debug] [2019-04-30T20:12:14.018Z] Found config in file C:\Users\armal\Documents\Projets\ElectronForConstruct\test\express\now.json  
> [debug] [2019-04-30T20:12:14.028Z] Using Now CLI 15.0.11                                                                             
> [debug] [2019-04-30T20:12:14.031Z] user supplied known subcommand                                                                    
> Now CLI 15.0.11 dev (beta) — https://zeit.co/support                                                                                 
> [debug] [2019-04-30T20:12:14.166Z] The yarn executable is already cached, not re-downloading                                         
> [debug] [2019-04-30T20:12:14.171Z] The nsfw module is already cached, not re-downloading                                             
> [debug] [2019-04-30T20:12:14.187Z] Reading `now.json` file                                                                           
> [debug] [2019-04-30T20:12:14.230Z] Locating files C:\Users\armal\Documents\Projets\ElectronForConstruct\test\express                 
> [debug] [2019-04-30T20:12:14.241Z] Locating files C:\Users\armal\Documents\Projets\ElectronForConstruct\test\express: 5.481ms        
> [debug] [2019-04-30T20:12:22.576Z] Locating files C:\Users\armal\Documents\Projets\ElectronForConstruct\test\express                 
> [debug] [2019-04-30T20:12:22.578Z] Locating files C:\Users\armal\Documents\Projets\ElectronForConstruct\test\express: 0.088ms        
> [debug] [2019-04-30T20:12:22.854Z] Adding build match for "about\index.js"                                                           
> [debug] [2019-04-30T20:12:22.856Z] Adding build match for "index.js"                                                                 
> Setting up 2 Builders                                                                                                                
> Building @now/node:about\index.js                                                                                                    
> [debug] [2019-04-30T20:12:22.861Z] v0.6.0 (workPath = C:\Users\armal\AppData\Local\Temp\co.zeit.now\dev\workPaths\tmrcguug)          
> [debug] [2019-04-30T20:12:22.862Z] Creating build process for about\index.js                                                         
> Error! HTTP request failed: 404                                                                                                      
> [debug] [2019-04-30T20:12:24.523Z] Error: HTTP request failed: 404                                                                   
    at Object.<anonymous> (C:\snapshot\repo\dist\index.js:1:2552184)                                                                   
    at Generator.next (<anonymous>)                                                                                                    
    at fulfilled (C:\snapshot\repo\dist\index.js:1:2551375)                                                                            
    at process._tickCallback (internal/process/next_tick.js:68:7)                                                                      
```

Still unable to start and error is not quite helpfull

**Comment by dihmeetree** [comment]
@Armaldio Yep I get the same thing :) They are working on it! I get the following:

![error](https://i.imgur.com/e0ZREdW.png)

**Comment by adriangzz** [comment]
Dynamic links are also giving me 404 on my deployed website but not when I run npm run dev.

Is this the same issue?

**Comment by TooTallNate** [comment]
Hey all, can you give [`now@15.0.11-canary.2`](https://github.com/zeit/now-cli/releases/tag/15.0.11-canary.2) a try, which includes initial Windows support. Please open a new issue if you have any issues.

**Comment by sqal** [comment]
@TooTallNate Good job 👍 I confirm that 15.0.11-canary.2 resolved this issue on Windows and `dev` command works fine now
