### ISSUE TITLE
[now dev] getaddrinfo ENOTFOUND registry.yarnpkg.com

### ISSUE THREAD

**Issue by mini-eggs** [vercel/vercel#2287]
I suspect this is a DNS issue or a Yarn registry issue but I haven't been able to get anywhere with all my duckduckgo'ing. Help would be very much appreciated!

```bash
> npm --version
6.9.0
> node --version
v11.14.0
> now --version
15.0.11
> cat /proc/version
Linux version 5.0.9-arch1-1-ARCH (builduser@heftig-18307) (gcc version 8.3.0 (GCC)) #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019
```

Reproducing:

```bash
> now init rust
> Success! Initialized "rust" example in ~/Projects/spaces/rust. To develop, `cd rust` and run `now dev`. To deploy, `cd rust` and run `now`.
> now dev rust --debug
> [debug] [2019-05-01T00:31:02.604Z] Using Now CLI 15.0.11
> [debug] [2019-05-01T00:31:02.605Z] user supplied known subcommand
> Now CLI 15.0.11 dev (beta) — https://zeit.co/support
> [debug] [2019-05-01T00:31:02.636Z] Creating directory /home/evan/.cache/co.zeit.now/dev/builders
> [debug] [2019-05-01T00:31:02.636Z] Finished creating /home/evan/.cache/co.zeit.now/dev/builders
> [debug] [2019-05-01T00:31:02.636Z] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.15.2/yarn-1.15.2.js
> [debug] [2019-05-01T00:31:06.961Z] Finished downloading yarn /home/evan/.cache/co.zeit.now/dev/builders/yarn
> [debug] [2019-05-01T00:31:06.961Z] Making the yarn binary executable
> [debug] [2019-05-01T00:31:06.961Z] Finished making the yarn binary executable
> [debug] [2019-05-01T00:31:06.962Z] The nsfw module is already cached, not re-downloading
> [debug] [2019-05-01T00:31:06.962Z] Reading `now.json` file
> [debug] [2019-05-01T00:31:06.964Z] Locating files /home/evan/Projects/spaces/rust
> [debug] [2019-05-01T00:31:06.965Z] Locating files /home/evan/Projects/spaces/rust: 0.811ms
> Error! Command failed: /usr/lib/node_modules/now/download/dist/now /home/evan/.cache/co.zeit.now/dev/builders/yarn add --exact --no-lockfile @now/build-utils@0.4.41-canary.8 @now/rust
error An unexpected error occurred: "https://registry.yarnpkg.com/async-retry/-/async-retry-1.2.3.tgz: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".

yarn add v1.15.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/home/evan/.cache/co.zeit.now/dev/builders/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

> [debug] [2019-05-01T00:31:21.046Z] Error: Command failed: /usr/lib/node_modules/now/download/dist/now /home/evan/.cache/co.zeit.now/dev/builders/yarn add --exact --no-lockfile @now/build-utils@0.4.41-canary.8 @now/rust
error An unexpected error occurred: "https://registry.yarnpkg.com/async-retry/-/async-retry-1.2.3.tgz: getaddrinfo ENOTFOUND registry.yarnpkg.com registry.yarnpkg.com:443".

yarn add v1.15.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/home/evan/.cache/co.zeit.now/dev/builders/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at makeError (/snapshot/repo/dist/index.js:1:126558)
    at module.exports.548.e.exports.Promise.all.then.e (/snapshot/repo/dist/index.js:1:127628)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> 
```

I copy and pasted directly from my terminal. Above I `now init rust`'d but it doesn't matter what project I init -- happens with all.

I suspect an interesting part would be:

``` bash
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

Is there any options we have through the now CLI of what registry we can use? Seems like my networking options do not like registry.yarnpkg.com. No matter what my DNS nameservers are set to (I tried 8.8.8.8/8.8.4.4) I receive the same results.

Thanks for taking a peek in advance -- very excited about `now dev`.

**Comment by mini-eggs** [comment]
Revisiting this today... Fortunately/unfortunately I realized I made a silly mistake. I placed Goog DNS at the bottom of my /etc/resolv.conf. Moving towards the top fixed what I was experiencing.
