### ISSUE TITLE
Can't now dev on a fresh `nodejs-micro` project with port 3000 used

### ISSUE THREAD

**Issue by sarupbanskota** [vercel/vercel#2315]
```
now init nodejs-micro .
now dev

> Now CLI 15.1.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
> Success! Builder setup complete
> NOTE: Requested port 3000 is already in use
> Ready! Available at http://localhost:3001
> GET /
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/private/var/folders/r0/ppg8c9dx4lnfzd15406wr9rr0000gn/T/zeit-fun-82406800
```

**Comment by sarupbanskota** [comment]
Works well for `nodejs` 

```
now init nodejs .
now dev

> Now CLI 15.1.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
> Success! Builder setup complete
> NOTE: Requested port 3000 is already in use
> Ready! Available at http://localhost:3001
> GET /
```

**Comment by pajasevi** [comment]
This is actually a problem with `now-micro`. Issue reported [here](https://github.com/lucasconstantino/now-micro/issues/4)
