### ISSUE TITLE
Remove sign-in for now-dev

### ISSUE THREAD

**Issue by pex** [vercel/vercel#2324]
As pointed out in https://spectrum.chat/zeit/now/now-dev-without-credentials~1a755ccf-ec83-4c81-a5aa-7e79574c73a2?m=MTU1NzIyODYyMzkzNw== we should consider removing the authentication requirement for `now dev`.

Asking for ZEIT credentials when running locally is unexpected and might become a blocker when using `now dev` in continuous-integration environments.

**Comment by leo** [comment]
We'll definitely do this very soon. I'll let you know here when an update comes out!

**Comment by TooTallNate** [comment]
This was fixed in https://github.com/zeit/now-cli/pull/2325.

**Comment by mstruebing** [comment]
I have problems to run this in circleci.
I'm using the `circleci/node:10.15-browsers` image and run: `now dev` and I get this output:

```
#!/bin/bash -eo pipefail
yarn dev

yarn run v1.13.0
$ now dev
> Now CLI 15.2.1-canary.0 dev (beta) — https://zeit.co/feedback/dev
- Installing builders: @now/next, @now/node, @now/static
> Setting up 1 Builder
- Setting up Builder for package.json:
[@now/next] Downloading user files...
[@now/next] Installing dependencies...
installing to /home/circleci/app

> Error! Exited with 2
warning "@zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
warning "@zeit/next-css > mini-css-extract-plugin@0.4.3" has unmet peer dependency "webpack@^4.4.0".
warning " > react-apollo@2.5.5" has unmet peer dependency "apollo-client@^2.5.1".
warning " > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
warning " > babel-eslint@10.0.1" has unmet peer dependency "eslint@>= 4.12.1".
error /home/circleci/app/node_modules/now: Command failed.
Exit code: 2
Command: node download/install.js
Arguments: 
Directory: /home/circleci/app/node_modules/now
Output:
{ Error: ETXTBSY: text file is busy, open '/home/circleci/app/node_modules/now/download/dist/now'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at download (/home/circleci/app/node_modules/now/download/dist/index.js:6047:27)
    at main (/home/circleci/app/node_modules/now/download/dist/index.js:6147:9)
    at Module.337 (/home/circleci/app/node_modules/now/download/dist/index.js:6181:1)
    at __webpack_require__ (/home/circleci/app/node_modules/now/download/dist/index.js:22:30)
    at startup (/home/circleci/app/node_modules/now/download/dist/index.js:36:19)
    at /home/circleci/app/node_modules/now/download/dist/index.js:42:18
    at Object.<anonymous> (/home/circleci/app/node_modules/now/download/dist/index.js:45:10)
    at Module._compile (module.js:652:30)
  errno: -26,
  code: 'ETXTBSY',
  syscall: 'open',
  path: '/home/circleci/app/node_modules/now/download/dist/now' }

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

Does anyone have an idea what's wrong here or how to fix this?
