### ISSUE TITLE
[now dev] Cant use bcrypt on @next/node

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2353]
Running Now CLI 15.2.1-canary.0 dev (beta)

End up getting this error, regardless of rebuilds or reinstalls:

```
Error: The module '/private/var/folders/_5/_7x_3yqn6kx16bd9sbl2k32w0000gn/T/zeit-fun-5c352d6635888/api/src/lib/binding/bcrypt_lib.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.module.exports.toStr (/private/var/folders/_5/_7x_3yqn6kx16bd9sbl2k32w0000gn/T/zeit-fun-5c352d6635888/api/src/main.ts:316108:18)
    at __webpack_require__ (/private/var/folders/_5/_7x_3yqn6kx16bd9sbl2k32w0000gn/T/zeit-fun-5c352d6635888/api/src/main.ts:22:30)
    at Object.<anonymous> (/private/var/folders/_5/_7x_3yqn6kx16bd9sbl2k32w0000gn/T/zeit-fun-5c352d6635888/api/src/main.ts:64048:16)
    at __webpack_require__ (/private/var/folders/_5/_7x_3yqn6kx16bd9sbl2k32w0000gn/T/zeit-fun-5c352d6635888/api/src/main.ts:22:30)
```

**Comment by xdk78** [comment]
on `Now CLI 15.3.0 dev (beta)` same problem...

**Comment by wbunting** [comment]
I was able to get it to work by downgrading node to 8.11.3

**Comment by TooTallNate** [comment]
Closing because the `@now/node` builder now uses your system installed version of `node`, partially to fix this issue. So if you happened to run `npm install`/`yarn` _before_ starting up `now dev`, it will now work as expected.
