### ISSUE TITLE
sudo npm i -g now dont install

### ISSUE THREAD

**Issue by soheilpaper** [vercel/vercel#2355]
Hi 
i am going to install now in [www.codenvy.io](url) so i get this error:

` sudo npm install -g now`

i get this error:

```
user@f88314372cf0:/projects/trash$ sudo npm i -g now
![Screenshot from 2019-05-16 14-02-24](https://user-images.githubusercontent.com/6679151/57843359-60fd3800-77e3-11e9-91fc-d65ed7c28051.png)
![Screenshot from 2019-05-16 14-02-24](https://user-images.githubusercontent.com/6679151/57843363-62c6fb80-77e3-11e9-9a10-7b28eeca0336.png)


/usr/bin/now -> /usr/lib/node_modules/now/download/dist/now

> now@15.2.0 postinstall /usr/lib/node_modules/now
> node download/install.js

/usr/lib/node_modules/now/download/dist/index.js:6045
async function download() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/now/download/install.js:16:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! now@15.2.0 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the now@15.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-05-16T09_29_49_791Z-debug.log
```

![Screenshot from 2019-05-16 14-02-24](https://user-images.githubusercontent.com/6679151/57843362-62c6fb80-77e3-11e9-877e-2c419214828b.png)

**Comment by ctrlplusb** [comment]
What version of node are you using?

```
node --version
```

I believe async/await requires node 8+.

**Comment by leo** [comment]
We've resolved this problem. Please use `now@canary`.

The fix will soon be pushed to the stable channel.
