### ISSUE TITLE
Error using express with sequelize and tedious

### ISSUE THREAD

**Issue by facosta0787** [vercel/vercel#2367]
I'm traying to start my implementation using sequelize to connect to a Miscrosoft Sql Server u sing the tedious driver, I have used `now init express` to get an start point but im getting the next error when i run `now dev` or even I deploy doing `now`

```
> Built @now/node:index.js [10s]
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:95400:15)
    at new ConnectionManager (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:2679:21)
    at new MssqlDialect (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:38810:30)
    at new Sequelize (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:47472:20)
    at dbinstance (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:35282:10)
    at Object.<anonymous> (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:26691:36)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at Object.<anonymous> (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:88835:15)
    at __webpack_require__ (/webpack/bootstrap:19:1)
    at startup (/webpack/bootstrap:33:1)
    at /webpack/bootstrap:39:1
    at Object.<anonymous> (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/index.js:45:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/mj/qjnfzgmj45z129qpf4w111gc0000gp/T/zeit-fun-238d04678c5d4/launcher.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

this is my package.json
```
{
  "name": "nodejs-express",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "dotenv": "^8.0.0",
    "express": "^4.16.4",
    "helmet": "^3.16.0",
    "pg-hstore": "^2.3.2",
    "sequelize": "^5.8.6",
    "supports-color": "^6.1.0",
    "tedious": "^6.1.1"
  },
  "scripts": {
    "start": "node ."
  }
}
```

My CLI Version: 15.2.0
Repository: [https://github.com/facosta0787/zeit-express-sequelize-tedious](https://github.com/facosta0787/zeit-express-sequelize-tedious)

**Comment by facosta0787** [comment]
For aggregating, In the version 1 of the now.sh it works but in the version 2 doesn't work

**Comment by facosta0787** [comment]
I found a solution for this, I don't know why i have to do this in order to be able to use sequelize and tedious with a lamda function with zeit but here the solution.
You have to specify the `dialectModule` in the sequelize config
```
const Sequelize = require('sequelize')
const tedious = require('tedious')

module.exports = async (req, res) => {
  const type = Sequelize.QueryTypes.SELECT

  const conn = new Sequelize('yourSchema', 'yourUser', 'yourPassword', {
    host: 'your.hostname.com',
    dialect: 'mssql',
    dialectModule: tedious,
    port: 1433,
    query: { raw: false },
    logging: console.log,
    operatorAliases: Sequelize.Op
  })```

**Comment by kevinpainchaud** [comment]
@facosta0787 You saved my life, thank you very much! 🙏
