### ISSUE TITLE
NextJS `now dev` crashes / hangs when `build.env.NODE_ENV` is set to `production`

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2384]
NextJS `now dev` crashes / hangs when `build.env.NODE_ENV` is set to `production`.

```
"build": {
    "env": {
      "NODE_ENV": "production"
    }
  },
```

If `now dev --debug` is used:

```
Error: Cannot start server when target is not server. https://err.sh/zeit/next.js/next-start-serverless
    at new Server (/Users/williamli/projects/bbiHQ/ibcol/node_modules/next-server/dist/server/next-server.js:37:19)
    at new DevServer (/Users/williamli/projects/bbiHQ/ibcol/node_modules/next/dist/server/next-dev-server.js:28:9)
    at module.exports (/Users/williamli/projects/bbiHQ/ibcol/node_modules/next/dist/server/next.js:6:16)
    at main (/Users/williamli/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:18:17)
    at Object.<anonymous> (/Users/williamli/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/dev-server.js:39:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

It works fine when deployed to Now.

**Comment by wiiiimm** [comment]
might be a duplicate of https://github.com/zeit/next.js/issues/7439 and https://github.com/zeit/now-builders/issues/464

**Comment by lfades** [comment]
This issue should be fixed in the latest canary of `next`, feel free to reopen if the issue persists.
