### ISSUE TITLE
Invalid challenge response for xxxx. Make sure the DNS records are correct.

### ISSUE THREAD

**Issue by purplecones** [vercel/vercel#239]
I get the following error when trying to alias to a custom domain. 

```
> www.meteor-now.com is a custom domain.
> Verifying the DNS settings for www.meteor-now.com (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for www.meteor-now.com
> Error! Unknown error: Error: Invalid challenge response for www.meteor-now.com. Make sure the DNS records are correct.
    at Alias.<anonymous> (/Users/purplecones/.nvm/versions/node/v7.2.1/lib/node_modules/now/lib/index.js:564:15)
    at Generator.next (<anonymous>)
    at c (/Users/purplecones/.nvm/versions/node/v7.2.1/lib/node_modules/now/lib/index.js:702:99)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Here is my CloudFlare setup:
![dns__meteor-now_com___cloudflare_-_web_performance___security](https://cloud.githubusercontent.com/assets/136654/22231229/2ba68394-e1b0-11e6-8689-4b7ae9416ac2.png)

**Comment by jamo** [comment]
The www should be alias(or cname) to alias.zeit.co

**Comment by purplecones** [comment]
totally right, I mis-typed that. Thanks for catching it!
