### ISSUE TITLE
now cli throws error when running with npx in docker

### ISSUE THREAD

**Issue by ChristophP** [vercel/vercel#2425]
Running now with npx in a node image thows an error when installing. This is a bit annoying when using `now` in CI.
Minimal reproducible example:
```sh
docker run node:10 npx now --help
```
Throws 
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/1/lib/node_modules/now/download/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! now@15.4.0 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the now@15.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-11T19_29_10_702Z-debug.log
Install for now@latest failed with code 1
```
Our current workaround is to install first with npm and then call `now`.

Two more interesting points
1) It only seems to error when there is no previous global or local install for `now`
2) I was not able to reproduce that error outside of docker on my ubuntu after removing the installations of now both globally and locally.

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!

**Comment by ChristophP** [comment]
cool, thanks
