### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by netspencer** [vercel/vercel#2457]
I'm getting an error when attempting to run now dev.

```
> Now CLI 15.6.0-canary.3 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
> Success! Builder setup complete
> NOTE: Requested port 3000 is already in use
> Ready! Available at http://localhost:3001
> GET /donate
TypeError: Cannot read property 'replace' of undefined
    at Object.default_1 [as default] (/snapshot/repo/dist/index.js:1:1370145)
    at DevServer.serveProjectAsNowV2 (/snapshot/repo/dist/index.js:1:1124117)
> GET /favicon.ico
TypeError: Cannot read property 'replace' of undefined
    at Object.default_1 [as default] (/snapshot/repo/dist/index.js:1:1370145)
    at DevServer.serveProjectAsNowV2 (/snapshot/repo/dist/index.js:1:1124117)
```

**Comment by netspencer** [comment]
oooh. this was a brain fart on my part. my now.json was invalid. this error should be handled better tho
