### ISSUE TITLE
node 10.x + firebase-admin crashes now dev

### ISSUE THREAD

**Issue by ywg-jean** [vercel/vercel#2460]
steps to reproduce : 
```bash
git clone git@github.com:zeit/now-examples.git
cd now-examples
cd nodejs
yarn add firebase-admin@7.4.0
yarn install --force # forces a rebuild of the binary packages
```
update `api/date.js` contents to 
```javascript
const firebase=require('firebase-admin')
const moment = require('moment')

const secret = {
  project_id: process.env.FIREBASE_PROJECT_ID,
  client_email: process.env.FIREBASE_CLIENT_EMAIL,
  private_key: process.env.FIREBASE_PRIVATE_KEY
};

firebase.initializeApp({
  credential: firebase.credential.cert(secret),
  databaseURL: process.env.FIREBASE_DB_URL
});
const firestore = firebase.firestore();
module.exports = async(req, res) => {
  const currentTime = moment().format('MMMM Do YYYY, h:mm:ss a')
  await firestore.listCollections().then(collections=>
    collections.forEach(collection=>console.log(collection.id, collection.path)));
  res.end(currentTime)
}
```
update package.json to target node 10.x: 
```json
"engines": {
    "node": "10.x"
},
```
run 
* `now dev`
* `curl http://localhost:3000/api/date.js`

results in a first crash  where it looks like it's `@now/node` or `ncc` which is crashing.
```
now dev
> Now CLI 15.6.0-canary.3 dev (beta) — https://zeit.co/feedback/dev
> NOTE: Requested port 3000 is already in use
> Ready! Available at http://localhost:3001
> GET /api/date.js
> Building @now/node:api/date.js
downloading user files...
installing dependencies for user's code...
found `engines` in `package.json`, selecting range: 10.x
installing to /Users/jean/dev/debug/src/now-examples/nodejs/api
yarn install v1.15.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "firebase-admin > @firebase/database@0.3.20" has unmet peer dependency "@firebase/app-types@0.x".
warning "firebase-admin > @firebase/database > @firebase/database-types@0.3.11" has unmet peer dependency "@firebase/app-types@0.x".
[4/4] Building fresh packages...
Done in 3.96s.
running user script...
compiling entrypoint with ncc...
ncc: Version 0.18.5
ncc: Compiling file index.js
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/retry-request/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/node-fetch/lib" attempted to require "encoding" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/dev/debug/src/now-examples/nodejs/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at pkg/prelude/bootstrap.js:757:23
    at pkg/prelude/bootstrap.js:337:5
    at pkg/prelude/bootstrap.js:315:14
    at u (/Users/jean/Library/Caches/co.zeit.now/dev/builders/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:1:109048)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
```

running both commands again : 
* `now dev`
* `curl http://localhost:3000/api/date.js`

results in 
```
now dev
> Now CLI 15.6.0-canary.3 dev (beta) — https://zeit.co/feedback/dev
> NOTE: Requested port 3000 is already in use
> Ready! Available at http://localhost:3001
> GET /api/date.js
> Building @now/node:api/date.js
downloading user files...
installing dependencies for user's code...
found `engines` in `package.json`, selecting range: 10.x
installing to /Users/jean/debug/yupwego/src/now-examples/nodejs/api
yarn install v1.15.2
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.22s.
running user script...
compiling entrypoint with ncc...
ncc: Version 0.18.5
ncc: Compiling file index.js
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/retry-request/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/node-fetch/lib" attempted to require "encoding" but could not be resolved, assuming external.
ncc: Module directory "/Users/jean/debug/yupwego/src/now-examples/nodejs/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
> Built @now/node:api/date.js [8s]
Unhandled rejection: Error: Failed to load /private/var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/zeit-fun-3f7e68353f5dc/api//src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node. The module '/private/var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/zeit-fun-3f7e68353f5dc/api/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/private/var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/zeit-fun-3f7e68353f5dc/api/date.js:160182:18)
    at __webpack_require__ (/private/var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/zeit-fun-3f7e68353f5dc/api/date.js:22:30)
    at Object.<anonymous> (/private/var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/zeit-fun-3f7e68353f5dc/api/date.js:98247:13)
    at __webpack_require__ (/private/var/folders/gt/c0_8ryzj2m7fwmf07t68z0940000gn/T/zeit-fun-3f7e68353f5dc/api/date.js:22:30)
LambdaError: RequestId: 829914c8-c65b-4174-834b-ee63c1cbed49 Process exited before completing request
    at Lambda.<anonymous> (/snapshot/repo/dist/index.js:1:2533551)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/repo/dist/index.js:1:2531692)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
This time it looks like it's now-cli's dev lambda container which crashed.

Trying to run directly from a node 10 script : 
```bash
yarn add dotenv
```
create api/test.js
```javascript
const firebase = require('firebase-admin')
const dotenv = require('dotenv')
dotenv.config();
const secret = {
  project_id: process.env.FIREBASE_PROJECT_ID,
  client_email: process.env.FIREBASE_CLIENT_EMAIL,
  private_key: process.env.FIREBASE_PRIVATE_KEY
};

firebase.initializeApp({
  credential: firebase.credential.cert(secret),
  databaseURL: process.env.FIREBASE_DB_URL
});
const firestore = firebase.firestore();

const timer = setTimeout(() => {}, 10000);
firestore.listCollections().then(collections=>{
    collections.forEach(collection=>console.log(collection.id, collection.path));
    clearTimeout(timer);
});
```
run with node 10.x
```
$ node --version
v10.16.0
$ node api/test.js
```
doesn't crash.

**Comment by ywg-jean** [comment]
I have tried various combinations with `now`, `now@canary` and `@now/node, `@now/node@canary`, they all crash. 

I couldn't try upgrading firebase admin to 8.x since it is blocked by https://github.com/zeit/ncc/issues/412 which depends on https://github.com/zeit/now-builders/pull/641 which is blocked by https://github.com/zeit/ncc/issues/434

**Comment by thomaslindstrom** [comment]
Same issue here.

**Comment by ywg-jean** [comment]
Since  zeit/ncc#412  and zeit/now-builders#641  have been resolved, I solved this by upgrading to node 10 and firebase 8.
