### ISSUE TITLE
now deploy fails with devDeps

### ISSUE THREAD

**Issue by remy** [vercel/vercel#2466]
I'm deploying a new project to node v2 - when I run `now` on this repo https://github.com/remy/jsonbin/commit/b88273ebb45de0bb4423a716e745c3d9c6e7794a - it fails to build: https://zeit.co/rem/jsonbin/5tjgs6wr1/logs?name=bld_lcpsyh73z

```
npm ERR! path /tmp/7b720260/node_modules/nyc/node_modules/amdefine
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/7b720260/node_modules/nyc/node_modules/amdefine' -> '/tmp/7b720260/node_modules/nyc/node_modules/.amdefine.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/.npm/_logs/2019-06-26T15_47_04_527Z-debug.logError: Exited with 254
    at ChildProcess.child.on (/tmp/184f3efb/.build-utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:30:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

I've no idea what this is referencing, but when I try to redeploy using `now -b NODE_ENV=production` it builds just fine.

**Comment by varna** [comment]
Maybe you load some packages differently? i.e.

```js
let amdefine = require('smth')
if (process.env.NODE_ENV === "production") {
   amdefine = require('amdefine')
}
```

**Comment by TooTallNate** [comment]
@remy I can't seem to reproduce this. It was most likely fixed when the `@now/node` builder switched from `ncc` to `node-file-trace`.

Here's an example deployment: https://jsonbin.now-examples.now.sh/
