### ISSUE TITLE
Now dev 15.6.2 doesn't work- Jaascript 

### ISSUE THREAD

**Issue by maitham** [vercel/vercel#2483]
Currently running 15.6.2 get the following error:

```
Security context: 0xa1c9e5a57c1 <JSObject>
    1: toJSON [buffer.js:~938] [pc=0x16b227b13c52](this=0xa1c84302fe9 <Uint8Array map = 0xa1cda0369c9>)
    2: arguments adaptor frame: 1->0
    5: builtin exit frame: stringify(this=0xa1c9e588ff1 <Object map = 0xa1cda002ba1>,0xa1c8af022d1 <undefined>,0xa1c8af022d1 <undefined>,0xa1cd2a82411 <Object map = 0xa1c897b6291>)

    6: arguments adaptor frame: 1->3
    7: _send [internal/child_process.js...

FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 4: v8::internal::HashTable<v8::internal::SeededNumberDictionary, v8::internal::SeededNumberDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::SeededNumberDictionary>, int, v8::internal::PretenureFlag) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 5: v8::internal::Dictionary<v8::internal::SeededNumberDictionary, v8::internal::SeededNumberDictionaryShape>::Add(v8::internal::Handle<v8::internal::SeededNumberDictionary>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, int*) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 6: v8::internal::(anonymous namespace)::DictionaryElementsAccessor::AddImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 7: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 8: v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
 9: v8::internal::Runtime_KeyedStoreIC_Slow(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/maitham.dib/Library/Caches/co.zeit.fun/runtimes/nodejs8.10/bin/node]
10: 0x16b2279042fd
11: 0x16b227b13c52
12: 0x16b22790535f
13: 0x16b227904239
Error: Builder exited with SIGABRT before sending build result
    at ChildProcess.onExit (/snapshot/repo/dist/index.js:1:2715210)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
Error: Builder exited with SIGABRT before sending build result
    at ChildProcess.onExit (/snapshot/repo/dist/index.js:1:2715210)
    at ChildProcess.emit (events.js:187:15)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by markozxuu** [comment]
Hi 👋 , I need more details for understand the error. A repository would be useful 🙏

**Comment by leo** [comment]
No reply. Closing.
