### ISSUE TITLE
5 minute Lambda?

### ISSUE THREAD

**Issue by 59023g** [vercel/vercel#2491]
Version 2. Unlimited account.

Increased `curl --timeout 300 "http://<url>"` to prevent socket hang up. To no avail. On both `now` and `now dev`.

```
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by 59023g** [comment]
Closing this. I converted my function to AWS Lambda. Can set the timeout manually. Up to 15 minutes. Will still use `now` for shorter, non-background tasks.
