### ISSUE TITLE
now cli update throwing EBUSY error

### ISSUE THREAD

**Issue by dillonburns** [vercel/vercel#2492]
```
$ now update
> UPDATE AVAILABLE The latest version of Now CLI is 15.6.2
> Run the `now update` command to update to the latest version
> Changelog: https://github.com/zeit/now-cli/releases/tag/15.6.2
> Now CLI 15.5.0 update (beta) — https://zeit.co/feedback/update
> Updating Now CLI...

  Configuration

    platform    win
    arch        x64
    location    C:\Users\reach\AppData\Roaming\npm\node_modules\now\download\dist\now.exe
    version     15.6.2 (latest stable release)

> Downloading `now` binary...
> Binary URL: https://github.com/zeit/now-cli/releases/download/15.6.2/now-win.exe.gz
> Update Now CLI? [y/N] y
> Error! An unexpected error occurred in update: Error: EBUSY: resource busy or locked, open 'C:\Users\reach\AppData\Roaming\npm\node_modules\now\download\dist\now.exe'
    at WriteStream.t.error.t (C:\snapshot\repo\dist\index.js:1:1589155)
    at WriteStream.emit (events.js:187:15)
    at WriteStream.EventEmitter.emit (domain.js:442:20)
    at C:\snapshot\repo\dist\index.js:1:2874894
    at C:\snapshot\repo\dist\index.js:1:2875329
    at FSReqWrap.oncomplete (fs.js:171:20)
```

**Comment by dillonburns** [comment]
I've tried running as admin, disabling windows anti-virus, and running `npm cache clear` but the error persists. This is on a Windows 10 system

**Comment by TJkrusinski** [comment]
Getting this as well, same configuration.

**Comment by TooTallNate** [comment]
Hey guys, sorry for the misleading error message. It turns out that the `now update` command is not supported on Windows.

To get the latest version, please re-install Now CLI from https://zeit.co/download

I've also [created a PR](https://github.com/zeit/now-cli/pull/2493) to have now-cli inform you of this before it reaches this error.

**Comment by dillonburns** [comment]
thanks @TooTallNate
