### ISSUE TITLE
SyntaxError : Unexpected token {

### ISSUE THREAD

**Issue by LucaAndrei** [vercel/vercel#252]
Hi,

I have just installed now and meteor-now using the followind command : 
`sudo npm install -g now meteor-now`

Whenever I try to run any 'now' command from the terminal I get the following error : 
```
/usr/local/lib/node_modules/now/bin/now.js:4
const {resolve} = require('path')
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:124:16)
    at node.js:811:3```

I'm mentioning that I am running on Ubuntu 14.04

Also, if anyone wants to know, I get an error whenever I try to run meteor-now.

/usr/local/lib/node_modules/meteor-now/node_modules/ora/index.js:2
const chalk = require('chalk');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-now/dist/app.js:529:19)
    at __webpack_require__ (/usr/local/lib/node_modules/meteor-now/dist/app.js:20:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-now/dist/app.js:433:13)

**Comment by LucaAndrei** [comment]
I am sorry for this bug. It can be closed.
It seems that the problem was from my NodeJS version

Leaving this issue here for further guidance if anyone will run into the same issue.

Thank you,
Andrei

**Comment by PolGuixe** [comment]
@LucaAndrei which version were you using? I have the same problem.

**Comment by LucaAndrei** [comment]
@PolGuixe I am sorry, but I cannot remember exactly.
I think it was something like ... 0.13.X ?
I cannot recall
I upgraded node to 6.9.4 and I was able to use all the commands and deploy properly
