### ISSUE TITLE
Deploy failure with ESM

### ISSUE THREAD

**Issue by ericelliott** [vercel/vercel#2569]
**Impact**: This completely breaks `now.sh` for me. I won't be able to deploy new builds until we get this fixed.

**Update:** I am no longer depending on the module mentioned below, but am still getting errors about esm. Apparently, something else is also depending on esm.

~~I just created [a new npm module](https://github.com/ericelliott/gql-validate) that uses esm~~, and then tried to deploy a project that uses the module. However, the deployment is failing with the following error output:

> ./node_modules/gql-validate/node_modules/esm/esm.js Critical dependency: require function is used in a way in which dependencies cannot be statically extracted  ./node_modules/gql-validate/node_modules/esm/esm.js Module not found: Can't resolve 'internal/bootstrap/loaders' in '/tmp/634390ac/node_modules/gql-validate/node_modules/esm'
--
Jul 17 2019 11:43:47:701 | ...package.json | > Build error occurred
Jul 17 2019 11:43:47:703 | ...package.json | { TypeError: Cannot destructure property `dir` of 'undefined' or 'null'.     at Object.<anonymous> (/tmp/634390ac/.next/serverless/pages/register.js:9022:1704)     at Object.eqrp (/tmp/634390ac/.next/serverless/pages/register.js:9023:30)     at __webpack_require__ (/tmp/634390ac/.next/serverless/pages/register.js:23:31)     at Object.<anonymous> (/tmp/634390ac/.next/serverless/pages/register.js:9011:11)     at Object.epOS (/tmp/634390ac/.next/serverless/pages/register.js:9015:30)     at __webpack_require__ (/tmp/634390ac/.next/serverless/pages/register.js:23:31)     at Module.edYE (/tmp/634390ac/.next/serverless/pages/register.js:8825:20)     at __webpack_require__ (/tmp/634390ac/.next/serverless/pages/register.js:23:31)     at /tmp/634390ac/.next/serverless/pages/register.js:91:18     at Object.<anonymous> (/tmp/634390ac/.next/serverless/pages/register.js:94:10) type: 'TypeError', '$error': '$error' }

See [this issue in standard-things/esm](https://github.com/standard-things/esm/issues/831).

**Comment by ericelliott** [comment]
@jdalton (esm author) took a look at the error. He seems convinced that a bundle script is ignoring the `package.json` `"module"` field:

> If you can find out why a bundle script is ignoring module then I think you'll resolve the issue but that's a bit beyond esm. Keep digging and report back.

**Comment by ericelliott** [comment]
All of my now deploys are failing now with an error like this:

```
2019-07-23T23:52:55.635Z  Creating an optimized production build ...
2019-07-23T23:52:55.637Z  
2019-07-23T23:52:56.026Z  > Using external babel configuration
2019-07-23T23:52:56.026Z  > Location: "/tmp/36a95be8/.babelrc"
2019-07-23T23:53:14.113Z  Compiled with warnings.
2019-07-23T23:53:14.113Z  
2019-07-23T23:53:14.114Z  ./node_modules/esm/esm.js
2019-07-23T23:53:14.114Z  Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
2019-07-23T23:53:14.114Z  
2019-07-23T23:53:14.114Z  ./node_modules/esm/esm.js
2019-07-23T23:53:14.114Z  Module not found: Can't resolve 'internal/bootstrap/loaders' in '/tmp/36a95be8/node_modules/esm'
2019-07-23T23:53:14.114Z  
2019-07-23T23:53:14.202Z  > Build error occurred
2019-07-23T23:53:14.204Z  TypeError: Cannot destructure property `dir` of 'undefined' or 'null'.
2019-07-23T23:53:14.204Z      at Object.<anonymous> (/tmp/36a95be8/.next/serverless/pages/index.js:4819:1781)
2019-07-23T23:53:14.204Z      at Object.JC+t (/tmp/36a95be8/.next/serverless/pages/index.js:4820:30)
2019-07-23T23:53:14.204Z      at __webpack_require__ (/tmp/36a95be8/.next/serverless/pages/index.js:23:31)
2019-07-23T23:53:14.204Z      at Object.<anonymous> (/tmp/36a95be8/.next/serverless/pages/index.js:4796:11)
2019-07-23T23:53:14.204Z      at Object.Ici4 (/tmp/36a95be8/.next/serverless/pages/index.js:4800:30)
2019-07-23T23:53:14.204Z      at __webpack_require__ (/tmp/36a95be8/.next/serverless/pages/index.js:23:31)
2019-07-23T23:53:14.204Z      at Object.q27P (/tmp/36a95be8/.next/serverless/pages/index.js:14590:65)
2019-07-23T23:53:14.204Z      at __webpack_require__ (/tmp/36a95be8/.next/serverless/pages/index.js:23:31)
2019-07-23T23:53:14.204Z      at Object.1TCz (/tmp/36a95be8/.next/serverless/pages/index.js:1015:24)
2019-07-23T23:53:14.204Z      at __webpack_require__ (/tmp/36a95be8/.next/serverless/pages/index.js:23:31)
2019-07-23T23:53:14.216Z  npm
2019-07-23T23:53:14.216Z   ERR! code ELIFECYCLE
2019-07-23T23:53:14.216Z  npm
2019-07-23T23:53:14.217Z   ERR! errno
2019-07-23T23:53:14.217Z   1
2019-07-23T23:53:14.218Z  npm
2019-07-23T23:53:14.218Z   ERR! @ now-build: `next build`
2019-07-23T23:53:14.218Z  npm 
2019-07-23T23:53:14.218Z  ERR! Exit status 1
2019-07-23T23:53:14.218Z  npm ERR! 
2019-07-23T23:53:14.218Z  npm ERR! Failed at the @ now-build script.
2019-07-23T23:53:14.218Z  npm 
2019-07-23T23:53:14.218Z  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-23T23:53:14.230Z  
2019-07-23T23:53:14.230Z  npm ERR! A complete log of this run can be found in:
2019-07-23T23:53:14.230Z  npm ERR!     /tmp/.npm/_logs/2019-07-23T23_53_14_219Z-debug.log
2019-07-23T23:53:14.234Z  Error: Exited with 1
2019-07-23T23:53:14.234Z      at ChildProcess.child.on (/tmp/58eefe6453c9eb32/.build-utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:30:24)
2019-07-23T23:53:14.234Z      at emitTwo (events.js:126:13)
2019-07-23T23:53:14.234Z      at ChildProcess.emit (events.js:214:7)
2019-07-23T23:53:14.234Z      at maybeClose (internal/child_process.js:925:16)
2019-07-23T23:53:14.234Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

That's the output from a recent deploy: `now logs tdd-day-d2gepinax.now.sh`

In case it's useful, here's the `.babelrc`:

```
$ cat .babelrc
{
  "env": {
    "development": {
      "presets": ["next/babel"],
    },
    "production": {
      "presets": ["next/babel"],
    },
    "test": {
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" }}]],
    }
  }
}
```

Another hint? Works in `now dev`:

```
> Now CLI 15.8.5 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
> Success! Build completed
> Ready! Available at http://localhost:3000
[ ready ] compiled successfully
```

Local runs of `next build` fail:

```
> next build

Creating an optimized production build ...

> Using external babel configuration
> Location: "/Users/eric/Dropbox/dev/tddday/.babelrc"
Compiled with warnings.

./node_modules/esm/esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/esm/esm.js
Module not found: Can't resolve 'internal/bootstrap/loaders' in '/Users/eric/Dropbox/dev/tddday/node_modules/esm'

> Build error occurred
TypeError: Cannot destructure property `dir` of 'undefined' or 'null'.
...
```

**Comment by TooTallNate** [comment]
Hey @ericelliott, thanks for the report. I've been told that we are working on a fix for this now. Will have an update for you soon!

**Comment by ericelliott** [comment]
Cool @TooTallNate -- I tracked down the other dependency breaking my build. It's another module I authored that also uses esm. As you can see, if the bundler knows how to handle ES6 modules without esm, it should be able to use [the module field from package.json](https://github.com/ericelliott/autodux/blob/master/package.json#L6).

**Comment by Timer** [comment]
Hey @ericelliott! 

We've tracked down what's causing this and have opened two PRs with potential fixes:
1. https://github.com/zeit/next.js/pull/8081
    * remain favoring `main` in `package.json`
    * transparently remove the usage of `esm` via source transforms (it's not needed in webpack)
1. https://github.com/zeit/next.js/pull/8082
    * favor `module` in `package.json`
    * maintain a list of improperly published packages and their fixes

`esm` doesn't play friendly with `webpack`, thus the error you're experiencing.

Unfortunately, it's not as simple as preferring the `module` key over the `main` key, as this breaks an unknown number of npm packages.

A notable example is `node-fetch` (~10 million weekly downloads), along with other packages listed in this webpack issue: https://github.com/webpack/webpack/issues/4742

We'll hopefully have one of these two solutions merged sometime soon. In the meantime, you can use one of them via a custom `next.config.js` or `.babelrc`!

**Comment by ericelliott** [comment]
I'd like to hear what @jdalton thinks of these proposals.

I like the idea of using the option that is least breaking. 4 years on from ES2015 all I want for Christmas is a module system that just works.

**Comment by ericelliott** [comment]
> We'll hopefully have one of these two solutions merged sometime soon. In the meantime, you can use one of them via a custom next.config.js or .babelrc!

How do I fix this in `next.config.js` or `.babelrc`?

**Comment by Timer** [comment]
Implementing the proposal in https://github.com/zeit/next.js/pull/8082 can be done with a `next.config.js` like so:
```js
module.exports = {
  webpack(config, { isServer }) {
    if (isServer) {
      config.resolve.mainFields = ['module', 'main']

      // Fix all packages that this change breaks:
      config.resolve.alias['node-fetch'] = 'node-fetch/lib/index.js'
    }
    return config
  },
}
```

I've omitted the Babel variant because it's trickier to pull off.
However, the Babel option is the less-breaking than the above example. 

Hopefully it works in your application!
If it's still broken, try to track down the list of modules it breaks and patch them via `alias` one-by-one.

**Comment by ericelliott** [comment]
Worked for me.

**Comment by leo** [comment]
It seems like the issue was resolved! Please let me know if any other problems occur, then we can re-open it immediately.

**Comment by ericelliott** [comment]
> It seems like the issue was resolved! Please let me know if any other problems occur, then we can re-open it immediately.

Did one of those permanent fixes get merged?

**Comment by Timer** [comment]
Not yet, @ericelliott -- however, let's move this issue to the Next.js repository.

I've filed a follow-up issue here: https://github.com/zeit/next.js/issues/8113
