### ISSUE TITLE
Fails with Error: ENOENT: no such file or directory, open '/home/nowuser/src/server/ssl/production/server.key'

### ISSUE THREAD

**Issue by gauravdhiman** [vercel/vercel#2592]
I am trying to deploy my app using Now v1 but my app fails with below error. Error is related to production SSL cert. From error, it looks like Now issue than an app issue.

```sh
npm start
> trackitt-pwa@0.0.1 start /home/nowuser/src
> node server/
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/home/nowuser/src/server/ssl/production/server.key'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/home/nowuser/src/server/app.js:63:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nowuser/src/server/index.js:3:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! trackitt-pwa@0.0.1 start: `node server/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the trackitt-pwa@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nowuser/.npm/_logs/2019-07-21T23_56_12_162Z-debug.log
More details: https://err.sh/now-cli/no-open-port-found
signal: 9
```

**Comment by gauravdhiman** [comment]
Above error comes when I have below code in `now.json`
```js
"env": {
  "NODE_ENV": "production"
}
```

If I remove above, the build happends successfully but whn I hit an app in browser it does not load and finally timesout. I see `Page was removed /` in below logs.
Deployment URL: https://my-app-hlsiwijcui.now.sh/

```
> Building page: /
Jul 23 2019 00:42:07:203 WAIT  Compiling...07:42:07
Jul 23 2019 00:42:07:208[07:42:07] Compiling server
Jul 23 2019 00:42:07:209Page was removed /
Jul 23 2019 00:42:07:227[07:42:07] Compiling client
Jul 23 2019 00:42:07:488[07:42:07] Compiled server in 128ms
Jul 23 2019 00:42:07:966[07:42:07] Compiled client in 535ms
Jul 23 2019 00:42:07:966 DONE  Compiled successfully in 597ms07:42:07
Jul 23 2019 00:44:07:147> Building page: /
Jul 23 2019 00:44:07:148 WAIT  Compiling...07:44:07
Jul 23 2019 00:44:07:202[07:44:07] Compiling server
Jul 23 2019 00:44:07:203Page was removed /
Jul 23 2019 00:44:07:400[07:44:07] Compiling client
Jul 23 2019 00:44:07:401[07:44:07] Compiled server in 159ms
Jul 23 2019 00:44:08:167[07:44:07] Compiled client in 715ms
Jul 23 2019 00:44:08:168 DONE  Compiled successfully in 792ms07:44:07
```

**Comment by paulogdm** [comment]
Hello,

We have announced the deprecation of our Now 1.0 platform. Therefore, I am closing this issue.
My apologies in the name of the team for missing your message here. If you do have any further issues, feel free to email support@zeit.co
