### ISSUE TITLE
Failed to compile on now. Doesn't resolve 'next/head' on `now dev`

### ISSUE THREAD

**Issue by mkrn** [vercel/vercel#2665]
Now CLI 15.8.5 dev (beta) — https://zeit.co/feedback/dev
Mac OS 
yarn -v
1.7.0
npm -v
6.4.1
node -v
v10.7.0

package.json 
```
{
  "name": "eventlive-domain",
  "version": "1.0.0",
  "scripts": {
    "build": "next build",
    "dev": "next",
    "now-build": "next build"
  },
  "dependencies": {
    "aws-amplify": "^1.1.30",
    "aws-sdk": "^2.494.0",
    "date-fns": "^1.29.0",
    "express": "^4.16.4",
    "graphql-tag": "^2.10.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "next": "^9.0.2",
    "react": "^16.8.6",
    "react-apollo": "^2.3.1",
    "react-dom": "^16.8.6",
    "reactstrap": "^6.5.0",
    "serve-favicon": "^2.5.0",
    "video.js": "^7.3.0",
    "videojs-dvrseekbar": "0.0.1"
  },
  "devDependencies": {
    "css-loader": "^1.0.1"
  },
  "resolutions": {
    "@aws-amplify/ui": "1.0.19"
  }
}
```

now.json 
```
{
  "version": 2,
  "alias": "live.eventlive.pro",
  "builds": [
    { "src": "package.json", "use": "@now/next" }
  ],
  "routes": [
    { "src": "^/favicon.ico", "dest": "/static/favicon.ico", "headers": { "Cache-Control": "public, max-age=31557600" } },
    { "src": "^/robots.txt", "dest": "/static/robots.txt", "headers": { "Cache-Control": "public, max-age=31557600" }  },
    { "src": "/u/(?<broadcaster>[^/]+)$", "dest": "/?broadcaster=$broadcaster", "headers": { "Cache-Control": "max-age=60, s-maxage=86400" }  },
    { "src": "/u/(?<broadcaster>[^/]+)/(?<slug>[^/]+)$", "dest": "/video?slug=$slug&broadcaster=$broadcaster", "headers": { "Cache-Control": "max-age=60, s-maxage=86400" }  }
  ]
}
```

.nowignore
```
README.md
.next
node_modules
```

next.config.js
```

module.exports = {
  target: 'serverless'
};
```

When trying to deploy to now getting this error during build:

```

> next build
--
Jul 30 2019 12:26:15:209 | ...package.json | Creating an optimized production build ...
Jul 30 2019 12:26:54:180 | ...package.json | Failed to compile.
Jul 30 2019 12:26:54:180 | ...package.json | ./node_modules/next/dist/build/webpack/loaders/next-serverless-loader.js?page=%2F&absolutePagePath=private-next-pages%2Findex.js&absoluteAppPath=next%2Fdist%2Fpages%2F_app&absoluteDocumentPath=private-next-pages%2F_document.js&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&distDir=private-dot-next&assetPrefix=&generateEtags=true&ampBindInitData=false&canonicalBase=&dynamicBuildId=false
Jul 30 2019 12:26:54:180 | ...package.json | Module not found: Can't resolve 'next-server/dist/server/render' in '/tmp/264f8dd6'
Jul 30 2019 12:26:54:180 | ...package.json | > Build error occurred
Jul 30 2019 12:26:54:181 | ...package.json | Error: > webpack config.resolve.alias was incorrectly overriden. https://err.sh/zeit/next.js/invalid-resolve-alias
```

Also, during `now dev` I get

```
Module not found: Can't resolve 'next/head' in '/Users/mkrn/Sites/eventlive-domain/pages'
```

Very puzzled, since these errors do not appear in Google search results 
Any hints appreciated

**Comment by mkrn** [comment]
I was able to make it deploy by deleting `package-lock.json`, I still get `next/head` issue in now dev

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'next/head' in '/Users/mkrn/Sites/eventlive-domain/pages'
    at factory.create (/Users/mkrn/Sites/eventlive-domain/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/Users/mkrn/Sites/eventlive-domain/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/Users/mkrn/Sites/eventlive-domain/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/mkrn/Sites/eventlive-domain/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/mkrn/Sites/eventlive-domain/node_modules/neo-async/async.js:2830:7
    at /Users/mkrn/Sites/eventlive-domain/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/mkrn/Sites/eventlive-domain/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/mkrn/Sites/eventlive-domain/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/mkrn/Sites/eventlive-domain/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mkrn/Sites/eventlive-domain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/mkrn/Sites/eventlive-domain/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/mkrn/Sites/eventlive-domain/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mkrn/Sites/eventlive-domain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/mkrn/Sites/eventlive-domain/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mkrn/Sites/eventlive-domain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/mkrn/Sites/eventlive-domain/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
```

Any ideas?

**Comment by mkrn** [comment]
The issue went away removing yarn.lock and building again. FYI Sorry about the noise.

**Comment by jiangbo2015** [comment]
+1
