### ISSUE TITLE
`now dev` gives Unknown Readlink error when running Lamdas

### ISSUE THREAD

**Issue by Bartvelp** [vercel/vercel#2670]
When running any node lamda `now dev` suddenly always spits out this error:
```
> GET /api/user/details.js
> Building @now/node:api/user/details.js
downloading user files...
download complete [1ms]
installing dependencies for user's code...
missing `engines` in `package.json`, using default range: 8.10.x
installing to C:\Users\user\Documents\werk\node\now\tracker\api\user
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 29506 packages in 9.36s
found 0 vulnerabilities

install complete [10518ms]
running user script...
script complete [1ms]
tracing input files...
{ Error: UNKNOWN: unknown error, readlink 'C:\Users\user\Documents\werk\node\now\tracker\api\user\details.js'
    at Object.readlinkSync (fs.js:850:3)
    at Job.readlink (C:\Users\user\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\@now\node\dist\index.js:36751:23)
    at Job.realpath (C:\Users\user\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\@now\node\dist\index.js:36818:26)
    at Promise.all.files.map.file (C:\Users\user\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\@now\node\dist\index.js:36690:22)
    at Array.map (<anonymous>)
    at Object.module.exports.module.exports [as default] (C:\Users\user\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\@now\node\dist\index.js:36688:27)
    at compile (C:\Users\user\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\@now\node\dist\index.js:23686:70)
    at Object.build (C:\Users\user\AppData\Roaming\co.zeit.now\Caches\dev\builders\node_modules\@now\node\dist\index.js:23806:71)
  message:
   'UNKNOWN: unknown error, readlink \'C:\\Users\\user\\Documents\\werk\\node\\now\\tracker\\api\\user\\details.js\'',
  errno: -4094,
  syscall: 'readlink',
  code: 'UNKNOWN',
  path:
   'C:\\Users\\user\\Documents\\werk\\node\\now\\tracker\\api\\user\\details.js' }


```
While deploying to zeit.co works fine.
I tried the following:
- Removing all zeit folders in the Roaming folder
- Removing the cached now files in the npm cache
- Removing now Desktop
- Reinstalling now
- Installing now@canary
- Rebooting my computer
- Changing project to something I know worked before

I've had this error [occasionally before](https://github.com/zeit/docs/issues/1006#issuecomment-515694786) but wasn't present for all my projects. @timothyis already responded and said he couldn't reproduce the error with the repo I shared in that thread but it appears to be linked to my computer.

**Comment by TJkrusinski** [comment]
I'm getting this as well. Having a lot of trouble trying to debug the issues. I've reduced down to a simple case and still getting the problem.

**Comment by Bartvelp** [comment]
Yes, please see @TJkrusinski https://github.com/zeit/now-builders/issues/855#issuecomment-517006324.
Closing since it is fixed in canary. But I really think there should be a longer test period or better tests.
