### ISSUE TITLE
nest.js sample 23-type-graphql, using `ncc` build work fine, but `now dev` not work.

### ISSUE THREAD

**Issue by SolidZORO** [vercel/vercel#2680]
nest.js sample 23-type-graphql https://github.com/nestjs/nest/tree/master/sample/23-type-graphql, using `ncc` build work fine, but `now dev` not work.

run `ncc`, build, output this dir, i found that as long as the `type-graphql` reference is included in the project, the typescript lib is output. and it is huge.

```
./dist

├── common
│   └── scalars
├── recipes
│   ├── dto
│   └── models
├── index.js  <--- 17MB!
└── typescript  <----  44 MB!
    └── lib
        ├── cs
        ├── de
        ├── es
        ├── fr
        ├── it
        ├── ja
        ├── ko
        ├── pl
        ├── pt-br
        ├── ru
        ├── tr
        ├── zh-cn
        └── zh-tw
```

and run `now dev -d`

```
./now.json

{
  "version": 2,
  "name": "nestjs-sample-23-type-graphql",
  "builds": [
    {
      "src": "dist/index.js",
      "use": "@now/node-server"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "dist/index.js"
    }
  ]
}

```

output error:

```
10:05:50 ➜ CAPTAIN <SolidZORO/Downloads/23-type-graphql> 23-type-graphql now dev -d
> [debug] [2019-08-01T02:06:00.377Z] Found config in file /Users/SolidZORO/Downloads/23-type-graphql/now.json
> [debug] [2019-08-01T02:06:00.382Z] Using Now CLI 15.9.0-canary.24
> [debug] [2019-08-01T02:06:00.384Z] user supplied known subcommand
> Now CLI 15.9.0-canary.24 dev (beta) — https://zeit.co/feedback/dev
> [debug] [2019-08-01T02:06:00.471Z] The yarn executable is already cached, not re-downloading
> [debug] [2019-08-01T02:06:00.473Z] Reading `package.json` file
> [debug] [2019-08-01T02:06:00.474Z] Reading `now.json` file
> [debug] [2019-08-01T02:06:00.478Z] Locating files /Users/SolidZORO/Downloads/23-type-graphql
> [debug] [2019-08-01T02:06:00.479Z] Ignoring /Users/SolidZORO/Downloads/23-type-graphql/.DS_Store
> [debug] [2019-08-01T02:06:00.479Z] Ignoring /Users/SolidZORO/Downloads/23-type-graphql/.gitignore
> [debug] [2019-08-01T02:06:00.480Z] Ignoring /Users/SolidZORO/Downloads/23-type-graphql/.idea
> [debug] [2019-08-01T02:06:00.480Z] Ignoring /Users/SolidZORO/Downloads/23-type-graphql/node_modules
> [debug] [2019-08-01T02:06:00.487Z] Locating files /Users/SolidZORO/Downloads/23-type-graphql: 8.188ms
> [debug] [2019-08-01T02:06:03.425Z] Adding build match for "dist/index.js"
> Ready! Available at http://localhost:3000
> [debug] [2019-08-01T02:06:06.300Z] No builders were updated
> GET /
> [debug] [2019-08-01T02:06:11.314Z] Using cached `now.json` config
> [debug] [2019-08-01T02:06:11.325Z] Using cached `now.json` config
> [debug] [2019-08-01T02:06:11.325Z] Building asset "dist/index.js-dist/index.js" for "GET /"
> Building @now/node-server:dist/index.js
> [debug] [2019-08-01T02:06:11.326Z] Using `@now/node-server@0.8.2`
> [debug] [2019-08-01T02:06:11.326Z] Creating build process for dist/index.js
downloading user files...
installing dependencies for user's code...
missing `engines` in `package.json`, using default range: 8.10.x
installing to /Users/SolidZORO/Downloads/23-type-graphql/dist
npm WARN nest-typescript-starter@1.0.0 No repository field.

audited 1499 packages in 2.512s
found 0 vulnerabilities

running user script...
preparing lambda files...
compiling entrypoint with ncc...
ncc: Version 0.18.5
ncc: Compiling file index.js
> [debug] [2019-08-01T02:06:22.925Z] Built asset dist/index.js-dist/index.js
{ Error: Module build failed (from /Users/SolidZORO/Library/Caches/co.zeit.now/dev/builders/node_modules/@zeit/ncc/dist/ncc/loaders/relocate-loader.js):
SyntaxError: Unexpected token (354684:10)
    at Object.re.raise (evalmachine.<anonymous>:1:266416)
    at Object.z.unexpected (evalmachine.<anonymous>:1:222693)
    at Object.ee.parseIdent (evalmachine.<anonymous>:1:265599)
    at Object.parseIdent (evalmachine.<anonymous>:1:461728)
    at Object.parseIdent (evalmachine.<anonymous>:1:186548)
    at Object.ee.parsePropertyName (evalmachine.<anonymous>:1:261995)
    at Object.parsePropertyName (evalmachine.<anonymous>:1:4333)
    at Object.H.parseClassElement (evalmachine.<anonymous>:1:236905)
    at Object.parseClassElement (evalmachine.<anonymous>:1:459918)
    at Object.parseClassElement (evalmachine.<anonymous>:1:183081)
    at compiler.close.n (evalmachine.<anonymous>:3:1350338)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'Module build failed (from /Users/SolidZORO/Library/Caches/co.zeit.now/dev/builders/node_modules/@zeit/ncc/dist/ncc/loaders/relocate-loader.js):\nSyntaxError: Unexpected token (354684:10)\n    at Object.re.raise (evalmachine.<anonymous>:1:266416)\n    at Object.z.unexpected (evalmachine.<anonymous>:1:222693)\n    at Object.ee.parseIdent (evalmachine.<anonymous>:1:265599)\n    at Object.parseIdent (evalmachine.<anonymous>:1:461728)\n    at Object.parseIdent (evalmachine.<anonymous>:1:186548)\n    at Object.ee.parsePropertyName (evalmachine.<anonymous>:1:261995)\n    at Object.parsePropertyName (evalmachine.<anonymous>:1:4333)\n    at Object.H.parseClassElement (evalmachine.<anonymous>:1:236905)\n    at Object.parseClassElement (evalmachine.<anonymous>:1:459918)\n    at Object.parseClassElement (evalmachine.<anonymous>:1:183081)' }
> [debug] [2019-08-01T02:06:22.928Z] Error: Module build failed (from /Users/SolidZORO/Library/Caches/co.zeit.now/dev/builders/node_modules/@zeit/ncc/dist/ncc/loaders/relocate-loader.js):
SyntaxError: Unexpected token (354684:10)
    at Object.re.raise (evalmachine.<anonymous>:1:266416)
    at Object.z.unexpected (evalmachine.<anonymous>:1:222693)
    at Object.ee.parseIdent (evalmachine.<anonymous>:1:265599)
    at Object.parseIdent (evalmachine.<anonymous>:1:461728)
    at Object.parseIdent (evalmachine.<anonymous>:1:186548)
    at Object.ee.parsePropertyName (evalmachine.<anonymous>:1:261995)
    at Object.parsePropertyName (evalmachine.<anonymous>:1:4333)
    at Object.H.parseClassElement (evalmachine.<anonymous>:1:236905)
    at Object.parseClassElement (evalmachine.<anonymous>:1:459918)
    at Object.parseClassElement (evalmachine.<anonymous>:1:183081)
    at compiler.close.n (evalmachine.<anonymous>:3:1350338)
    at _promise0.then._result0 (eval at create (evalmachine.<anonymous>:1:349386), <anonymous>:13:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
> [debug] [2019-08-01T02:06:23.030Z] Build process for dist/index.js exited with 1


```

 i found `now dev` use `ncc: Version 0.18.5`, my local is `ncc: Version 0.20.4`.

i don't know if it's too big or because of other reasons that can't be deployed.

**Comment by styfle** [comment]
Hi @SolidZORO 

A lot has change since this issue.

1. We no longer support `@now/node-server` so you can try `@vercel/node` instead.
2. We no longer use `ncc`, instead `node-file-trace` is used

Does switching to `@vercel/node` solve your issue?

**Comment by SolidZORO** [comment]
Too long, I have forgotten, maybe this question is not important, thank you for your reply.

**Comment by jeluchu** [comment]
Thank you very much @styfle  for this solution, I have not known why deployments gave me an error for several days. And this that you have put has given me the solution
