### ISSUE TITLE
`now` is giving an error using Mojave and Node 8 LTS

### ISSUE THREAD

**Issue by paulogdm** [vercel/vercel#2711]
```
$ now
(node:32756) ExperimentalWarning: The http2 module is an experimental API.
(node:32756) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 nowExit listeners added. Use emitter.setMaxListeners() to increase limit
> Error! An unexpected error occurred!
TypeError: e.ref is not a function
at f.ref (/usr/local/lib/node_modules/now/dist/index.js:2:491203)
at H2Context.getOrCreateHttp2 (/usr/local/lib/node_modules/now/dist/index.js:2:488764)
at Context.getOrCreateHttp2 (/usr/local/lib/node_modules/now/dist/index.js:2:1713162)
at Context.getHttp2 (/usr/local/lib/node_modules/now/dist/index.js:2:1713387)
at Object.get (/usr/local/lib/node_modules/now/dist/index.js:2:1711928)
at fetchImpl (/usr/local/lib/node_modules/now/dist/index.js:2:3785448)
at <anonymous> TypeError: e.ref is not a function
at f.ref (/usr/local/lib/node_modules/now/dist/index.js:2:491203)
at H2Context.getOrCreateHttp2 (/usr/local/lib/node_modules/now/dist/index.js:2:488764)
at Context.getOrCreateHttp2 (/usr/local/lib/node_modules/now/dist/index.js:2:1713162)
at Context.getHttp2 (/usr/local/lib/node_modules/now/dist/index.js:2:1713387)
at Object.get (/usr/local/lib/node_modules/now/dist/index.js:2:1711928)
at fetchImpl (/usr/local/lib/node_modules/now/dist/index.js:2:3785448)
at <anonymous>
```
The error was originally reported by @leourbina.
```
node version is v8.9.0
now version is 16.0.0
```

**Comment by TooTallNate** [comment]
Because of `fetch-h2`, you need node `>= 8.11`.

We should do _one of_ the following:

 * Adjust the engines field in `package.json` to require node `>= 8.11`, _or_
 * __Not__ use `fetch-h2` in `< 8.10`

**Comment by leo** [comment]
Engines field!
