### ISSUE TITLE
npm now broken: TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by bartdeslagmulder** [vercel/vercel#282]
Hi guys!

Just started a new project with micro and now.
I've installed node v7.5.0 and set up a basic micro function from the micro github page.
Everything works fine on localhost.

I'm on the point to use now (as I did in several previous projects) but I receive this error when checking the version:

```
bartdeslagmulder:~/workspace (master) $ now -v
/home/ubuntu/workspace/node_modules/now/bin/now.js:34
  let message = `Update available! ${chalk.red(update.current)} → ${chalk.green(update.latest)} \n`
                                                     ^

TypeError: Cannot read property 'current' of undefined
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/now/bin/now.js:34:54)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

Installing now@4.0.1 is working fine for me.

Package.json contents:

```
{
  "name": "xxx",
  "version": "1.0.1",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "deploy": "npm version patch && now --alias",
    "dev": "nodemon --exec npm start",
    "start": "micro -p 8080",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "micro": "^6.2.1",
    "now": "^4.1.0"
  },
  "devDependencies": {
    "nodemon": "^1.11.0"
  }
}
```

Already tried removing the node_modules folder and downgrading to Node.js v7.4.0 without success.

**Comment by leo** [comment]
Should be fixed! 😊 https://github.com/zeit/now-cli/releases/tag/4.1.1
