### ISSUE TITLE
@now/node: Cannot find module '~' when using paths in TypeScript

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2832]
Trying to use the micro-cookie-session lib with @now/node@canary and I'm getting this error below.

Don't have the error when I run the code locally (with micro-dev)

```
Unable to import module 'launcher': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.901 (/var/task/user/backend/index.js:4546:18)
    at __webpack_require__ (/var/task/user/backend/index.js:22:30)
    at Object.68 (/var/task/user/backend/index.js:69:18)
    at __webpack_require__ (/var/task/user/backend/index.js:22:30)
    at Object.262 (/var/task/user/backend/index.js:401:17)
    at __webpack_require__ (/var/task/user/backend/index.js:22:30)
```

**edit:** This happens in @now/node now.

For context, using typescript

**Comment by vadistic** [comment]
Btw. I found okeyish temp solution. You can compile your lambdas directly on Now with "prepare/preinstall" script.  Like `"preinstall": "yarn build"` & pointing routes to compiled code.

It also fixes my issue with shared monorepo deps (that worked only when local dist folders were present), and lack of support for typescript composite projects/ project references.

This way you can use `https://github.com/LeDDGroup/typescript-transform-paths` or some simple custom js script replacer / or even simple bash sed to do whatever with your paths. The only downside is slightly increased build time and sligth abuse of zeit's free rescources^^

**Comment by amaury1093** [comment]
On the docs https://zeit.co/docs/runtimes#official-runtimes/node-js/using-typescript-with-the-node-js-runtime:

> Most options are supported aside from "Path Mappings" and "Project References".

Is this the right issue to track where these two features are going to be supported by now?

**Comment by theKashey** [comment]
So is there any workaround? 
If not - then `now` should throw an error is `paths` in `tsconfig` are not empty.

**Comment by 0ubbe** [comment]
Yup just spent 1h this afternoon trying to figure this out. 

I think setting `"paths"` in TS is common enough to have well documented this incompatibility and possible workarounds.
I'm happy to contribute with documentation PRs 🙌🏼

**Comment by gaoxiaoliangz** [comment]
`vercel dev` still has this problem. I checked the code in `dev-server.js`, it seems that ts-node only uses `target` in provided tsconfig.json.

**Comment by neoromantic** [comment]
Any follow-up here? Any suggestions on how to use Vercel withcustom paths?

**Comment by emzet93** [comment]
Any updates on this? My serverless function in `api/` directory uses imports alias and I'm trying to find a way to make it work on vercel. Is there any way to achieve this at the moment?

**Comment by sam-potter** [comment]
```js
// tsconfig.json

{
  "compilerOptions": {
    "baseUrl": "."
  }
}
```

```js
// src/utils/assert.ts

export function assert(value: unknown, message: string | Error): asserts value {
  if (typeof value === 'undefined') throw message instanceof Error ? message : new Error(message);
}
```

```js
// api/edge.ts

import { assert } from "src/utils/assert";

export const config = {
  runtime: "edge",
};

export default function handler(req: Request) {
  assert(req, "req is undefined");

  return new Response("Hello world!");
}
```

Just wanting to bump this again. The code above will fail to deploy to Vercel with the following error message:
`vc-file-system:api/edge.js:4:25: ERROR: Could not resolve "src/utils/assert"`. CLI version `28.8.0`. This is an edge function, but same issue occurs with regular serverless functions.

This issue has been open since 2019, just wondering if there are any plans to support this behaviour?

:heart:

**Comment by kevbook** [comment]
Any updates on this? Or any possible workarounds

**Comment by hrasoa** [comment]
Did not test on production, but this is working for me on local:

Install `tsconfig-paths`
Then in `tsconfig.json`:

```json
  "ts-node": {
    "require": ["tsconfig-paths/register"],
    "compilerOptions": {
      "module": "commonjs"
    }
  }
```

**Comment by kevbook** [comment]
It works on Vercel now

**Comment by criskell** [comment]
any follow-up pls?
