### ISSUE TITLE
FetchError: getaddrinfo EMFILE

### ISSUE THREAD

**Issue by homerjam** [vercel/vercel#2837]
The log below is from the build step obtained via the dashboard.

I think this could be linked to zeit/now-builders#342 

My own fork of the @nuxtjs/now-builder works - it uses zeit/now-builders#344 

zeit/now-builders#353 was supposed to have resolved this but it seems not...

```
14:09:19  ----------------- Prepare build -----------------
--
BUILD | May 02 2019 15:09:19:648 | 14:09:19 Entry directory: .
BUILD | May 02 2019 15:09:19:648 | 14:09:19 Downloading files...
BUILD | May 02 2019 15:09:20:343 | decompressing release url...
BUILD | May 02 2019 15:09:24:994 | { FetchError: request to https://dmmcy0pwk6bqi.cloudfront.net/14729b6f3781397cc2ba4a62208093e1fa9d7c3e failed, reason: getaddrinfo EMFILE dmmcy0pwk6bqi.cloudfront.net:443     at ClientRequest.<anonymous> (/var/task/worker.js:3659:11)     at emitOne (events.js:116:13)     at ClientRequest.emit (events.js:211:7)     at TLSSocket.socketErrorListener (_http_client.js:355:9)     at emitOne (events.js:116:13)     at TLSSocket.emit (events.js:211:7)     at emitErrorNT (internal/streams/destroy.js:64:8)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   message: 'request to https://dmmcy0pwk6bqi.cloudfront.net/14729b6f3781397cc2ba4a62208093e1fa9d7c3e failed, reason: getaddrinfo EMFILE dmmcy0pwk6bqi.cloudfront.net:443',   type: 'system',   errno: 'EMFILE',   code: 'EMFILE' }
BUILD | May 02 2019 15:09:28:015 | { FetchError: request to https://api-bru1.zeit.co/v2/now/deployments/dpl_A3ikxgP42BCt9mRWPFsiyrrDAGrk/builds/bld_li5l27o0u failed, reason: getaddrinfo EMFILE api-bru1.zeit.co:443     at ClientRequest.<anonymous> (/var/task/worker.js:3659:11)     at emitOne (events.js:116:13)     at ClientRequest.emit (events.js:211:7)     at TLSSocket.socketErrorListener (_http_client.js:355:9)     at emitOne (events.js:116:13)     at TLSSocket.emit (events.js:211:7)     at emitErrorNT (internal/streams/destroy.js:64:8)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   message: 'request to https://api-bru1.zeit.co/v2/now/deployments/dpl_A3ikxgP42BCt9mRWPFsiyrrDAGrk/builds/bld_li5l27o0u failed, reason: getaddrinfo EMFILE api-bru1.zeit.co:443',   type: 'system',   errno: 'EMFILE',   code: 'EMFILE' }
BUILD | May 02 2019 15:09:28:027 | { FetchError: request to https://slack.com/api/chat.postMessage failed, reason: getaddrinfo EMFILE slack.com:443     at ClientRequest.<anonymous> (/var/task/worker.js:55275:11)     at emitOne (events.js:121:20)     at ClientRequest.emit (events.js:211:7)     at TLSSocket.socketErrorListener (_http_client.js:355:9)     at emitOne (events.js:116:13)     at TLSSocket.emit (events.js:211:7)     at emitErrorNT (internal/streams/destroy.js:64:8)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   name: 'FetchError',   message: 'request to https://slack.com/api/chat.postMessage failed, reason: getaddrinfo EMFILE slack.com:443',   type: 'system',   errno: 'EMFILE',   code: 'EMFILE' }
BUILD | May 02 2019 15:09:31:036 | { FetchError: request to https://api-bru1.zeit.co/v2/now/deployments/dpl_A3ikxgP42BCt9mRWPFsiyrrDAGrk/builds/bld_li5l27o0u failed, reason: getaddrinfo EMFILE api-bru1.zeit.co:443     at ClientRequest.<anonymous> (/var/task/worker.js:3659:11)     at emitOne (events.js:116:13)     at ClientRequest.emit (events.js:211:7)     at TLSSocket.socketErrorListener (_http_client.js:355:9)     at emitOne (events.js:116:13)     at TLSSocket.emit (events.js:211:7)     at emitErrorNT (internal/streams/destroy.js:64:8)     at _combinedTickCallback (internal/process/next_tick.js:138:11)     at process._tickDomainCallback (internal/process/next_tick.js:218:9)   message: 'request to https://api-bru1.zeit.co/v2/now/deployments/dpl_A3ikxgP42BCt9mRWPFsiyrrDAGrk/builds/bld_li5l27o0u failed, reason: getaddrinfo EMFILE api-bru1.zeit.co:443',   type: 'system',   errno: 'EMFILE',   code: 'EMFILE' }
```

**Comment by styfle** [comment]
We no longer download files and instead utilize `git clone`, so you should no longer see this error.
