### ISSUE TITLE
Cannot find module XY when using nested package.json

### ISSUE THREAD

**Issue by lemmon** [vercel/vercel#2840]
Not sure if this is related to the builder or ncc, or if actually it is a bug. I have an exemple app that contains two `@now/node` builds. One contains `package.json` file, another one doesn't. There's another `package.json` in the root directory that contains a dependency. The build containing the package file fiails to load the dependency.

https://now-require.lemmon.now.sh/ (runs fine)
https://now-require.lemmon.now.sh/api (fails)

example code:
https://github.com/lemmon/now-require

error log from the /api request
```
START RequestId: 0eb4cb18-caed-45d3-9e1e-af59b2b409f6 Version: $LATEST
2019-06-24T12:59:43.396Z	0eb4cb18-caed-45d3-9e1e-af59b2b409f6	Cannot find module 'basic-auth'
2019-06-24T12:59:43.396Z	0eb4cb18-caed-45d3-9e1e-af59b2b409f6	Did you forget to add it to "dependencies" in `package.json`?
END RequestId: 0eb4cb18-caed-45d3-9e1e-af59b2b409f6
REPORT RequestId: 0eb4cb18-caed-45d3-9e1e-af59b2b409f6	
Duration: 56.77 ms  Billed Duration: 100 ms   Memory Size: 3008 MB  Max Memory Used: 24 MB	
RequestId: 0eb4cb18-caed-45d3-9e1e-af59b2b409f6 Process exited before completing request
```

What is interesting is that this code runs flawlessly with `now dev` but it fails when deployed. Not sure if this is a bug or just unexpected behavior with the local dev environment.

It would be nice if now would be able to locate 'root' dependencies so there's no need to include them more than once.

**Comment by styfle** [comment]
The inconsistency here that `/api` fails and `/api/` works.

The routing is a little different between `now dev` and `now` which needs to be the same.

**Comment by LexSwed** [comment]
Same issue I have in monorepo with `@vercel/node@1.6.0`

```bash
Built @now/node@latest:api/translate.ts [3s]
Cannot find module 'node-fetch'
Require stack:
- /private/var/folders/tc/p0dlxnfn53n0pl_w210gmjym0000gn/T/zeit-fun-4e9d18e2d8133/api/_utils/bing.js
- /private/var/folders/tc/p0dlxnfn53n0pl_w210gmjym0000gn/T/zeit-fun-4e9d18e2d8133/api/translate.ts
- /private/var/folders/tc/p0dlxnfn53n0pl_w210gmjym0000gn/T/zeit-fun-4e9d18e2d8133/___now_launcher.js
- /Users/[user]/Library/Caches/co.zeit.fun/runtimes/nodejs/bootstrap.js
Did you forget to add it to "dependencies" in `package.json`?
LambdaError: RequestId: 62971c19-47e6-44dc-9e2b-13aae7270910 Process exited before completing request
    at Lambda.<anonymous> (/Users/[user]/[project]/node_modules/vercel/dist/index.js:2:3455199)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/[user]/[project]/node_modules/vercel/dist/index.js:2:3453086)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
So `vercel` is run from the root of the `project` while ~full path to the `/api` is `[project]/packages/www/api/`

**Comment by user72356** [comment]
Has anyone in this thread found a fix for this?
