### ISSUE TITLE
static doesn't work in v4.1.2

### ISSUE THREAD

**Issue by devongovett** [vercel/vercel#288]
Looks like `serve` was bumped, but it doesn't run with the `harmony-async-await` flag.

```
> > serve ./content
> /home/nowuser/src/node_modules/b01b4c3f7eef4ef3ac933c4c925304ca3432df6b/lib/index.js:43
> const handler = async (req, res) => {
>                       ^
> SyntaxError: Unexpected token (
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:545:28)
>     at Module._extensions..js (module.js:582:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/2a9909022d27ed3456706e4b2e3a923934cd710e/register.js:42:5)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/b01b4c3f7eef4ef3ac933c4c925304ca3432df6b/bin/serve.js:37:1)
```

**Comment by avanslaars** [comment]
I'm seeing the same thing, and this comes after a long delay in attempting to install `serve@^3.1.0` - I see 
```
⧗ Installing:
 ‣ serve@^3.1.0
FetchError: network timeout at: http://10.100.202.49:3000
```

Followed by 

```
> Installing package serve@^3.1.0
> ▲ npm start
> ▲ npm install
> > public@ start /home/nowuser/src
> > serve ./content
>     at Object.<anonymous> (/home/nowuser/src/node_modules/b01b4c3f7eef4ef3ac933c4c925304ca3432df6b/bin/serve.js:37:1)
> /home/nowuser/src/node_modules/b01b4c3f7eef4ef3ac933c4c925304ca3432df6b/lib/index.js:43
> const handler = async (req, res) => {
```

Not sure if those are related, but hope this helps iron out the issue

**Comment by devongovett** [comment]
I solved it temporarily by adding a package.json like this:

```json
{
  "name": "my-site",
  "version": "1.0.0",
  "scripts": {
    "start": "node --harmony-async-await ./node_modules/.bin/serve ."
  },
  "dependencies": {
    "serve": "^3.2.2"
  }
}
```

**Comment by leo** [comment]
Should work [now](https://github.com/zeit/now-cli/releases/tag/4.2.2)! 😊
