### ISSUE TITLE
[now dev] [golang] Cant run @now/go in dev

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2933]
Reproducable library:

https://github.com/aequasi/snowflake

```shell
aaron at Aarons-MBP-2 in ~/projects/snowflake on master
$ now dev
> Now CLI 16.1.2 dev (beta) — https://zeit.co/feedback/dev
> Ready! Available at http://localhost:3000
> GET /
> Building @now/go:index.go

Manually assigning 'GO111MODULE' is not recommended.

By default:
  - 'GO111MODULE=on' If entrypoint package name is not 'main'
  - 'GO111MODULE=off' If entrypoint package name is 'main'

We highly recommend you leverage Go Modules in your project.
Learn more: https://github.com/golang/go/wiki/Modules

Downloading user files...
Parsing AST for "index.go"
go: finding github.com/bwmarrin/snowflake v0.3.0
Found exported function "H" in "index.go"
Tidy `go.mod` file...
go: finding github.com/bwmarrin/snowflake v0.3.0
go: downloading github.com/bwmarrin/snowflake v0.3.0
go: extracting github.com/bwmarrin/snowflake v0.3.0
go: finding github.com/zeit/now-builders/utils/go/bridge latest
go: finding github.com/zeit/now-builders/utils/go latest
go: finding github.com/zeit/now-builders/utils latest
go: finding github.com/zeit/now-builders latest
go: downloading github.com/zeit/now-builders v0.0.0-20190824121048-fa411a5e4cb1
go: extracting github.com/zeit/now-builders v0.0.0-20190824121048-fa411a5e4cb1
go: finding github.com/aws/aws-lambda-go/events latest
go: finding github.com/aws/aws-lambda-go/lambda latest
go: finding github.com/aws/aws-lambda-go v1.13.1
go: downloading github.com/aws/aws-lambda-go v1.13.1
go: extracting github.com/aws/aws-lambda-go v1.13.1
go: finding github.com/urfave/cli v1.21.0
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/stretchr/objx v0.1.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/stretchr/testify v1.3.0
go: extracting github.com/stretchr/testify v1.3.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.0
go: extracting github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/davecgh/go-spew v1.1.0
Running `go build`...
go: cannot find main module; see 'go help modules'
{ Error: Command failed: go get
    at makeError (/Users/aaron/.nvm/versions/node/v10.16.3/lib/node_modules/now/dist/index.js:2:135543)
    at Promise.all.then.e (/Users/aaron/.nvm/versions/node/v10.16.3/lib/node_modules/now/dist/index.js:2:136670)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }


```

**Comment by cryptiklemur** [comment]
This repo successfully deploys:

```
yarn info @now/build-utils@latest...
yarn info @now/go...
yarn add @now/build-utils@0.9.13...
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @now/build-utils@0.9.13
info All dependencies
└─ @now/build-utils@0.9.13
Done in 0.61s.
yarn add @now/go@0.5.10...
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @now/go@0.5.10
info All dependencies
└─ @now/go@0.5.10
Done in 0.73s.
yarn run now-postinstall...
yarn run v1.17.3
$ node dist/install.js
Downloading Go ...
Done in 7.91s.
running builder.exports.build...
Downloading user files...
Parsing AST for "index.go"
Found exported function "H" in "index.go"
Tidy `go.mod` file...
go: finding github.com/bwmarrin/snowflake v0.3.0
go: downloading github.com/bwmarrin/snowflake v0.3.0
go: extracting github.com/bwmarrin/snowflake v0.3.0
go: finding github.com/zeit/now-builders/utils/go/bridge latest
go: finding github.com/zeit/now-builders/utils/go latest
go: finding github.com/zeit/now-builders/utils latest
go: finding github.com/zeit/now-builders latest
go: downloading github.com/zeit/now-builders v0.0.0-20190824121048-fa411a5e4cb1
go: extracting github.com/zeit/now-builders v0.0.0-20190824121048-fa411a5e4cb1
go: finding github.com/aws/aws-lambda-go/events latest
go: finding github.com/aws/aws-lambda-go/lambda latest
go: finding github.com/aws/aws-lambda-go v1.13.1
go: downloading github.com/aws/aws-lambda-go v1.13.1
go: extracting github.com/aws/aws-lambda-go v1.13.1
go: finding github.com/urfave/cli v1.21.0
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/BurntSushi/toml v0.3.1
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: downloading github.com/stretchr/testify v1.3.0
go: extracting github.com/stretchr/testify v1.3.0
go: downloading github.com/davecgh/go-spew v1.1.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/davecgh/go-spew v1.1.0
Running `go build`...
done
done
```

**Comment by thasophearak** [comment]
@aequasi Thank for the issue 🙌  

I've tried to reproduce it, but not able to.
![image](https://user-images.githubusercontent.com/5785105/64158432-a90f9b80-ce62-11e9-92db-8e4cc6283707.png)

But I've encounter different thing with when I set `GO111MODULE=on` in my environment variable.

Would you mind try it again in a folder where you don't set any `GO111MODULE` at all?

PS: `GO111MODULE` is managed by `@now/go` builder itself.

**Comment by cryptiklemur** [comment]
AFAIK I'm not setting that anywhere. I did just update to `16.1.3 dev (beta)` and the issue seems to have gone away. 

Can re-open if this issue comes up again

**Comment by technowar** [comment]
I cloned your repo, and ran `now dev` on my computer and got this.

![Screenshot_2019-09-14_06-40-45](https://user-images.githubusercontent.com/2110456/64871306-8b6adf00-d677-11e9-8001-ac69ff771342.png)

My `now` version is 16.2.0.

**EDIT**, made it work with 16.2.0.

**Comment by shuiRong** [comment]
Back up a related problem and solution.

If you got this:
```
go: cannot find main module, but found .git/config in /Users/...../Code/Golang/xxxxxx
        to create a module there, run:
        cd ../../../.. && go mod init
```
and the API is `502`, please run `go mod init` in your project root path.

The error message above is inaccurate. (wrong path)
