### ISSUE TITLE
UnicodeEncodeError in python builder

### ISSUE THREAD

**Issue by offero** [vercel/vercel#3091]
Any payload that has non-ascii characters in it blows up if not encoded in latin-1. All payloads from browsers will be utf-8.

To reproduce: Have a web app send (fetch) a json payload with strings with Greek (or other non-ascii characters) to a python endpoint deployed on now.

Logs:
```
Duration: 1.84 ms     Billed Duration: 100 ms Memory Size: 3008 MB    Max Memory Used: 66 MB
                          Unhandled exception in thread started by <bound method BaseServer.handle_request of <http.server.HTTPServer object at 0x7f83a3e29e48>>
                          Traceback (most recent call last):
                            File "/var/lang/lib/python3.6/socketserver.py", line 298, in handle_request
                              ready = selector.select(timeout)
                            File "/var/lang/lib/python3.6/selectors.py", line 376, in select
                              fd_event_list = self._poll.poll(timeout)
                          PermissionError: [Errno 1] Operation not permitted
                          'latin-1' codec can't encode characters in position 2370-2379: Body ('Χριστοφορε') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.: UnicodeEncodeError
                          Traceback (most recent call last):
                            File "/var/task/now__handler__python.py", line 42, in now_handler
                              headers=headers, data=body, allow_redirects=False)
                            File "/var/task/requests/api.py", line 60, in request
                              return session.request(method=method, url=url, **kwargs)
                            File "/var/task/requests/sessions.py", line 533, in request
                              resp = self.send(prep, **send_kwargs)
                            File "/var/task/requests/sessions.py", line 646, in send
                              r = adapter.send(request, **kwargs)
                            File "/var/task/requests/adapters.py", line 449, in send
                              timeout=timeout
                            File "/var/task/urllib3/connectionpool.py", line 672, in urlopen
                              chunked=chunked,
                            File "/var/task/urllib3/connectionpool.py", line 387, in _make_request
                              conn.request(method, url, **httplib_request_kw)
                            File "/var/lang/lib/python3.6/http/client.py", line 1254, in request
                              self._send_request(method, url, body, headers, encode_chunked)
                            File "/var/lang/lib/python3.6/http/client.py", line 1299, in _send_request
                              body = _encode(body, 'body')
                            File "/var/lang/lib/python3.6/http/client.py", line 171, in _encode
                              (name.title(), data[err.start:err.end], name)) from None
                          UnicodeEncodeError: 'latin-1' codec can't encode characters in position 2370-2379: Body ('Χριστοφορε') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
        
```

Full reproduction here: https://github.com/offero/nowpyunicodefail

**Comment by pedropregueiro** [comment]
Having the same issue with euro sign (€).

**Comment by offero** [comment]
The now handler creates a `request` object here: https://github.com/zeit/now/blob/canary/packages/now-python/now_init.py#L56

`request` calls `_send_request `which calls `_encode`: https://github.com/python/cpython/blob/3.6/Lib/http/client.py#L1299

`encode` tries to use latin-1
https://github.com/python/cpython/blob/3.6/Lib/http/client.py#L159

The fix is to encode to bytes using utf-8 when creating the request
