### ISSUE TITLE
Express js deployment - `NO_STATUS_CODE_FROM_LAMBDA`

### ISSUE THREAD

**Issue by Joozty** [vercel/vercel#3130]
Hi, I am trying to deploy express server which is running Next.js but I am not successful. I prepared a simple minimal working example here https://github.com/Joozty/zeit-example.

The error I am getting is:
```
502: BAD_GATEWAY
Code: NO_STATUS_CODE_FROM_LAMBDA
ID: zrh1:sbf2t-1570442652078-54973ddacf7e
```

In logs I can see:
```
2019-10-07T09:48:37.560Z	67956173-022c-4665-83bf-130bd94dad90	Error: > Couldn't find a `pages` directory. Please create one under the project root
    at Object.findPagesDir (/var/task/node_modules/next/dist/lib/find-pages-dir.js:3:170)
    at new Server (/var/task/node_modules/next/dist/next-server/server/next-server.js:40:42)
    at createServer (/var/task/node_modules/next/dist/server/next.js:2:133)
    at Object.<anonymous> (/var/task/server.js:7:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
Duration: 163.08 ms  Billed Duration: 200 ms  Memory Size: 3008 MB  Max Memory Used: 33 MB	
RequestId: 67956173-022c-4665-83bf-130bd94dad90 Process exited before completing request
```

Could you please point me out whether this is a bug on your side or in my code? I even tried to specify `dir` folder for next configuration but without any luck.

```
import next from 'next'

const app = next({ dir: __dirname, dev })
```

Thanks in advance

**Comment by Joozty** [comment]
Solved here https://spectrum.chat/zeit/now/500-code-internal-missing-response-from-cache~98e3b256-673c-4aa4-9456-116f96d5c3ce
