### ISSUE TITLE
What am I missing?: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by JohnAllen** [vercel/vercel#315]
```
$ node --version 
v5.2.0
```

```
npm install -g now
$ now
/usr/local/lib/node_modules/now/build/bin/now.js:4
const {resolve} = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
john@macbook:~$ now --version
/usr/local/lib/node_modules/now/build/bin/now.js:4
const {resolve} = require('path')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

Any thoughts on what's causing this?  `npm 4.2.0`

**Comment by JohnAllen** [comment]
Nevermind, I see from the `bin/now.js` file that Node 6 is required which works.
