### ISSUE TITLE
Successful built Node.js app is not responding.

### ISSUE THREAD

**Issue by nenravitsa** [vercel/vercel#3155]
I have a little telegram bot written on node.js, that successfully worked over the year on now v1.
But I faced a big problem with v2. Build is successful, no errors in console. The last line is "Done in 5.61s." On my dashboard I can see status "ready". But there is no runtime logs at all, and no response from app to. 

My config:

```
{
  "name": "blackoak",
  "alias": "blackoak.now.sh",
  "builds": [
    {
      "src": "./app.js",
      "use": "@now/node-server"
    },
    {
      "src": "./static",
      "use": "@now/static"
    }
  ],
  "public": true,
  "env": {
    "TOKEN": "@oaktoken",
    "NODE_ENV": "production",
    "MONGO_URL": "@mongourl"
  }
}
```

**Comment by styfle** [comment]
Try replacing `@now/node-server` with `@now/node` and rename `app.js` to `index.js` so that you don't have to visit `example.com/app.js`.

**Comment by nenravitsa** [comment]
Thanks for responding. For now I can see some logs on runtime console, but steel no errors and my application is not responding :(

**Comment by styfle** [comment]
I just visited https://blackoak.now.sh and it responds with [HTTP 401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) status code so that looks like something your app is doing, not the platform.

Perhaps you need to disable Auth?

**Comment by nenravitsa** [comment]
There is no auth at all and my app working well on local machine (but at the same time connected to remote database and telegram api).

**Comment by styfle** [comment]
Perhaps your remove database is responding with 401 and the status is forwarded to your serverless function response?

It's difficult to know without seeing the source code.

~~You might try adding `console.log(process.env.MONGO_URL)` at the top just to be sure the secret is assigned to the environment variable.~~

I just realized this is a public deployment so anyone can see the source code and logs.

This is the error message:

```
{ RequestError: Error: socket hang up
    at new RequestError (/var/task/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/var/task/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/var/task/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/var/task/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/var/task/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:355:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'EFATAL' }
```

Somewhere you are invoking `request` to an endpoint that doesn't respond.

You could try removing this code which appears to to periodically which is not currently supported:

```
//clean up db every sunday
schedule.scheduleJob("59 21 * * 0", () => {
  Warrior.update({}, { $set: { battles: null } }, { multi: true });
});
```
