### ISSUE TITLE
Failed Now Deployments

### ISSUE THREAD

**Issue by GainorB** [vercel/vercel#3179]
The repo is private, so I can't make it public, but things were working fine then all of a sudden deployments all fail with this from the logs:

```
{ FetchError: request to https://registry.now.systems/v2/now/01b6b067a727d5b113323f2ab71d690cf674c420/blobs/sha256:adc1f5edae575234136e21d5af0dad4db2b8a7a0e213600056570de47c98f178 failed, reason: certificate has expired
at ClientRequest.<anonymous> (/zeit/4c8275e5/.build-utils/.builder/node_modules/node-fetch/lib/index.js:1455:11)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at TLSSocket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
at TLSSocket.emit (events.js:211:7)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
message: 'request to https://registry.now.systems/v2/now/01b6b067a727d5b113323f2ab71d690cf674c420/blobs/sha256:adc1f5edae575234136e21d5af0dad4db2b8a7a0e213600056570de47c98f178 failed, reason: certificate has expired',
type: 'system',
errno: 'CERT_HAS_EXPIRED',
code: 'CERT_HAS_EXPIRED' }
```

Has anyone experienced this error? How can I fix this? This is happening across several projects. The now.json looks like this:

```
{
  "name": ".......",
  "version": 1,
  "type": "docker",
  "build": {
    "env": {
      "CONTENTFUL_SPACE_ID": "@.....",
      "CONTENTFUL_ACCESS_TOKEN": "@....."
    }
  },
  "env": {
    "CONTENTFUL_SPACE_ID": "@.....",
    "CONTENTFUL_ACCESS_TOKEN": "@....."
  }
}
```

**Comment by TooTallNate** [comment]
Thanks for the report, this should be resolved at this point. Can you please verify?

**Comment by GainorB** [comment]
@TooTallNate Thanks, everything is working now.. What was wrong? How can this be avoided?

**Comment by TooTallNate** [comment]
It was nothing on your end. There was a backend outage that we are taking necessary steps to avoid in the future. Thanks for your patience and confirmation of the fix!
