### ISSUE TITLE
Next.js 404 from non-Next deployment

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#328]
I'm hosting a `micro` server with `now` that just spits whatever requests it gets to the `console.log`, which i read via `now-logs`.  It's hosted at a subdomain of mine, `https://api-tester.wayhome.io`

I'm using it to test a Mailgun route, but my Mailgun logs are showing a weird response--it appears to be a 404 page from a `Next.js` deployment:

```
{
  "severity": "permanent",
  "tags": [],
  "storage": {
    "url": "https://se.api.mailgun.net/v3/domains/sandboxd<id>.mailgun.org/messages/<key>",
    "key": //redacted
  },
  "envelope": {
    "sender": "postmaster@sandboxd<id>.mailgun.org",
    "transport": "http",
    "targets": "https://api-tester.wayhome.io"
  },
  "delivery-status": {
    "attempt-no": 8,
    "description": "<!DOCTYPE html><html><head></head><body><div><div id=\"__next\"><div class=\"error error_404 \" data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"619030190\"><div class=\"text\" data-reactid=\"2\"><h1 data-reactid=\"3\">404</h1><div class=\"desc\" data-reactid=\"4\"><h2 data-reactid=\"5\"><!-- react-text: 6 -->This page could not be found<!-- /react-text --><!-- react-text: 7 -->.<!-- /react-text --></h2></div></div><style data-reactid=\"8\">    .error {      color: #000;      background: #fff;      top: 0;      bottom: 0;      left: 0;      right: 0;      position: absolute;      font-family: \"SF UI Text\", \"Helvetica Neue\", \"Lucida Grande\";      text-align: center;      padding-top: 20%;    }    .error.error_500 {      background: #000;      background: #fff;    }    h1, .desc {      display: inline-block;      vertical-align: top;    }    .desc {      text-align: left;      line-height: 49px;      height: 49px;      vertical-align: middle;    }    .shouldRetry .desc {      height: 29px;      margin-top: -18px;    }    h1, h2, h3 {      margin: 0;      padding: 0;      font-weight: normal;    }    h1 {      border-right: 1px solid rgba(0, 0, 0,.3);      margin-right: 20px;      padding: 10px 23px;      font-size: 24px;      font-weight: 500;    }    .shouldRetry h1 {      padding: 16px 23px;    }    .dark h1 {      border-right: 1px solid rgba(255, 255, 255, .3);    }    .shouldRetry h2, .shouldRetry h3 {      margin: 3px 0;    }    h2 {      font-size: 14px;    }    h3 {      font-size: 11px;      color: rgba(255, 255, 255, .68);    }  </style></div></div><script>__NEXT_DATA__ = {\"props\":{\"code\":404,\"title\":\"This page could not be found\",\"shouldRetry\":false},\"hash\":null,\"base\":\"\",\"serviceWorker\":false,\"component\":null}</script></div><script type=\"text/javascript\" src=\"/_next/next.bundle.js\"></script></body></html>",
    "session-seconds": 120.43688702583313,
    "retry-seconds": 14400,
    "code": 404,
    "message": "<!DOCTYPE html><html><head></head><body><div><div id=\"__next\"><div class=\"error error_404 \" data-reactroot=\"\" data-reactid=\"1\" data-react-checksum=\"619030190\"><div class=\"text\" data-reactid=\"2\"><h1 data-reactid=\"3\">404</h1><div class=\"desc\" data-reactid=\"4\"><h2 data-reactid=\"5\"><!-- react-text: 6 -->This page could not be found<!-- /react-text --><!-- react-text: 7 -->.<!-- /react-text --></h2></div></div><style data-reactid=\"8\">    .error {      color: #000;      background: #fff;      top: 0;      bottom: 0;      left: 0;      right: 0;      position: absolute;      font-family: \"SF UI Text\", \"Helvetica Neue\", \"Lucida Grande\";      text-align: center;      padding-top: 20%;    }    .error.error_500 {      background: #000;      background: #fff;    }    h1, .desc {      display: inline-block;      vertical-align: top;    }    .desc {      text-align: left;      line-height: 49px;      height: 49px;      vertical-align: middle;    }    .shouldRetry .desc {      height: 29px;      margin-top: -18px;    }    h1, h2, h3 {      margin: 0;      padding: 0;      font-weight: normal;    }    h1 {      border-right: 1px solid rgba(0, 0, 0,.3);      margin-right: 20px;      padding: 10px 23px;      font-size: 24px;      font-weight: 500;    }    .shouldRetry h1 {      padding: 16px 23px;    }    .dark h1 {      border-right: 1px solid rgba(255, 255, 255, .3);    }    .shouldRetry h2, .shouldRetry h3 {      margin: 3px 0;    }    h2 {      font-size: 14px;    }    h3 {      font-size: 11px;      color: rgba(255, 255, 255, .68);    }  </style></div></div><script>__NEXT_DATA__ = {\"props\":{\"code\":404,\"title\":\"This page could not be found\",\"shouldRetry\":false},\"hash\":null,\"base\":\"\",\"serviceWorker\":false,\"component\":null}</script></div><script type=\"text/javascript\" src=\"/_next/next.bundle.js\"></script></body></html>"
  },
  "event": "failed",
  "campaigns": [],
  "reason": "old",
  "user-variables": {},
  "flags": {
    "is-routed": false,
    "is-authenticated": true,
    "is-callback": true,
    "is-system-test": false,
    "is-test-mode": false
  },
  "log-level": "error",
  "timestamp": 1487250578.351978,
  "message": {
    "headers": {
     // mailstuff
    },
    "attachments": [],
    "recipients": [
      "https://api-tester.wayhome.io"
    ],
    "size": 9067
  },
  "recipient": "https://api-tester.wayhome.io"
```

this is strange b/c I'm not running `next`, but also b/c the endpoint sometimes works as intended. 

Also, it appears that eventually, the retry succeeds, as it does show up in my console via `now-logs`. 

Has anyone seen this before?  Any ideas how to fix?

Could this have to do with the `sleep` state that Now deployments go into? it seems that when the server has recently been active, these errors don't happen.

**Comment by jamo** [comment]
Looks like it's 404 from a misbehavior of the error inspector application...
I tried connecting directly to your deployment (`api-tester:wayhome:io`) and curl and other requests just "hang"

In the application logs I see a lot of errors like this (see the `details`)
(there is nothing too secretive looking in it so I think it's ok to share the log snippet here)
<details>

```
TypeError: argument string is required
    at Object.parse (/home/nowuser/src/node_modules/media-typer/index.js:141:11)
    at Promise (/home/nowuser/src/node_modules/micro/lib/server.js:55:26)
    at exports.json (/home/nowuser/src/node_modules/micro/lib/server.js:52:47)
    at /home/nowuser/src/index.js:11:48
    at Generator.next (<anonymous>)
    at c (/home/nowuser/src/index.js:70:99)
    at /home/nowuser/src/index.js:70:198
    at __async (/home/nowuser/src/index.js:70:28)
    at module.exports (/home/nowuser/src/index.js:7:46)
    at Function.<anonymous> (/home/nowuser/src/node_modules/micro/lib/server.js:25:23)
```
</details>



A proper logs support should ship soon so debugging issues like this
Feel free to ping in in zeit.chat slack if you need more assistance debugging is or follow up here..

**Comment by brandonmp** [comment]
Ah yeah, i should have mentioned that above--the endpoint only takes requests w/ a JSON or `urlencoded` `body` & just logs everything to console. this explains the `exception` you posted.

re: the hanging, since I was just interested  in logging the body, i forgot to `return` on completion--thanks for spotting that.


That said: 

> Looks like it's 404 from a misbehavior of the error inspector application...

Is that something internal to Zeit? 

The requests Mailgun was sending had `body` fields, and my endpoint correctly logged them (sometimes after a delay, which I'm guessing is due to the instance sleeping).  

I did some more testing.  When I run this command:

`$ curl --data-urlencode "paramName=param" https://api-tester.wayhome.io`

It hangs for a minute or so on my command line, then responds with the `404` mentioned in OP. The payload, though, is correctly logged to the `console` in the app. 

So it would appear that the `404` is being thrown in response to my endpoint failing to `return` or `send()` a response w/in `micro`.

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊
