### ISSUE TITLE
npm errors when deploying with react-snapshot dependency

### ISSUE THREAD

**Issue by flybayer** [vercel/vercel#33]
I have a project with these dependencies:

```
  "devDependencies": {
    "history": "4.2.0",
    "react": "15.3.1",
    "react-dom": "15.3.1",
    "react-icons": "2.2.1",
    "react-router": "4.0.0-2",
    "react-scripts": "0.4.1",
    "react-snapshot": "1.0.2"
  },
  "dependencies": {
    "http-server": "0.9.0"
  },
```

When I deploy it, I get many errors in the log when trying to install react-snapshot. **Any suggestions for fixing this?** Thanks!

``` shell
> Deploying ~/c/thefaithnet
> Using Node.js 6.2.1 (default)
> Ready! https://thefaithnet-iegsuatzeo.now.sh (copied to clipboard) [2s]
> Upload [====================] 100% 0.0s
> Sync complete (659B) [1s]
> Initializing…
> Building
> ▲ npm install
> Installing package http-server@0.9.0
> Installing package history@4.2.0
> Installing package react@15.3.1
> Installing package react-dom@15.3.1
> Installing package react-icons@2.2.1
> Installing package react-router@4.0.0-2
> Installing package react-scripts@0.4.1
> Installing package react-snapshot@1.0.2
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp info check checked for "/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/lib/binding/Release/node-v48-linux-x64/fse.node" (not found)
> node-pre-gyp info using node-pre-gyp@0.6.29
> node-pre-gyp info using node@6.2.1 | linux | x64
> node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@6.2.1 (node-v48 ABI) (falling back to source compile with node-gyp)
> node-pre-gyp http Pre-built binary not available for your system, looked for https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v48-linux-x64.tar.gz
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.2.1 | linux | x64
> gyp info ok
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.2.1 | linux | x64
> gyp http GET https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v6.2.1/SHASUMS256.txt
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/.node-gyp/6.2.1/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.2.1',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info ok
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.2.1 | linux | x64
> make: Entering directory '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build'
>   SOLINK_MODULE(target) Release/obj.target/.node
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> gyp info spawn make
>   COPY Release/.node
> make: Leaving directory '/home/nowuser/src/node_modules/09ad3fb161afd3f4b10cb78f85ad7a42d2a25d1f/build'
> gyp info ok
> node-pre-gyp info ok
> ▲ npm run build
```

**Comment by chrisdwheatley** [comment]
I'm not sure those are actually errors you're seeing, I think they may just be information logs.

Is your build failing in any way?

**Comment by flybayer** [comment]
@chrisdwheatley hmm, you may be right. The app works once built but why does this behavior happen? Also, I should have mentioned that it takes a very long time to do `npm install`. Around 5-10 minutes.

**Comment by kblcuk** [comment]
I'm experiencing the same issue with [seneca.js](http://senecajs.org/) -based microservice.
Seems like machine used to run `now` deployments misses some libraries required for compiling native modules. Here is my build output:

``` sh
> Installing package seneca@^3.0.0
> Installing package seneca-balance-client@^0.6.0
> Installing package seneca-mesh@^0.9.0
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.6.0 | linux | x64
> gyp http GET https://nodejs.org/download/release/v6.6.0/node-v6.6.0-headers.tar.gz
> gyp http 200 https://nodejs.org/download/release/v6.6.0/node-v6.6.0-headers.tar.gz
> gyp http GET https://nodejs.org/download/release/v6.6.0/SHASUMS256.txt
> gyp http 200 https://nodejs.org/download/release/v6.6.0/SHASUMS256.txt
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/src/node_modules/72bf8f1cecb1e93ac9d8c19f7cab75495a391811/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '/home/nowuser/.node-gyp/6.6.0/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.6.0',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/72bf8f1cecb1e93ac9d8c19f7cab75495a391811',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> gyp info spawn make
> make: Entering directory '/home/nowuser/src/node_modules/72bf8f1cecb1e93ac9d8c19f7cab75495a391811/build'
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CXX(target) Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o
> ../src/upstream/farmhash-legacy.cc:268:10: fatal error: 'nmmintrin.h' file not found
> #include <nmmintrin.h>
>          ^
> 1 error generated.
> farmhash-legacy.target.mk:103: recipe for target 'Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o' failed
> make: Leaving directory '/home/nowuser/src/node_modules/72bf8f1cecb1e93ac9d8c19f7cab75495a391811/build'
> make: *** [Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 4.6.0-coreos
> gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd /home/nowuser/src/node_modules/72bf8f1cecb1e93ac9d8c19f7cab75495a391811
> gyp ERR! node -v v6.6.0
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> Error: Command node-gyp rebuild ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.3.1
> gyp info using node@6.6.0 | linux | x64
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '-f',
> gyp info spawn args   '/home/nowuser/src/node_modules/be3fce83c59be0aff575ebddf77a349a510e3a5b/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/nowuser/.node-gyp/6.6.0/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/nowuser/.node-gyp/6.6.0',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/nowuser/src/node_modules/be3fce83c59be0aff575ebddf77a349a510e3a5b',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> make: Entering directory '/home/nowuser/src/node_modules/be3fce83c59be0aff575ebddf77a349a510e3a5b/build'
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
>   CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
>   AR(target) Release/obj.target/deps/msgpack/msgpack.a
>   COPY Release/msgpack.a
>   CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
> In file included from ../src/msgpack.cc:9:
> In file included from ../../5e286f4cce742eb75e78290088861a514a5e0fdc/nan.h:50:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/algorithm:62:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/bits/stl_algo.h:66:
> In file included from /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/random:50:
> /usr/bin/../lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../include/c++/5.3.0/x86_64-alpine-linux-musl/bits/opt_random.h:33:10: fatal error: 'x86intrin.h' file not found
> #include <x86intrin.h>
>          ^
> 1 error generated.
> msgpackBinding.target.mk:101: recipe for target 'Release/obj.target/msgpackBinding/src/msgpack.o' failed
> make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
> make: Leaving directory '/home/nowuser/src/node_modules/be3fce83c59be0aff575ebddf77a349a510e3a5b/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Linux 4.6.0-coreos
> gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd /home/nowuser/src/node_modules/be3fce83c59be0aff575ebddf77a349a510e3a5b
> gyp ERR! not ok
> gyp ERR! node -v v6.6.0
> gyp ERR! node-gyp -v v3.3.1
> Error: Command node-gyp rebuild ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by jamo** [comment]
I retested retriggering build for the first one and it builded properly. The UnhandledPromiseRejections can be ignored.

And the header errors from the second log should work not (the headers are present in current build images.)

I'm closing this now, but reopen if the issue still occurs
