### ISSUE TITLE
Python Pipenv is not working

### ISSUE THREAD

**Issue by praecantatio** [vercel/vercel#3317]
Tried with both python 3.6 and 3.7. 

Latest now@16.5.2

now dev gives:

```JavaScript
  message:
   'Command failed: pip3 install --disable-pip-version-check --target . --upgrade werkzeug\nTraceback (most recent call last):\n  File "/usr/bin/pip3", line 9, in <module>\n    from pip import main\nImportError: cannot import name \'main\'\n',
  code: 1,
  stdout: '',
  stderr:
   'Traceback (most recent call last):\n  File "/usr/bin/pip3", line 9, in <module>\n    from pip import main\nImportError: cannot import name \'main\'\n',
  failed: true,
  signal: null,
  cmd:
   'pip3 install --disable-pip-version-check --target . --upgrade werkzeug',
  timedOut: false,
  killed: false }
> [debug] [2019-11-15T05:48:56.943Z] Error: Command failed: pip3 install --disable-pip-version-check --target . --upgrade werkzeug
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

```

Pipfile:
```Python
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"

[requires]
python_version = "3.6"
```

**Comment by Immortalin** [comment]
This is with the Flask example from the docs

**Comment by praecantatio** [comment]
This is with the Flask example from the docs.

**Comment by styfle** [comment]
Hi @praecantatio 

Which version of `pip3` do you have installed?

Can you try updating to the latest with `pip3 install --upgrade pip`?

**Comment by praecantatio** [comment]
`pip 19.3.1`

The problem is that Zeit now is not using the interpreter of the virtualenv (created by Pipenv) that it is in.

**Comment by praecantatio** [comment]
Fixed
```
sudo -H pip3 install --upgrade pip
sudo -H pip2 install --upgrade pip
```
