### ISSUE TITLE
[now dev] can't start properly on CI

### ISSUE THREAD

**Issue by N0xFF** [vercel/vercel#3345]
Now CLI 16.6.0.

On CI when I run `now dev` I got an error and server never available on `3000` port.

Actual:

```
> Error! Builder exited with 0 before sending build result
> [debug] [2019-11-22T16:29:45.441Z] Error: Builder exited with 0 before sending build result
    at ChildProcess.onExit (/usr/local/share/.config/yarn/global/node_modules/now/dist/index.js:2:3424969)
    at ChildProcess.emit (events.js:215:7)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

Expected:

```
> Ready! Available at http://localhost:3000
```

<details>
<summary>Verbose log</summary>

```
> [debug] [2019-11-22T16:29:34.649Z] Found config in file /home/circleci/app/now.json
> [debug] [2019-11-22T16:29:34.765Z] Using Now CLI 16.6.0
> [debug] [2019-11-22T16:29:34.768Z] user supplied known subcommand
> Now CLI 16.6.0 dev (beta) — https://zeit.co/feedback/dev
> [debug] [2019-11-22T16:29:35.873Z] Creating directory /home/circleci/.cache/co.zeit.now/dev/builders
> [debug] [2019-11-22T16:29:35.873Z] Finished creating /home/circleci/.cache/co.zeit.now/dev/builders
> [debug] [2019-11-22T16:29:35.874Z] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.17.3/yarn-1.17.3.js
> [debug] [2019-11-22T16:29:36.170Z] Finished downloading yarn /home/circleci/.cache/co.zeit.now/dev/builders/yarn
> [debug] [2019-11-22T16:29:36.171Z] Making the yarn binary executable
> [debug] [2019-11-22T16:29:36.171Z] Finished making the yarn binary executable
> [debug] [2019-11-22T16:29:36.173Z] Reading `package.json` file
> [debug] [2019-11-22T16:29:36.174Z] Reading `now.json` file
> [debug] [2019-11-22T16:29:36.174Z] Searching files inside of /home/circleci/app/
> [debug] [2019-11-22T16:29:38.612Z] Found 34408 and filtered out 34265 files
> [debug] [2019-11-22T16:29:38.617Z] Locating files /home/circleci/app
> [debug] [2019-11-22T16:29:38.617Z] Ignoring /home/circleci/app/.circleci
> [debug] [2019-11-22T16:29:38.617Z] Ignoring /home/circleci/app/.git
> [debug] [2019-11-22T16:29:38.617Z] Ignoring /home/circleci/app/.gitignore
> [debug] [2019-11-22T16:29:38.617Z] Ignoring /home/circleci/app/node_modules
> [debug] [2019-11-22T16:29:38.623Z] Locating files /home/circleci/app: 6.064ms
> [debug] [2019-11-22T16:29:38.635Z] No builders need to be installed
> [debug] [2019-11-22T16:29:38.725Z] Adding build match for "next.config.js"
> Creating initial build
> Building @now/next:next.config.js
> [debug] [2019-11-22T16:29:38.727Z] Using `@now/next@2.0.0`
> [debug] [2019-11-22T16:29:38.727Z] Creating build process for next.config.js
[@now/next] Downloading user files...
missing `engines` in `package.json`, using default range: 8.10.x
[@now/next] Installing dependencies...
Skipping dependency installation because dev mode is enabled
The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated
> Using external babel configuration
> Location: "/home/circleci/app/.babelrc"
> [debug] [2019-11-22T16:29:44.646Z] Builder "@now/build-utils" updated to version `1.1.0`
> [debug] [2019-11-22T16:29:44.646Z] Builder "@now/next" updated to version `2.1.0`
> [debug] [2019-11-22T16:29:44.647Z] Purging require cache for "/home/circleci/.cache/co.zeit.now/dev/builders/node_modules/@now/next/dist/index.js"
> [debug] [2019-11-22T16:29:44.647Z] Purging require cache for "/home/circleci/.cache/co.zeit.now/dev/builders/node_modules/@now/next/package.json"
> [debug] [2019-11-22T16:29:44.647Z] Killing builder sub-process with PID 2658
> [debug] [2019-11-22T16:29:44.665Z] Invalidated build match for "next.config.js"
> [debug] [2019-11-22T16:29:44.779Z] Adding build match for "next.config.js"
> Building @now/next:next.config.js
> [debug] [2019-11-22T16:29:44.779Z] Using `@now/next@2.1.0`
> [debug] [2019-11-22T16:29:44.779Z] Creating build process for next.config.js
> [debug] [2019-11-22T16:29:44.801Z] Killed builder with PID 2658
> [debug] [2019-11-22T16:29:44.804Z] Build process for next.config.js exited with 0
> Error! Builder exited with 0 before sending build result
> [debug] [2019-11-22T16:29:45.441Z] Error: Builder exited with 0 before sending build result
    at ChildProcess.onExit (/usr/local/share/.config/yarn/global/node_modules/now/dist/index.js:2:3424969)
    at ChildProcess.emit (events.js:215:7)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[@now/next] Downloading user files...
Missing `engines` in `package.json`, using default range: 8.10.x
[@now/next] Installing dependencies...
Skipping dependency installation because dev mode is enabled
The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated
> Using external babel configuration
> Location: "/home/circleci/app/.babelrc"
[ ready ] compiled successfully
[ wait ]  compiling ...
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

[@now/next] Development server for next.config.js running at http://localhost:5000
> Built @now/next:next.config.js [8s]
[ ready ] compiled successfully
```

</details>

**Comment by styfle** [comment]
Hi @N0xFF 

Can you share the output when you run `now --debug -b NOW_BUILDER_DEBUG=1`?

**Comment by N0xFF** [comment]
After investigation, I achieve the same error on local machine.

How to reproduce:

1. Remove cache.
```bash
rm -rf ~/Library/Caches/co.zeit.now
```

2. Run `now dev`.
<details>
<summary>Verbose log</summary>

```
MacBook-Air:XXX Maxim$ now dev --debug
> [debug] [2019-12-12T22:00:39.214Z] Found config in file /Users/Maxim/Projects/Ruby/XXX/now.json
> [debug] [2019-12-12T22:00:39.279Z] Using Now CLI 16.6.3
> [debug] [2019-12-12T22:00:39.283Z] user supplied known subcommand
> Now CLI 16.6.3 dev (beta) — https://zeit.co/feedback/dev
> [debug] [2019-12-12T22:00:41.956Z] Creating directory /Users/Maxim/Library/Caches/co.zeit.now/dev/builders
> [debug] [2019-12-12T22:00:41.967Z] Finished creating /Users/Maxim/Library/Caches/co.zeit.now/dev/builders
> [debug] [2019-12-12T22:00:41.970Z] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.17.3/yarn-1.17.3.js
> [debug] [2019-12-12T22:00:52.376Z] Finished downloading yarn /Users/Maxim/Library/Caches/co.zeit.now/dev/builders/yarn
> [debug] [2019-12-12T22:00:52.399Z] Making the yarn binary executable
> [debug] [2019-12-12T22:00:52.399Z] Finished making the yarn binary executable
> [debug] [2019-12-12T22:00:52.442Z] Reading `package.json` file
> [debug] [2019-12-12T22:00:52.443Z] Reading `now.json` file
> [debug] [2019-12-12T22:00:52.444Z] Searching files inside of /Users/Maxim/Projects/Ruby/XXX/
> [debug] [2019-12-12T22:01:01.043Z] Found 32876 and filtered out 32723 files
> [debug] [2019-12-12T22:01:01.073Z] Using local env: /Users/Maxim/Projects/Ruby/XXX/.env.build
> [debug] [2019-12-12T22:01:01.078Z] Locating files /Users/Maxim/Projects/Ruby/XXX
> [debug] [2019-12-12T22:01:01.080Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/.circleci
> [debug] [2019-12-12T22:01:01.080Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/.env.build
> [debug] [2019-12-12T22:01:01.081Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/.git
> [debug] [2019-12-12T22:01:01.081Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/.gitignore
> [debug] [2019-12-12T22:01:01.082Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/.next
> [debug] [2019-12-12T22:01:01.083Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/node_modules
> [debug] [2019-12-12T22:01:01.089Z] Ignoring /Users/Maxim/Projects/Ruby/XXX/cypress/.DS_Store
> [debug] [2019-12-12T22:01:01.124Z] Locating files /Users/Maxim/Projects/Ruby/XXX: 44.521ms
> [debug] [2019-12-12T22:01:01.170Z] No builders need to be installed
> [debug] [2019-12-12T22:01:01.426Z] Adding build match for "next.config.js"
> Creating initial build
> Building @now/next:next.config.js
> [debug] [2019-12-12T22:01:01.435Z] Using `@now/next@2.1.0`
> [debug] [2019-12-12T22:01:01.436Z] Creating build process for next.config.js
The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated
> [debug] [2019-12-12T22:01:13.784Z] Builder "@now/build-utils" updated to version `1.1.1`
> [debug] [2019-12-12T22:01:13.784Z] Builder "@now/next" updated to version `2.1.1`
> [debug] [2019-12-12T22:01:13.805Z] Purging require cache for "/Users/Maxim/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/dist/index.js"
> [debug] [2019-12-12T22:01:13.805Z] Purging require cache for "/Users/Maxim/Library/Caches/co.zeit.now/dev/builders/node_modules/@now/next/package.json"
> [debug] [2019-12-12T22:01:13.806Z] Killing builder sub-process with PID 10432
> [debug] [2019-12-12T22:01:13.869Z] Invalidated build match for "next.config.js"
> [debug] [2019-12-12T22:01:14.367Z] Adding build match for "next.config.js"
> Building @now/next:next.config.js
> [debug] [2019-12-12T22:01:14.370Z] Using `@now/next@2.1.1`
> [debug] [2019-12-12T22:01:14.370Z] Creating build process for next.config.js
> [debug] [2019-12-12T22:01:14.454Z] Killed builder with PID 10432
> [debug] [2019-12-12T22:01:14.456Z] Build process for next.config.js exited with 0
> Error! Builder exited with 0 before sending build result
> [debug] [2019-12-12T22:01:15.920Z] Error: Builder exited with 0 before sending build result
    at ChildProcess.onExit (/Users/Maxim/.config/yarn/global/node_modules/now/dist/index.js:2:3427849)
    at ChildProcess.emit (events.js:215:7)
    at ChildProcess.EventEmitter.emit (domain.js:478:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated
> Using external babel configuration
> Location: "/Users/Maxim/Projects/Ruby/XXX/.babelrc"
[ ready ] compiled successfully
[ wait ]  compiling ...
> Built @now/next:next.config.js [27s]
[ ready ] compiled successfully
```

</details>

Error occurs when built-in packages need to be updated. Like `@now/build-utils` and `@now/next` in example above. Because when I run `now dev` for the second time (when these packages already updated), server runs on 3000 port without any problem.

Now I ran `now --debug -b NOW_BUILDER_DEBUG=1` as you suggested. It executed without any problem. But I think I can't share output because it contains sensitive information.

**Comment by zfoster** [comment]
I have the same issue in CI

**Comment by N0xFF** [comment]
Workaround part of CircleCI config:

```yml
- run:
    name: 'React: Start server to install dependencies'
    command: now dev --debug
    background: true
- run:
    name: 'React: Kill server'
    command: sleep 60 && pkill -f now
- run:
    name: 'React: Start server'
    command: now dev
    background: true
```
