### ISSUE TITLE
Error: Cannot find module '@babel/plugin-transform-runtime' from '/zeit/5fdc1c32'

### ISSUE THREAD

**Issue by cyrus-za** [vercel/vercel#3479]
Related to #1674 

It works fine running `next` or `next build` locally. It even works fine with `now dev` but as soon as I run `now` it seems to not have the devDependencies available on the server. 

logs
```
019-12-30T07:04:56.493Z  Downloading 1238 deployment files...
2019-12-30T07:05:06.128Z  Installing build runtime...
2019-12-30T07:05:06.130Z  yarn info @now/build-utils@latest...
2019-12-30T07:05:06.134Z  yarn info @now/next...
2019-12-30T07:05:06.725Z  Build runtime installed: 597.259ms
2019-12-30T07:05:07.234Z  Looking up build cache...
2019-12-30T07:05:07.777Z  Running builder.exports.build...
2019-12-30T07:05:07.788Z  Installing dependencies...
2019-12-30T07:05:08.050Z  yarn install v1.17.3
2019-12-30T07:05:08.149Z  [1/4] Resolving packages...
2019-12-30T07:05:08.702Z  [2/4] Fetching packages...
2019-12-30T07:05:37.654Z  info fsevents@2.1.2: The platform "linux" is incompatible with this module.
2019-12-30T07:05:37.654Z  info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
2019-12-30T07:05:37.655Z  info fsevents@1.2.11: The platform "linux" is incompatible with this module.
2019-12-30T07:05:37.655Z  info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
2019-12-30T07:05:37.656Z  [3/4] Linking dependencies...
2019-12-30T07:05:37.663Z  warning "@zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
2019-12-30T07:05:37.663Z  warning "@zeit/next-css > mini-css-extract-plugin@0.4.3" has unmet peer dependency "webpack@^4.4.0".
2019-12-30T07:05:37.664Z  warning "@zeit/next-sass > sass-loader@6.0.6" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
2019-12-30T07:05:37.666Z  warning "next > native-url@0.2.3" has unmet peer dependency "@types/node@>=8.0.0".
2019-12-30T07:05:37.669Z  warning "next-images > file-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0".
2019-12-30T07:05:37.669Z  warning "next-images > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
2019-12-30T07:05:37.677Z  warning " > file-loader@5.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
2019-12-30T07:05:54.991Z  [4/4] Building fresh packages...
2019-12-30T07:05:57.048Z  Done in 49.00s.
2019-12-30T07:05:57.082Z  Running "yarn run now-build"
2019-12-30T07:05:57.327Z  yarn run v1.17.3
2019-12-30T07:05:57.365Z  $ next build
2019-12-30T07:05:57.894Z  Creating an optimized production build...
2019-12-30T07:05:57.942Z  Attention: Next.js now collects completely anonymous telemetry regarding usage.
2019-12-30T07:05:57.942Z  This information is used to shape Next.js' roadmap and prioritize features.
2019-12-30T07:05:57.942Z  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2019-12-30T07:05:57.942Z  https://nextjs.org/telemetry
2019-12-30T07:05:57.943Z  
2019-12-30T07:05:58.815Z  
2019-12-30T07:05:58.816Z  Failed to compile.
2019-12-30T07:05:58.816Z  
2019-12-30T07:05:58.817Z  ./node_modules/next/dist/client/next.js
2019-12-30T07:05:58.817Z  Error: Cannot find module '@babel/plugin-transform-runtime' from '/zeit/5fdc1c32'
2019-12-30T07:05:58.817Z      at Array.map (<anonymous>)
2019-12-30T07:05:58.817Z  
2019-12-30T07:05:58.817Z  > Build error occurred
2019-12-30T07:05:58.818Z  Error: > Build failed because of webpack errors
2019-12-30T07:05:58.818Z      at build (/zeit/5fdc1c32/node_modules/next/dist/build/index.js:9:900)
2019-12-30T07:05:58.836Z  error Command failed with exit code 1.
2019-12-30T07:05:58.836Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2019-12-30T07:05:58.851Z  Error: Exited with 1
2019-12-30T07:05:58.851Z      at ChildProcess.child.on (/zeit/7da5d4576aaa60c9/.build-utils/.builder/node_modules/@now/next/dist/index.js:48339:24)
2019-12-30T07:05:58.851Z      at emitTwo (events.js:126:13)
2019-12-30T07:05:58.851Z      at ChildProcess.emit (events.js:214:7)
2019-12-30T07:05:58.852Z      at maybeClose (internal/child_process.js:925:16)
2019-12-30T07:05:58.852Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2019-12-30T07:05:58.992Z  worker exited with code 20 and signal null
2019-12-30T07:06:01.382Z  done
```

.babelrc
```json
{
  "presets": [
    ["@babel/preset-env", { "targets": { "browsers": ["last 2 Chrome versions"] } }],
    "next/babel"
  ],
  "plugins": [
    "@babel/plugin-transform-runtime",
    ["styled-components", { "ssr": true, "displayName": true, "preprocess": false }]
  ]
}
```

package.json (removed some scripts for cleaner reading)
```json
{
  "engines": {
    "node": ">=12",
    "yarn": "1.x"
  },
  "cacheDirectories": [
    "node_modules",
    ".cache",
    "dist"
  ],
  "scripts": {
    "build": "graphql-codegen && next build",
    "start": "next start -p $PORT",
    "now-build": "next build"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.4.2",
    "@babel/preset-react": "^7.0.0",
    "@babel/runtime": "^7.4.2",
    "@graphql-codegen/cli": "^1.7.0",
    "@graphql-codegen/typescript": "^1.7.0",
    "@graphql-codegen/typescript-operations": "^1.7.0",
    "@graphql-codegen/typescript-react-apollo": "^1.7.0",
    "@gunar/unite": "^1.2.3",
    "@types/auth0-js": "^8.11.11",
    "@types/chart.js": "^2.7.50",
    "@types/common-tags": "^1.8.0",
    "@types/enzyme": "^3.9.1",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/jest": "^24.0.11",
    "@types/js-cookie": "^2.2.2",
    "@types/jsonwebtoken": "^8.3.2",
    "@types/lodash": "^4.14.134",
    "@types/moment-timezone": "^0.5.12",
    "@types/pify": "^3.0.2",
    "@types/react-document-title": "^2.0.3",
    "@types/react-infinite-scroller": "^1.2.1",
    "@types/react-stripe-elements": "^1.1.10",
    "@types/sass": "^1.16.0",
    "@types/superagent": "^4.1.1",
    "@typescript-eslint/eslint-plugin": "^1.13.0",
    "@typescript-eslint/parser": "^1.13.0",
    "babel-core": "^7.0.0-0",
    "babel-jest": "^24.5.0",
    "babel-plugin-styled-components": "^1.10.6",
    "babel-preset-es2015": "^6.24.1",
    "enzyme": "^3.9.0",
    "enzyme-adapter-react-16": "^1.11.2",
    "enzyme-to-json": "^3.3.5",
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "eslint-plugin-simple-import-sort": "^4.0.0",
    "file-loader": "^5.0.2",
    "jest": "^24.5.0",
    "jest-haste-map": "^24.5.0",
    "jest-resolve": "^24.5.0",
    "lint-staged": "^9.2.5",
    "now": "^16.7.0",
    "prettier": "^1.19.1",
    "pretty-quick": "^1.11.1",
    "ts-jest": "^24.0.0",
    "tsc-watch": "^3.0.0",
    "typescript": "^3.7"
  },
  "dependencies": {
    "@apollo/react-components": "^3.1.3",
    "@apollo/react-hoc": "^3.1.3",
    "@apollo/react-hooks": "^3.1.3",
    "@auth0/nextjs-auth0": "^0.7.0",
    "@bugsnag/js": "^6.2.0",
    "@bugsnag/plugin-react": "^6.2.0",
    "@invisible/ui": "1.9.1",
    "@material-ui/core": "^4.8.0",
    "@material-ui/icons": "^3.0.2",
    "@segment/consent-manager": "^1.3.0",
    "@segment/in-eu": "^0.2.1",
    "@segment/snippet": "^4.4.0",
    "@types/moment-duration-format": "^2.2.2",
    "@types/react": "^16.8.0",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "apollo-cache": "^1.3.2",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "apollo-link-batch-http": "^1.2.13",
    "apollo-link-error": "^1.1.12",
    "apollo-utilities": "^1.3.2",
    "chart.js": "^2.8.0",
    "clsx": "^1.0.4",
    "common-tags": "^1.8.0",
    "depcheck": "^0.8.3",
    "email-validator": "^2.0.4",
    "env-var": "^3.5.0",
    "express": "^4.16.4",
    "express-env": "^1.0.2",
    "graphql": "^14.3.1",
    "graphql-tag": "^2.10.1",
    "isomorphic-unfetch": "^3.0.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.11",
    "moment-duration-format": "^2.3.2",
    "moment-timezone": "^0.5.23",
    "next": "^9.1.5",
    "next-images": "^1.2.0",
    "node-sass": "^4.13.0",
    "query-string": "^6.4.2",
    "react": "^16.12.0",
    "react-apollo": "^3.1.1",
    "react-chartkick": "^0.3.0",
    "react-date-range": "^1.0.0-beta",
    "react-dom": "^16.12.0",
    "react-icons": "^3.7.0",
    "react-infinite-scroller": "^1.2.4",
    "react-stripe-elements": "^2.0.3",
    "react-toastify": "^5.3.2",
    "regenerator": "^0.13.3",
    "sass": "^1.17.3",
    "string-sanitizer": "^1.0.0",
    "superagent": "^5.0.2"
  }
}

```

now.json
```json
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@now/next"
    }
  ],
  "build": {
    "env": {
      "NPM_TOKEN": "@npm-token",
    }
  }
}

```

**Comment by mcsdevv** [comment]
Hey @cyrus-za, apologies for the delayed response, are you still experiencing this issue?

**Comment by cyrus-za** [comment]
I can't even remember if I had to do a workaround or if I found a fix. But no, I dont think any project will last if this issue is still being experienced 5 months later :)

**Comment by mcsdevv** [comment]
Thanks for confirming, sorry again for the delay. For reference, the best place to get help would either be Discussion or [Vercel Support](vercel.com/support/request).

**Comment by cyrus-za** [comment]
I have now run into this same error with a new project and new set of dependencies. https://github.com/vercel/next.js/issues/13736

**Comment by olaven** [comment]
Hi! Experiencing something similar. 
Getting the following error on Vercel, but not locally: 

2020-06-15T18:02:17.320Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'next/dist/next-server/server/api-utils'\nRequire stack:\n- /var/task/.next/serverless/pages/api/auth/me.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'next/dist/next-server/server/api-utils'","Require stack:","- /var/task/.next/serverless/pages/api/auth/me.js","- /var/task/now__launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function.Module._load (internal/modules/cjs/loader.js:877:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)","    at internal/main/run_main_module.js:18:47"]}Unknown application error occurredRuntime.ImportModuleError
