### ISSUE TITLE
Can't use Sequelize

### ISSUE THREAD

**Issue by michalsanger** [vercel/vercel#349]
I would like to connect to PostgreSQL with Sequelize but I get `Cannot find module './dialects/mysql/data-types` on Now. This works on localhost:

`index.js`:
```
const Sequelize = require('sequelize');

module.exports = async (req, res) => {
  const db = new Sequelize('intents', process.env.DB_USER, process.env.DB_PASSWORD, {
    host: process.env.DB_HOST,
    dialect: 'postgres',
  });
  return 'Ready!';
}
```

deps:
```
  "dependencies": {
    "micro": "^7.0.6",
    "pg": "^6.1.2",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.30.2"
  }
```

Start script:
`"now-start": "micro index.js"`

Error on start:
```
> micro: Error when importing /home/nowuser/src/index.js: Error: Cannot find module './dialects/mysql/data-types'
>     at Function.Module._resolveFilename (module.js:472:15)
>     at Function.Module._load (module.js:420:25)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/sequelize/lib/data-types.js:988:19)
>     at Module._compile (module.js:573:32)
>     at Module._extensions..js (module.js:582:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/async-to-gen/register.js:42:5)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/sequelize/lib/utils.js:3:17)
>     at Module._compile (module.js:573:32)
>     at Module._extensions..js (module.js:582:10)
```

**Comment by TooTallNate** [comment]
Flushed the cache on that package on our backend. Can you try deploying again?

**Comment by michalsanger** [comment]
It's working. Thanks!

**Comment by matheuss** [comment]
🎉
