### ISSUE TITLE
git integrations deployment fail

### ISSUE THREAD

**Issue by mmaedel** [vercel/vercel#3526]
hello
deployment fails with the following since yesterday...

Downloading 30 deployment files...
Installing build runtime...
Build runtime installed: 6652.495ms
Looking up build cache...
Installing build runtime...
Build runtime installed: 556.619ms
Looking up build cache...
Installing build runtime...
Build runtime installed: 679.375ms
Looking up build cache...
Installing build runtime...
Build runtime installed: 624.159ms
Installing build runtime...
Looking up build cache...
Build runtime installed: 736.966ms
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/66e2d69e/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/66e2d69e/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/4d077ce0/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/4d077ce0/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 900.908ms
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/10c397a3/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/10c397a3/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Installing build runtime...
Looking up build cache...
Build runtime installed: 777.694ms
Looking up build cache...
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/3b668215/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/3b668215/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 643.492ms
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/2db7d5af/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/2db7d5af/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Looking up build cache...
Installing build runtime...
Build runtime installed: 691.189ms
Looking up build cache...
Installing build runtime...
Build runtime installed: 832.747ms
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/4cbd55f9/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/4cbd55f9/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/67398e7a/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/67398e7a/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 894.857ms
Looking up build cache...
Installing build runtime...
Build runtime installed: 1134.512ms
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/5ae2e6e2/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/5ae2e6e2/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Looking up build cache...
Installing build runtime...
Failed to `go get`
Build runtime installed: 873.513ms
{ Error: Command failed: go get
# cd /tmp/d24a8ac/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/d24a8ac/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Looking up build cache...
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/7ffc4211/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/7ffc4211/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 837.004ms
Installing build runtime...
Looking up build cache...
Build runtime installed: 740.859ms
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/119de112/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/119de112/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/2a894c94/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/2a894c94/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 967.470ms
Looking up build cache...
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/35d4bcd2/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/35d4bcd2/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 1178.113ms
Installing build runtime...
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/46725fbf/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/46725fbf/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
Build runtime installed: 921.164ms
done
Looking up build cache...
Installing build runtime...
Build runtime installed: 759.998ms
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/37ba77b3/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/37ba77b3/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Looking up build cache...
Installing build runtime...
Build runtime installed: 867.698ms
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/5e7cae90/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/5e7cae90/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/5c169c03/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/5c169c03/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 884.146ms
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/58dba8d9/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/58dba8d9/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Looking up build cache...
Build runtime installed: 883.495ms
Installing build runtime...
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/409e3521/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/409e3521/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Build runtime installed: 1054.613ms
Looking up build cache...
Installing build runtime...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/62a457f3/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/62a457f3/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
Build runtime installed: 716.579ms
worker exited with code 20 and signal null
done
Looking up build cache...
Installing build runtime...
Build runtime installed: 859.524ms
Looking up build cache...
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/508d0cd8/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/508d0cd8/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/3efbc43d/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/3efbc43d/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/24b26fa8/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/24b26fa8/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/3aaae35/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/3aaae35/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
Failed to `go get`
{ Error: Command failed: go get
# cd /tmp/59ad27b0/src/github.com/zeit/now; git submodule update --init --recursive
fatal: No url found for submodule path 'examples/ember' in .gitmodules
package github.com/zeit/now/utils/go/bridge: exit status 128

    at makeError (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:48947:9)
    at Promise.all.then.arr (/zeit/616a724c66b8499e/.build-utils/.builder/node_modules/@now/go/dist/index.js:49051:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: '',
  stderr: '# cd /tmp/59ad27b0/src/github.com/zeit/now; git submodule update --init --recursive\nfatal: No url found for submodule path \'examples/ember\' in .gitmodules\npackage github.com/zeit/now/utils/go/bridge: exit status 128\n',
  failed: true,
  signal: null,
  cmd: 'go get',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
done

**Comment by mmaedel** [comment]
hello again

still not working with redeploy...

i just tried to redeploy last working version/commit... but aggregates similar err as above ....?!

asking for info/help please

regards 
Matthias

**Comment by mmaedel** [comment]
all Ok now...

Thanx

**Comment by ng-parth** [comment]
hi @mmaedel 
What was your exact issue and how did you fixed it? 

My issue is, 
I am a react project created using CRA. It was working fine and deployment was great using **now** until recently. 
I recently moved some of my services into a git submodule to reuse onto other projects. 
And since then, I am unable to figure out how to build and deploy it using now. 

Initially, with default build command, it said `Cannot find module: XXXX Make sure this package is installed.`
After that, I updated the build command to `git submodule update --init --recursive; npm run build` but it is still failing with following error: `fatal: not a git repository (or any of the parent directories): .git`

If needed, I can post my build logs here.

**Comment by Spaceface16518** [comment]
@ng-parth I just filed a ticket with and issue about git submodules in regards to the [Hugo Guide](https://vercel.com/guides/deploying-hugo-with-vercel). They said that there is a known issue about this, and that they'll update it soon. They also mentioned that it was working through the CLI but not through Git Integration. Unless it would mess something up, you could try deploying manually through the CLI, to a non-production environment.
