### ISSUE TITLE
Next.js dev server gets stuck after a while, requests just spin 

### ISSUE THREAD

**Issue by jeantil** [vercel/vercel#3612]
Moved from zeit/next.js#10061

Describe the bug
====
When I run my Next.js app with now dev, after a while (on the order of minutes, definitely less than an hour) my requests to it will stop working.

How to reproduce
====

The original reporter provided this: 
> I'm not sure how to isolate this one. It happens all the time with this project https://github.com/mjm/courier-js but it's not an easy thing to get running for reproduction.

> Run `now dev`
> Work on the app, making changes to files, saving, and watching them hot reload in the browser
> Eventually, one of these changes will try to reload and will get stuck. The on-page indicator for a page compiling will be there and keep spinning continuously. Trying to refresh the page just causes the browser to try to load the page until it times out.
> When I give up, I can hit Ctrl-C to try to kill the server, but if it's in this state, it can take a minute or two to actually get the message and quit.

I encounter the same issue on a different private repo. Changing even css in styled-jsx can block the server. Since `ctrl+c` is so slow to answer I `ctrl+z` then `kill -9 %1` then restart `now dev`

Expected behavior
====
Continuing to make changes should keep working and trigger refreshes in the browser.

System information
====
original reporter's
> OS: macOS Catalina, though I think this happened before upgrading too
> Browser (if applies): I've seen in both Chrome and Safari
> Version of Next.js: 9.1.7, has happened in earlier versions of Next 9 as well
> Version of Now CLI: 16.7.3

>OS: Ubuntu 19.10
>Browser: both chrome and firefox trigger the issue
> Version of Next.js : 9.1.6, 9.1.7,9.2.0
> Version of Now cli : 16.7.3 

the problem has started since we upgraded to next.js 9

Additional context
==== 
The issue disappears if we run `next dev` directly.

**Comment by mjm** [comment]
I think my experience lines up with yours. I was able to adjust my app enough to run correctly outside `now dev` and just run `npx next dev`, and while I haven't had a lot of time to test it, I haven't seen the issue yet.

@jeantil does your project use TypeScript or just JavaScript? wondering if it has anything to do with it.

**Comment by jeantil** [comment]
Our project is a mono repo which uses a mix of typescript (for modules and backend services in a separate express app) and javascript (for the next.js app) we don't use the next `api/` folder because we use firebase for storage and connecting to firebase makes lambda startup really slow.

**Comment by mjm** [comment]
I’ve been working with just `next dev` instead of `now dev` for the last week, and haven’t seen this issue in that time, so I’m pretty convinced this is an issue in Now specifically.

**Comment by PierBover** [comment]
I'm seeing this in Firefox on macOS with an Eleventy + API project. Not on Chromium-based browsers though.

**Comment by jeantil** [comment]
I'm seeing this with both chrome and Firefox on linux

Le dim. 9 févr. 2020 à 19:36, Pier Bover <notifications@github.com> a
écrit :

**Comment by MatteoGioioso** [comment]
Same issue here, sometimes I try to manually reload and get stuck forever.

**Comment by andyWynyard** [comment]
Yep, I'm getting this too. Usually happens when I break something. Cant `ctrl C` neither.

**Comment by happylinks** [comment]
Also getting this consistently at least once every hour. Not sure what I can check to see what's up.

**Comment by Vadorequest** [comment]
Also experienced this. Using TypeScript.

Usually, what happens is the request hangs, I kill the server (ctrl+c) and start it again. Sometimes, the server start under 8889 instead of 8888 because some process still run under 8888.

**Comment by mcsdevv** [comment]
For those still experiencing this issue, can you share with me your use case for using `now dev` rather than `next dev`? We are currently working on a series of improvements for `now dev`.

**Comment by happylinks** [comment]
@mcsdevv Ok so I just realised because of your post that I actually don't need now dev anymore and can use next dev. At the start I wasn't using nextjs yet, so relied on now to start my serverless functions. But I recently migrated to next and forgot that next dev also runs the serverless functions in that case. So thanks for that!

**Comment by bsideup** [comment]
@mcsdevv 
1. followed the docs for Zeit Functions saying that I should use `now dev`
2. I am developing a SPA, not a website, and I don't think I have a use case for NextJS

**Comment by Vadorequest** [comment]
@mcsdevv I don't exactly remember why I use `now dev` in favour of `next start`.

But running `next start --help` states that it's running under `production` mode, it doesn't seem to be meant to be used for development. Or is it outdated/misleading?

```sh
 next start --help

      Description
        Starts the application in production mode.
        The application should be compiled with `next build` first.

      Usage
        $ next start <dir> -p <port>

      <dir> represents the directory of the Next.js application.
      If no directory is provided, the current directory will be used.

      Options
        --port, -p      A port number on which to start the application
        --hostname, -H  Hostname on which to start the application
        --help, -h      Displays this message

```

If I run `next start`, the app crashes immediately:

```sh
next start
Building Next with NODE_ENV="production" APP_STAGE="undefined" for CUSTOMER_REF="undefined"
Warning: You have enabled experimental feature(s).
Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Error: Could not find a valid build in the '/Users/vadorequest/dev/next-right-now/.next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/next-server.js:971:23)
    at new Server (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/next-server/server/next-server.js:64:29)
    at createServer (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/next.js:2:133)
    at start (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/server/lib/start-server.js:1:323)
    at nextStart (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/cli/next-start.js:20:125)
    at /Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next:28:339

```

Also, it doesn't seem to read my `.env.build` file, unlike what `now dev` does.
Also, here is how I start the server in debug mode:
`node_modules/cross-env/src/bin/cross-env-shell.js 'npx concurrently -p '{name}' -n 'debugger,now-cli' -c 'gray.bgWhite,yellow.bgBlue' \"node --inspect-brk node_modules/.bin/now\" \"yarn start\"'`

With `yarn start` running `now dev --listen 8888`.

I believe I can't start Next.js in debug (breakpoint, step by step) mode without using now dev. Or I don't know how.

Overall, I have very little understanding between what both CLI are supposed to do. I just know that `next start` doesn't work, while `now dev` does.

---
**Edit**: I noticed you meant `next dev` vs `now dev`.

```sh
next dev
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
Building Next with NODE_ENV="development" APP_STAGE="undefined" for CUSTOMER_REF="undefined"
Warning: You have enabled experimental feature(s).
Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

[webpack] Building release "1.0.1_development"
[ info ]  bundled successfully, waiting for typecheck results...
[ ready ] compiled successfully - ready on http://localhost:3000

```

It doesn't seem to read my `.env.build` file, unlike what `now dev` does.

**Comment by jeantil** [comment]
> For those still experiencing this issue, can you share with me your use case for using now dev rather than next dev? We are currently working on a series of improvements for now dev.

we use now dev instead of just next dev because we have separate backend api project which is deployed along with the nextjs app and now dev builds and runs both, while nextjs only runs the js parts.

**Comment by PierBover** [comment]
In my use case I simply didn't use Next. My cloud functions were pure Node code for API endpoints and my front end was not using React either.

**Comment by nhuesmann** [comment]
I am not using Next.js, but am using Now for a serverless backend. `now dev` **always** becomes unresponsive after a time—could be 20 minutes, could be 45 minutes, but it always eventually stops responding. At that point, ctrl + c takes forever to actual stop the server (minutes). I am using TypeScript & yarn workspaces in a monorepo.

**Comment by leo** [comment]
@nhuesmann Thank you for sharing this report! Would you mind elaborating how the source code of the project looks like where you're seeing this problem? I'd love to reproduce it.

If the Git repository is public or you can tell me the name of the project on Vercel, please email me at leo@vercel.com (privately), so that I can dig into it. Thanks!

**Comment by Vadorequest** [comment]
@leo I don't know if you're interested by a Next.js project, but if so we could collaborate on this, I've got an open source project at https://github.com/UnlyEd/next-right-now/tree/v1-hyb-mst-aptd-gcms-lcz-sty

Installation steps are at https://unlyed.github.io/next-right-now/getting-started/quick-start (use branch `v1-hyb-mst-aptd-gcms-lcz-sty`)

You can get in touch directly with me using Discord Vadorequest#3210, if needed.

**Comment by mtford90** [comment]
We've been experiencing this for over a year. I assumed it was just some quirk of our specific setup (we have a custom server with TypeScript) but it's interesting to hear others are having this issue.

Similar symptoms for us - after about an hour, the dev server just stops responding and I have to Ctrl+C and then restart and all is well again.

- Next 9.4.2
- CSS Modules (no styled-jsx)
- A custom server using express
- TypeScript 3.8.3
- Plugins: next-offline, next-images, @zeit/next-source-maps

**Comment by chandu535** [comment]
Did any body got this issue solved?
I'm getting this error in my current project, alothough I've done some more project, but didn't face this issue on those.
Please Give me a confirmation.
