### ISSUE TITLE
Deploying from terminal to Now working, but github integration is failing

### ISSUE THREAD

**Issue by r202-digital** [vercel/vercel#3691]
I have the following web app details:

_package.json_
```
{
  "name": "notjustaboxevents",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "deploy": "now --target production",
    "now-build": "next build"
  },
  "dependencies": {
    "@chakra-ui/core": "^0.4.1",
    "@emotion/core": "^10.0.22",
    "@emotion/styled": "^10.0.23",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "emotion-theming": "^10.0.19",
    "express": "^4.17.1",
    "hygen": "^5.0.3",
    "next": "^9.1.6",
    "next-fonts": "^0.19.0",
    "node-sass": "^4.13.0",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "react-icons": "^3.8.0",
    "react-messenger-customer-chat": "^0.7.2",
    "react-responsive": "^8.0.1",
    "react-slick": "^0.25.2"
  }
}
```

_next.config.js_
```
const withFonts = require("next-fonts");
const withSass = require("@zeit/next-sass");
const withCss = require("@zeit/next-css");

module.exports = withCss(
  withSass(
    withFonts({
      devIndicators: {
        autoPrerender: false
      },
      target: "serverless"
    })
  )
);

```

_now.json_
```
{
  "version": 2,
  "name": "notjustaboxevents",
  "builds": [{ "src": "package.json", "use": "@now/next" }]
}
```

The problem is, whenever I use 
`now --prod` on local, it's all fine.

But when I push to Github, which my project uses as CI, it gives me this problem:
```
[4/4] Building fresh packages...
--
08:00:16 AM | success Saved lockfile.
08:00:16 AM | Done in 14.36s.
08:00:16 AM | Running "yarn run now-build"
08:00:16 AM | yarn run v1.17.3
08:00:16 AM | warning package.json: No license field
08:00:16 AM | $ next build
08:00:16 AM | Creating an optimized production build...
08:00:26 AM | Failed to compile.
08:00:26 AM | ./pages/about.js
08:00:26 AM | Module not found: Can't resolve '../components/Nav' in '/zeit/79b647a8/pages'
08:00:26 AM | > Build error occurred
08:00:26 AM | Error: > Build failed because of webpack errors
08:00:26 AM | at build (/zeit/79b647a8/node_modules/next/dist/build/index.js:10:900)
08:00:26 AM | error Command failed with exit code 1.
08:00:26 AM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:00:26 AM | Error: Exited with 1
08:00:26 AM | at ChildProcess.child.on (/zeit/8fa4fb30d2598703/.build-utils/.builder/node_modules/@now/next/dist/index.js:47050:24)
08:00:26 AM | at emitTwo (events.js:126:13)
08:00:26 AM | at ChildProcess.emit (events.js:214:7)
08:00:26 AM | at maybeClose (internal/child_process.js:925:16)
08:00:26 AM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
08:00:26 AM | worker exited with code 20 and signal null
08:00:29 AM | done
```

It resolves the Nav components fine from my local device but when Now does it, suddenly it doesn't work. Please help

**Comment by rogerbaockt** [comment]
Same issue here with Next.js git deployment , local device dev motion and now command deployment worked fine , but GitHub deployment failed.

Now CLI 17.0.4
Next.js v9.2.1
```
Failed to compile.
--
04:01:18 PM | ./lib/redux/reducers/currentUser.js
04:01:18 PM | Module not found: Can't resolve '../actionTypes' in '/zeit/6c06e32b/lib/redux/reducers'
04:01:18 PM | > Build error occurred
04:01:18 PM | Error: > Build failed because of webpack errors
04:01:18 PM | at build (/zeit/6c06e32b/node_modules/next/dist/build/index.js:10:900)
04:01:18 PM | error Command failed with exit code 1.
04:01:18 PM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
04:01:18 PM | Error: Exited with 1
04:01:18 PM | at ChildProcess.<anonymous> (/zeit/c18bcb27e1d90ff6/.build-utils/.builder/node_modules/@now/next/dist/index.js:47142:24)
04:01:18 PM | at ChildProcess.emit (events.js:223:5)
04:01:18 PM | at ChildProcess.EventEmitter.emit (domain.js:475:20)
04:01:18 PM | at maybeClose (internal/child_process.js:1021:16)
04:01:18 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
04:01:18 PM | worker exited with code 20 and signal null
04:01:21 PM | Done with "package.json"

```


package.json

```
{
  "name": "abc",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "export": "next export"
  },
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "antd": "^3.9.2",
    "babel-plugin-import": "^1.9.1",
    "braft-editor": "^2.3.8",
    "firebase": "^7.9.0",
    "firebase-admin": "^8.9.2",
    "isomorphic-unfetch": "^3.0.0",
    "next": "latest",
    "now": "^17.0.4",
    "null-loader": "2.0.0",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-firebaseui": "^4.1.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0"
  },
  "license": "ISC"
}

```

next.config.js

```
/* eslint-disable */
const withCss = require("@zeit/next-css");

module.exports = withCss({
  webpack: (config, { isServer }) => {
    if (isServer) {
      const antStyles = /antd\/.*?\/style\/css.*?/;
      const origExternals = [...config.externals];
      config.externals = [
        (context, request, callback) => {
          if (request.match(antStyles)) return callback();
          if (typeof origExternals[0] === "function") {
            origExternals[0](context, request, callback);
          } else {
            callback();
          }
        },
        ...(typeof origExternals[0] === "function" ? [] : origExternals)
      ];

      config.module.rules.unshift({
        test: antStyles,
        use: "null-loader"
      });
    }
    return config;
  }
});
```

**Comment by mcsdevv** [comment]
@r202-digital apologies for the delay in getting in touch here. Are you still experiencing this issue? If so, can you provide a reproducible example, please?

**Comment by styfle** [comment]
The deployments from local CLI and git might be different if you forgot to add/commit a file to git.

The error message  "Module not found: Can't resolve file.js" will tell you which file is missing.

You can probably `git add file.js && git commit -m "add file" && git push` to fix it.
