### ISSUE TITLE
Cannot deploy - Error! queryA EREFUSED api.zeit.co [WINDOWS]

### ISSUE THREAD

**Issue by s-kashif** [vercel/vercel#3756]
On Windows 10
Now CLI 17.0.1
Getting this error while calling now
Error! queryA EREFUSED api.zeit.co

**Comment by Alaboudi1** [comment]
I am also experiencing the same problem after updating to the new CLI? I am using WSL 2 in windows. 

Now CLI 17.0.2
Error! queryA ETIMEOUT api.zeit.co

**Comment by styfle** [comment]
Are you still experiencing this issue? Does it happen every time?

**Comment by vuphan365** [comment]
Still happen :(

**Comment by styfle** [comment]
No, nothing unconventional. Perhaps the issue is related to Anycast:

> Each request to any `api.zeit.co` endpoint, will be automatically resolved to the closest Origin location using Anycast. 

https://zeit.co/docs/api

**Comment by williamluke4** [comment]
Same issue using Now CLI `17.0.4` on Windows

**Comment by styfle** [comment]
If you add the `--debug` flag the you can see each network request.

Maybe that will provide more insight.

**Comment by williamluke4** [comment]
@styfle Here is the output when using `now --debug`
```
C:\Users\willi\Github\PrismaFlow>now --debug
> [debug] [2020-03-12T15:55:22.906Z] Found config in file C:\Users\willi\Github\PrismaFlow\now.json
Now CLI 17.0.4
> [debug] [2020-03-12T15:55:22.933Z] user supplied no target, defaulting to deploy
> [debug] [2020-03-12T15:55:22.945Z] Spinner invoked (Retrieving scope…) with a 1000ms delay
> [debug] [2020-03-12T15:55:24.366Z] Spinner ended (Retrieving scope…)
> [debug] [2020-03-12T15:55:25.380Z] GET https://api.zeit.co/teams 
> [debug] [2020-03-12T15:55:26.375Z] GET https://api.zeit.co/teams : 993.268ms
(node:6736) Warning: No such label '> [debug] #1 GET /teams' for console.timeEnd()
> [debug] [2020-03-12T15:55:26.427Z] GET https://api.zeit.co/teams 
(node:6736) Warning: Label '> [debug] #1 GET /teams}' already exists for console.time()
> [debug] [2020-03-12T15:55:27.451Z] GET https://api.zeit.co/teams : 988.034ms
(node:6736) Warning: No such label '> [debug] #1 GET /teams' for console.timeEnd()
> [debug] [2020-03-12T15:55:27.669Z] Spinner invoked (Retrieving project…) with a 1000ms delay
> [debug] [2020-03-12T15:55:27.673Z] GET https://api.zeit.co/teams 
> [debug] [2020-03-12T15:55:27.694Z] GET https://api.zeit.co/projects/QmRV1Wj8wHtRJYoLTfSXXbViVybbUxeM48bJQFrihhZoyw?teamId=team_pzzTUy8TWCB9zVj2gpx2JyAv 
(node:6736) Warning: Label '> [debug] #1 GET /teams}' already exists for console.time()
> [debug] [2020-03-12T15:55:28.680Z] GET https://api.zeit.co/teams : 988.767ms
(node:6736) Warning: No such label '> [debug] #1 GET /teams' for console.timeEnd()
> [debug] [2020-03-12T15:55:28.712Z] GET https://api.zeit.co/projects/QmRV1Wj8wHtRJYoLTfSXXbViVybbUxeM48bJQFrihhZoyw?teamId=team_pzzTUy8TWCB9zVj2gpx2JyAv : 1016.165ms
> [debug] [2020-03-12T15:55:28.728Z] Spinner ended (Retrieving project…)
> [debug] [2020-03-12T15:55:28.734Z] Spinner invoked (Deploying atto-byte/prisma-flow) with a 0ms delay
[now-client-debug] 2020-03-12T15:55:28.740Z Creating deployment...
[now-client-debug] 2020-03-12T15:55:28.783Z Provided 'path' is a directory. Reading subpaths... 
[now-client-debug] 2020-03-12T15:55:28.786Z Read 22 subpaths
[now-client-debug] 2020-03-12T15:55:28.798Z Found 1 rules in .nowignore
[now-client-debug] 2020-03-12T15:55:28.828Z Building file tree...
[now-client-debug] 2020-03-12T15:55:28.919Z Read 38 files in the specified directory
[now-client-debug] 2020-03-12T15:55:29.120Z Yielding a 'hashes-calculated' event with 38 hashes
[now-client-debug] 2020-03-12T15:55:29.122Z Using provided API URL: https://api.zeit.co
[now-client-debug] 2020-03-12T15:55:29.123Z Using provided user agent: now 17.0.4 node-v12.0.0 win32 (x64)
[now-client-debug] 2020-03-12T15:55:29.124Z Setting platform version to 2
[now-client-debug] 2020-03-12T15:55:29.147Z Creating the deployment and starting upload...
[now-client-debug] 2020-03-12T15:55:29.149Z Determining necessary files for upload...
[now-client-debug] 2020-03-12T15:55:29.151Z Creating deployment
[now-client-debug] 2020-03-12T15:55:29.154Z Sending deployment creation API request
[now-client-debug] 2020-03-12T15:55:57.784Z Yielding a 'error' event
> [debug] [2020-03-12T15:55:57.787Z] Spinner ended (Deploying atto-byte/prisma-flow)
> [debug] [2020-03-12T15:55:58.331Z] Error: Error: queryA EREFUSED api.zeit.co
Error: queryA EREFUSED api.zeit.co
    at Now.handleDeploymentError (C:\Users\willi\AppData\Roaming\nvm\v12.0.0\node_modules\now\dist\index.js:2:1825241)
    at processDeployment (C:\Users\willi\AppData\Roaming\nvm\v12.0.0\node_modules\now\dist\index.js:2:2279034)
    at Now.create (C:\Users\willi\AppData\Roaming\nvm\v12.0.0\node_modules\now\dist\index.js:2:1822725)
    at createDeploy (C:\Users\willi\AppData\Roaming\nvm\v12.0.0\node_modules\now\dist\index.js:2:2012932)
    at Module.main (C:\Users\willi\AppData\Roaming\nvm\v12.0.0\node_modules\now\dist\index.js:2:2862946)
    at Se (C:\Users\willi\AppData\Roaming\nvm\v12.0.0\node_modules\now\dist\index.js:2:1728252)
Error! queryA EREFUSED api.zeit.co

```

**Comment by hynra** [comment]
Same issue using Now CLI 19.0.1 on Windows
```
[now-client-debug] 2020-05-18T07:44:52.676Z Creating deployment...
[now-client-debug] 2020-05-18T07:44:52.677Z Provided 'path' is a directory. Reading subpaths...
[now-client-debug] 2020-05-18T07:44:52.678Z Read 4 subpaths
[now-client-debug] 2020-05-18T07:44:52.681Z Found 1 rules in .nowignore
[now-client-debug] 2020-05-18T07:44:52.681Z Building file tree...
[now-client-debug] 2020-05-18T07:44:52.691Z Read 3 files in the specified directory
[now-client-debug] 2020-05-18T07:44:52.693Z Yielding a 'hashes-calculated' event with 3 hashes
[now-client-debug] 2020-05-18T07:44:52.694Z Using provided API URL: https://api.vercel.com
[now-client-debug] 2020-05-18T07:44:52.694Z Using provided user agent: now 19.0.1 node-v10.17.0 win32 (x64)
[now-client-debug] 2020-05-18T07:44:52.695Z Setting platform version to 2
[now-client-debug] 2020-05-18T07:44:52.695Z Creating the deployment and starting upload...
[now-client-debug] 2020-05-18T07:44:52.696Z Determining necessary files for upload...
[now-client-debug] 2020-05-18T07:44:52.697Z Creating deployment
[now-client-debug] 2020-05-18T07:44:52.698Z Sending deployment creation API request
[now-client-debug] 2020-05-18T07:45:11.698Z Yielding a 'error' event
> [debug] [2020-05-18T07:45:11.699Z] Spinner ended (Setting up project)
> [debug] [2020-05-18T07:45:12.332Z] Error: Error: queryA EREFUSED api.vercel.com
Error: queryA EREFUSED api.vercel.com
    at Now.handleDeploymentError (C:\Users\iman\AppData\Roaming\npm\node_modules\vercel\dist\index.js:2:1756758)
    at processDeployment (C:\Users\iman\AppData\Roaming\npm\node_modules\vercel\dist\index.js:2:2184846)
Error! queryA EREFUSED api.vercel.com
PS C:\Users\my\Documents\vercel-integration\DEPLOYMENT\chat-prod>
```
