### ISSUE TITLE
now is broken as of 17.0.2

### ISSUE THREAD

**Issue by mreinstein** [vercel/vercel#3762]
```bash
➜ now
Now CLI 17.0.2
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ WARN! You are using an old version of the Now Platform. More: https://zeit.co/guides/migrate-to-zeit-now │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘
> Deploying ~/Sites/Go.EnhancedContent.Syndi/test/design under nekoflux
> Using project design
> https://design-wqngfosrui.now.sh [v1] [2s]
> Build completed
Error! An unexpected error occurred!
  Error: Chalk template literal is missing 1 closing bracket (`}`)
    at e.exports (/usr/local/lib/node_modules/now/dist/index.js:2:1500074)
    at chalkTag (/usr/local/lib/node_modules/now/dist/index.js:2:4107379)
    at Object.Chalk.t.template [as default] (/usr/local/lib/node_modules/now/dist/index.js:2:4105076)
    at /usr/local/lib/node_modules/now/dist/index.js:2:4024321
    at processTicksAndRejections (internal/process/task_queues.js:94:5) Error: Chalk template literal is missing 1 closing bracket (`}`)
    at e.exports (/usr/local/lib/node_modules/now/dist/index.js:2:1500074)
    at chalkTag (/usr/local/lib/node_modules/now/dist/index.js:2:4107379)
    at Object.Chalk.t.template [as default] (/usr/local/lib/node_modules/now/dist/index.js:2:4105076)
    at /usr/local/lib/node_modules/now/dist/index.js:2:4024321
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

**Comment by rockymountainhigh1943** [comment]
Same issue we're having over here —> https://github.com/zeit/now/issues/3755

**Comment by mreinstein** [comment]
oops, sorry. I searched for this issue but didn't find it. Closing in favor of the earlier ticket.
