### ISSUE TITLE
routes-manifest.json discovery doesn't take distDir into account

### ISSUE THREAD

**Issue by Janpot** [vercel/vercel#3765]
This is when using `next@canary`. Deploys fail when `distDir` setting is used in `next.config.js`. 

```
2020-02-07T10:43:15.600Z  Error: A routes-manifest.json couldn't be found. This could be due to a failure during the build
2020-02-07T10:43:15.600Z      at Object.getRoutesManifest (/zeit/e0f2cd85419bbae1/.build-utils/.builder/node_modules/@now/next/dist/index.js:6057:15)
2020-02-07T10:43:15.600Z      at async Object.module.exports.178.exports.build (/zeit/e0f2cd85419bbae1/.build-utils/.builder/node_modules/@now/next/dist/index.js:3823:28)
2020-02-07T10:43:15.600Z      at async buildStep (/var/task/sandbox-worker.js:20292:20)
2020-02-07T10:43:15.600Z      at async mainSub (/var/task/sandbox-worker.js:20047:9)
2020-02-07T10:43:15.600Z      at async main (/var/task/sandbox-worker.js:19975:5)
```

Looks like it's not being taken into account here: https://github.com/zeit/now/blob/4dc635e5f2a8cc5ff8de9e1d25ff2693c4e37746/packages/now-next/src/utils.ts#L328-L332

**Comment by Janpot** [comment]
Ok, nevermind, just found https://zeit.co/docs/v2/platform/frequently-asked-questions?query=now.json#missing-public-directory

You might want to add a warning for this though
