### ISSUE TITLE
Build fails: "non-existent npm package" even when it does

### ISSUE THREAD

**Issue by jacklaurencegaray** [vercel/vercel#3787]
```
yarn install v1.17.3
--
02:48:25 PM | [1/4] Resolving packages...
02:48:27 PM | error Couldn't find package "3d-view@^2.0.0" required by "gl-plot3d@^2.4.2" on the "npm" registry.
02:48:27 PM | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
02:48:27 PM | Error: Exited with 1
02:48:27 PM | at ChildProcess.<anonymous> (/zeit/72d2a711565ce413/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:33891:24)
02:48:27 PM | at ChildProcess.emit (events.js:210:5)
02:48:27 PM | at ChildProcess.EventEmitter.emit (domain.js:475:20)
02:48:27 PM | at maybeClose (internal/child_process.js:1021:16)
02:48:27 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
02:48:27 PM | worker exited with code 20 and signal null
02:48:30 PM | Done with "package.json"
```

Both [`3d-view@^2.0.0`](https://www.npmjs.com/package/3d-view) and [`gl-plot3d@^2.4.2`](https://www.npmjs.com/package/gl-plot3d) exist in the npm registry with the correct versions.

**Comment by styfle** [comment]
It sounds like a problem with the npm registry.

Do you still see this issue?
