### ISSUE TITLE
Python Sanic example with 19.12.2 is broken

### ISSUE THREAD

**Issue by remidebette** [vercel/vercel#3799]
Hi,

Starting with sanic 19.12.2, the sample code provided [here](https://zeit.co/docs/runtimes#advanced-usage/advanced-python-usage) does not work. (older versions work fine)

used: 
@now/python and @now/python@canary
python 3.6.9
node 12.16.0

The logs of now dev:

```
$ now dev
Now CLI 17.0.3 dev (beta) — https://zeit.co/feedback
> Ready! Available at http://localhost:3000
> Building @now/python@canary:index.py
Installing required dependencies...
> Built @now/python@canary:index.py [1m]
Traceback (most recent call last):
  File "/home/remi/.cache/co.zeit.fun/runtimes/python3/../python/bootstrap.py", line 147, in <module>
    lambda_runtime_main()
  File "/home/remi/.cache/co.zeit.fun/runtimes/python3/../python/bootstrap.py", line 127, in lambda_runtime_main
    fn = lambda_runtime_get_handler()
  File "/home/remi/.cache/co.zeit.fun/runtimes/python3/../python/bootstrap.py", line 113, in lambda_runtime_get_handler
    mod = importlib.import_module(module_name)
  File "/home/remi/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/zeit-fun-8312f05f7c2c9/now__handler__python.py", line 11, in <module>
    __now_spec.loader.exec_module(__now_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./index.py", line 8, in <module>
    async def index(request, path=""):
  File "/tmp/zeit-fun-8312f05f7c2c9/sanic/app.py", line 197, in response
    args = list(signature(handler).parameters.keys())
  File "/home/remi/.pyenv/versions/3.6.9/lib/python3.6/inspect.py", line 3065, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/home/remi/.pyenv/versions/3.6.9/lib/python3.6/inspect.py", line 2815, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/home/remi/.pyenv/versions/3.6.9/lib/python3.6/inspect.py", line 2193, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: ([Route(handler=<function index at 0x7fff28ec4ea0>, methods=frozenset({'GET'}), pattern=re.compile('^/([^/].*?)$'), parameters=[Parameter(name='path', cast=<class 'str'>)], name='index', uri='/
<path:path>'), Route(handler=<function index at 0x7fff28ec4ea0>, methods=frozenset({'GET'}), pattern=re.compile('^/([^/].*?)/$'), parameters=[Parameter(name='path', cast=<class 'str'>)], name='index', uri
='/<path:path>/')], <function index at 0x7fff28ec4ea0>) is not a callable object
LambdaError: RequestId: b5ae12a2-1ee1-43ab-9bab-4ad9ed1e5e2a Process exited before completing request
    at Lambda.<anonymous> (/home/remi/.nvm/versions/node/v12.16.0/lib/node_modules/now/dist/index.js:2:3545645)
    at Generator.next (<anonymous>)
    at fulfilled (/home/remi/.nvm/versions/node/v12.16.0/lib/node_modules/now/dist/index.js:2:3543532)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by styfle** [comment]
Does it work when you deploy to production with `now`?

Our test fixture is using Sanic 19.6.0 as seen here: https://github.com/zeit/now/blob/0e71ff2df1601fb4c7b697f57848c78d6bc41507/packages/now-python/test/fixtures/11-asgi/Pipfile.lock#L147

**Comment by remidebette** [comment]
Hi, thanks for the response.

Deploying to `now` results in the same behavior.
I fell back to the last sanic version before 19.12.2 (explicitly: 12.9.0) to make it work for now.

This ticket is just a heads up that `now` breaks with this new version of sanic.

**Comment by styfle** [comment]
I was tried deploying multiple versions of Sanic and all of them worked.

- 19.6.0
- 19.9.0
- 19.12.0
- 19.12.2

### Example

- Demo: https://00-asgi-sanic-kn3216axc.now.sh/api/sanic
- Source: https://00-asgi-sanic-kn3216axc.now.sh/_src
