### ISSUE TITLE
ECONNREFUSED on deployement

### ISSUE THREAD

**Issue by martineon** [vercel/vercel#3802]
## Hi everyone ✌️!

I'm having an issue since i've updated `now`.

After the update, i've got this:

````
Error! queryA ECONNREFUSED api.zeit.co
````

I tried to downgrade the `now`, `npm` and `node` version, but the issue is still there.

No **proxy** or **dns** is configure on my computer.

I tried to ping `api.zeit.co`  and got `Request timeout for icmp_seq 0`.
Don't know if it's normal or not. 😞

### _Thanks in advance for your help 👏 !_

**Versions:**
````
macOS 10.14.6
node v13.8.0
npm 6.13.7
now 17.0.3
````

**Debug logs:**

`````
[now-client-debug] 2020-02-18T16:46:39.555Z Creating the deployment and starting upload...
[now-client-debug] 2020-02-18T16:46:39.555Z Determining necessary files for upload...
[now-client-debug] 2020-02-18T16:46:39.555Z Creating deployment
[now-client-debug] 2020-02-18T16:46:39.559Z Sending deployment creation API request
[now-client-debug] 2020-02-18T16:47:05.654Z Yielding a 'error' event
> [debug] [2020-02-18T16:47:05.654Z] Spinner ended (Deploying prizoners/citizen_pso)
> [debug] [2020-02-18T16:47:06.099Z] Error: Error: queryA ECONNREFUSED api.zeit.co
Error: queryA ECONNREFUSED api.zeit.co
    at Now.handleDeploymentError (/Users/eonmartin/.nvm/versions/node/v13.8.0/lib/node_modules/now/dist/index.js:2:1825302)
    at processDeployment (/Users/eonmartin/.nvm/versions/node/v13.8.0/lib/node_modules/now/dist/index.js:2:2279028)
    at Now.create (/Users/eonmartin/.nvm/versions/node/v13.8.0/lib/node_modules/now/dist/index.js:2:1822786)
    at createDeploy (/Users/eonmartin/.nvm/versions/node/v13.8.0/lib/node_modules/now/dist/index.js:2:2012926)
    at Module.main (/Users/eonmartin/.nvm/versions/node/v13.8.0/lib/node_modules/now/dist/index.js:2:2862940)
    at Se (/Users/eonmartin/.nvm/versions/node/v13.8.0/lib/node_modules/now/dist/index.js:2:1728313)
Error! queryA ECONNREFUSED api.zeit.co
`````

ps: Sorry for my english... 🥺

**Comment by paulogdm** [comment]
Unfortunately, it seems you may have a problem with either NVM or some local configuration. That error happens if your machine is unable to resolve "api.zeit.co" to an IP. Double-check your environment with the commands:

- `dig a api.zeit.co +short`
- `dig a api.zeit.co @1.1.1.1 +short`
- `dig a api.zeit.co @8.8.8.8 +short`
- `dig ns api.zeit.co +short`
