### ISSUE TITLE
[now-go] now dev fails installing now-go

### ISSUE THREAD

**Issue by jamesramsay** [vercel/vercel#3804]
I'm trying to write a a few Serverless Go functions, and wanted to use `now dev` for testing locally, but have been getting errors at the `now-go` install step.

```
now dev --debug
...
> [debug] [2020-02-18T20:56:42.968Z] Spinner invoked (Installing Runtime: now-go@1.0.3) with a 300ms delay
> [debug] [2020-02-18T20:56:52.079Z] Spinner ended (Installing Runtime: now-go@1.0.3)
Error! Command failed with exit code 1: /usr/local/bin/node /Users/jramsay/Library/Caches/co.zeit.now/dev/builders/yarn add --exact --no-lockfile --non-interactive now-go@1.0.3
> [debug] [2020-02-18T20:56:52.641Z] Error: Command failed with exit code 1: /usr/local/bin/node /Users/jramsay/Library/Caches/co.zeit.now/dev/builders/yarn add --exact --no-lockfile --non-interactive now-go@1.0.3
    at o (/usr/local/lib/node_modules/now/dist/index.js:2:4160232)
    at S (/usr/local/lib/node_modules/now/dist/index.js:2:291228)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
zsh: exit 1     now dev --debug
```

In case it's relevant, here's my `now.json` config:

```
{
  "version": 2,
  "routes": [{ "src": "/api/(.*)", "dest": "api/micropub.go" }],
  "functions": {
    "api/micropub.go": {
      "runtime": "now-go@1.0.3",
      "includeFiles": "templates/**"
    }
  },
  "env": {
    "GITLAB_TOKEN": "@gitlab_token"
  }
}
```

I have been using `now@17.0.3`, but also tried downgrading to `now@16.7.3`.

**Comment by jamesramsay** [comment]
I upgraded from `node v12.10.0` to `node v13.9.0` with no change except some longer output:

```
> [debug] [2020-02-18T21:00:25.362Z] Spinner invoked (Installing Runtime: now-go@1.0.3) with a 300ms delay
> [debug] [2020-02-18T21:00:31.478Z] Spinner ended (Installing Runtime: now-go@1.0.3)
Error! Command failed with exit code 1: /usr/local/bin/node /Users/jramsay/Library/Caches/co.zeit.now/dev/builders/yarn add --exact --no-lockfile --non-interactive now-go@1.0.3
> [debug] [2020-02-18T21:00:32.005Z] Error: Command failed with exit code 1: /usr/local/bin/node /Users/jramsay/Library/Caches/co.zeit.now/dev/builders/yarn add --exact --no-lockfile --non-interactive now-go@1.0.3
    at o (/usr/local/lib/node_modules/now/dist/index.js:2:4160232)
    at S (/usr/local/lib/node_modules/now/dist/index.js:2:291228)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.installBuilders (/usr/local/lib/node_modules/now/dist/index.js:2:1191882)
    at DevServer.start (/usr/local/lib/node_modules/now/dist/index.js:2:1286109)
    at Object.dev [as default] (/usr/local/lib/node_modules/now/dist/index.js:2:363012)
    at main (/usr/local/lib/node_modules/now/dist/index.js:2:2626990)
    at Se (/usr/local/lib/node_modules/now/dist/index.js:2:1728313)
zsh: exit 1     now dev --debug
```

**Comment by styfle** [comment]
Hi @jamesramsay 

Can you try running the command and see if it provides anymore information?

```
cd /Users/jramsay/Library/Caches/co.zeit.now/dev/builders
/usr/local/bin/node /Users/jramsay/Library/Caches/co.zeit.now/dev/builders/yarn add --exact --no-lockfile --non-interactive now-go@1.0.3
```

Also, what do you see when you run `which node`?

**Comment by jamesramsay** [comment]
Thanks for that suggestion @styfle. That made it obvious I was using the wrong `runtime` field. It should have been: `"runtime": "@now/go@1.0.0"`

I think the problem was I guessed the runtime because it wasn't listed in the docs (https://zeit.co/docs/runtimes#official-runtimes/go). Maybe a quick fix to the docs to link to the correct node module would help others? Thanks again 😊

**Comment by styfle** [comment]
Oh nice catch!

You should be be able to use config options without `runtime` like the following:

```
{
  "functions": {
    "api/micropub.go": {
      "includeFiles": "templates/**"
    }
  }
}
```

All of the properties are optional as seen in the [`function` docs](https://zeit.co/docs/configuration#project/functions).

Also see [advanced usage](https://zeit.co/docs/runtimes#advanced-usage/technical-details/including-additional-files).
