### ISSUE TITLE
Now Dev Crashes on Node 8

### ISSUE THREAD

**Issue by redreceipt** [vercel/vercel#3866]
When running `now dev` on node 8.6, it crashes with a very cryptic error. It should check the node version cleanly if there's a requirement.

```
kpffl % now dev                                                                                     (master) kpffl 
/usr/local/Cellar/now-cli/17.0.4/libexec/lib/node_modules/now/dist/index.js:2
require('./sourcemap-register.js');module.exports=function(e,t){"use strict";var n={};function __webpack_require__(t){if(n[t]){return n[t].exports}var r=n[t]={i:t,l:false,exports:{}};e[t].call(r.exports,r,r.exports,__webpack_require__);r.l=true;return r.exports}__webpack_require__.c=n;function startup(){return __webpack_require__(4165)}t(__webpack_require__);return startup()}([,,,,,,,,,,,,,,,,function(e,t,n){"use strict";var r=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:true});const i=r(n(4859));function arrayMove(e,t,n,r,i){for(let o=0;o<i;++o){n[o+r]=e[o+t];e[o+t]=void 0}}function pow2AtLeast(e){e=e>>>0;e=e-1;e=e|e>>1;e=e|e>>2;e=e|e>>4;e=e|e>>8;e=e|e>>16;return e+1}function getCapacity(e){return pow2AtLeast(Math.min(Math.max(16,e),1073741824))}class Deque{constructor(e){this._capacity=getCapacity(e);this._length=0;this._front=0;this.arr=[]}push(e){cons

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
kpffl %                                                                                             (master) kpffl
kpffl % nvm use                                                                                     (master) kpffl 
Found '/Users/XXXXX/Documents/Projects/kpffl/.nvmrc' with version <13.8.0>
Now using node v13.8.0 (npm v6.13.6)
kpffl % now dev                                                                                     (master) kpffl 
Now CLI 17.0.4 dev (beta) — https://zeit.co/feedback
> Ready! Available at http://localhost:3000
```

**Comment by leo** [comment]
Thank you for sharing! We'll make sure to render a proper error in this case.

Out of the box, we support Node.js' latest LTS version.

**Comment by styfle** [comment]
It looks like `npm` doesn't check [`engines`](https://github.com/zeit/now/blob/62ce2f6cac5418e1a627485c658cda5889ebc073/packages/now-cli/package.json#L61) the same way yarn does.

We could recommend `npm i -g --engine-strict now` so that install fails with a Not Supported error:

```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for now@17.0.4: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"5.6.0"})
npm ERR! notsup Not compatible with your version of node/npm: now@17.0.4
```

We also have a [preinstall](https://github.com/zeit/now/blob/master/packages/now-cli/scripts/preinstall.js) script that could check the current node version and print a pretty error.

**Comment by redreceipt** [comment]
> It looks like `npm` doesn't check [`engines`](https://github.com/zeit/now/blob/62ce2f6cac5418e1a627485c658cda5889ebc073/packages/now-cli/package.json#L61) the same way yarn does.

In case it helps the decision, I installed with Homebrew, guessing many do the same.

**Comment by styfle** [comment]
That sounds like a bug with the homebrew formula since brew is supposed to install the dependency along with any required dependencies (in this case Node.js 10 or newer).

We don't control that formula however but I did find the original PR https://github.com/Homebrew/homebrew-core/pull/14827

Perhaps someone could submit a PR to homebrew to fix it? cc @amio

**Comment by styfle** [comment]
This is fixed when installing with npm on the canary channel.

```
npm i -g now@canary
```
