### ISSUE TITLE
Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by leo** [vercel/vercel#480]
User report from community:
...
> Enter your billing address
✓ Country     Finland
⠋ ZIP         00100TypeError: Cannot read property 'state' of undefined
    at /thebox/Users/leo/Projects/now-cli/build/bin/now-billing-add.js:159:28
    at Generator.next (<anonymous>)
    at c (/thebox/Users/leo/Projects/now-cli/build/bin/now-billing-add.js:208:99)
    at process._tickCallback (internal/process/next_tick.js:103:7)
⠼ ZIP         00100

Not sure if this still applies, needs to be tested.

**Comment by leo** [comment]
Seems to be fixed!
