### ISSUE TITLE
Vercel refuses to work with TypeScript’s default tsconfig.json

### ISSUE THREAD

**Issue by dtinth** [vercel/vercel#4835]
By creating a `tsconfig.json` using `tsc --init`, which looks like this:

```jsonc
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

…and then run `vercel dev`, it errors out with:

```
Error while parsing "/home/ubuntu/environment/dtinth/tsconfig.json"
/home/ubuntu/environment/dtinth/node_modules/vercel/node_modules/@vercel/node/dist/dev-server.js:47
            throw err;
            ^

SyntaxError: Unexpected token / in JSON at position 29
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/ubuntu/environment/dtinth/node_modules/vercel/node_modules/@vercel/node/dist/dev-server.js:38:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

From checking the source code, it seems that the code that parses `tsconfig.json` did not handle JSON comments.

https://github.com/vercel/vercel/blob/c68e83f9726e622c3366653aee2674e35ccf4bc9/packages/now-node/src/dev-server.ts#L37

Note that TypeScript configuration file `tsconfig.json`, despite having a `.json` file format, is actually a JSONC (JSON with Comments) file. Easiest way to deal with this may be to use [strip-json-comments](https://www.npmjs.com/package/strip-json-comments)

**Comment by styfle** [comment]
@TooTallNate We should be using `ts.readConfigFile()` in dev like we do for production deployments 

https://github.com/vercel/vercel/blob/068ea00615eb70709e3516df7b12cc6a77fb7559/packages/now-node/src/typescript.ts#L367

**Comment by leo** [comment]
Thank you for sharing! We'll roll out a fix for this very soon.

**Comment by sh-a-v** [comment]
> 
> 
> Thank you for sharing! We'll roll out a fix for this very soon.

@leo how soon?

**Comment by cupcakearmy** [comment]
Same issue here. Good that the problem has been found :)

**Comment by wobsoriano** [comment]
I'm still getting this issue with Nuxt + TS

![Screen Shot 2021-06-20 at 11 03 00 PM](https://user-images.githubusercontent.com/13049130/122679010-accd0780-d21b-11eb-91a2-734ab80ac5fa.png)

```

23:01:42.523 | Cloning completed: 1.127s
23:01:42.551 | Analyzing source code...
23:01:42.562 | Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
23:01:44.028 | Installing build runtime...
23:01:48.424 | Build runtime installed: 4.396s
23:01:51.474 | Looking up build cache...
23:01:51.814 | Build Cache not found
23:01:53.052 | [log] Running with @nuxt/vercel-builder version 0.21.3
23:01:53.052 | [log]  ----------------- Prepare build -----------------
23:01:53.052 | [log] Downloading files...
23:01:53.053 | [log] Working directory: /vercel/path0
23:01:53.060 | Error: Can not read tsconfig.json from /vercel/path0
23:01:53.060 | at prepareTypescriptEnvironment (/vercel/3c784afb160a123f/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:177:13)
23:01:53.061 | at Object.build (/vercel/3c784afb160a123f/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:286:5)
23:01:53.061 | at buildStep (/var/task/webpack:/@zeit/api/scripts/build-container/src/utils/purpose-build.ts:164:1)
```

**_tsconfig.json_**

```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "DOM"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./*"
      ]
    },
    "types": [
      "@nuxt/types",
      "@nuxtjs/axios",
      "@types/node",
      "@nuxtjs/dayjs",
    ]
  },
  "exclude": [
    "node_modules",
    ".nuxt",
    "dist"
  ]
}
```
