### ISSUE TITLE
Error installing build runtime

### ISSUE THREAD

**Issue by iinfin** [vercel/vercel#4998]
I've been getting this error for my deployments. I guess it doesn't seem related to the repository itself but still I tested with different repositories and tried to redeploy from older commits.

```
13:43:14.889  	Cloning github.com/u29dc/www (Branch: master, Commit: 25d7069)
13:43:15.431  	Cloning completed in 541ms
13:43:15.432  	Analyzing source code...
13:43:16.473  	Installing build runtime...
13:43:32.185  	Error: Exited with 1
13:43:32.185  	    at ChildProcess.<anonymous> (/var/task/sandbox-worker.js:21953:21)
13:43:32.185  	    at ChildProcess.emit (events.js:310:20)
13:43:32.185  	    at ChildProcess.EventEmitter.emit (domain.js:482:12)
13:43:32.185  	    at maybeClose (internal/child_process.js:1021:16)
13:43:32.185  	    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13:43:34.260  	Done with "package.json"
```

**Comment by greatSumini** [comment]
same here 😢

**Comment by babyPrince** [comment]
Same thing here

**Comment by babyPrince** [comment]
Seems to be back to normal now 🥂

**Comment by jordyvandomselaar** [comment]
NPM had an outage. Should be fixed soon!

**Comment by iinfin** [comment]
Oh I see @jordyvandomselaar, it was because of [this](https://status.npmjs.org/incidents/cksjqc1w11v5) then.
Seems to be resolved!
