### ISSUE TITLE
`now domains add --force` is not skipping the verifications

### ISSUE THREAD

**Issue by matheuss** [vercel/vercel#528]
```
» now domains add -f cadmill.com.au
> Error! Unknown error: Error: verification failed, retrying
Error: verification failed, retrying
    at Domains.<anonymous> (/Users/rudi/.config/yarn/global/node_modules/now/build/lib/index.js:689:33)
    at next (native)
    at c (/Users/rudi/.config/yarn/global/node_modules/now/build/lib/index.js:983:99)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Via @ryardley on [zeit.chat](https://zeit.chat)

**Comment by rgoytacaz** [comment]
@albinekb

**Comment by rgoytacaz** [comment]
@OlliV

**Comment by TooTallNate** [comment]
Closing because `-f`/`--force` is not a valid flag for `now domains add` and as of latest Now CLI a proper error message is shown:

```
$ now domains add -f cadmill.com.au
> Error! Unknown or unexpected option: -f
```
