### ISSUE TITLE
Scaling a static deployment causes an error because of missing "scale" property

### ISSUE THREAD

**Issue by tombell** [vercel/vercel#542]
It seems that with launching the new infinite scaling for `static` deployments, the API responses have changed for those deployments. The no longer include the `scale` property, this causes errors to be thrown when attempting to scale them.

```
TypeError: Cannot match against 'undefined' or 'null'.
    at /usr/local/lib/node_modules/now/build/bin/now-scale.js:184:12
    at Generator.next (<anonymous>)
    at c (/usr/local/lib/node_modules/now/build/bin/now-scale.js:336:99)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

https://github.com/zeit/now-cli/blob/master/bin/now-scale.js#L184

Example response from getting my deployments:

```json
{
  "deployments": [
    {
      "uid": "redacted-static-deployment",
      "name": "redacted-static-deployment",
      "url": "redacted-static-deployment.now.sh",
      "created": "1494866861611",
      "state": "READY",
      "type": "STATIC"
    },
    {
      "uid": "redacted",
      "name": "redacted",
      "url": "redacted.now.sh",
      "created": "1494536324193",
      "state": "FROZEN",
      "type": "NPM",
      "scale": {
        "current": 0,
        "min": 0,
        "max": 1
      }
    }
  ]
}
```

**Comment by rauchg** [comment]
Thanks for reporting. I could have sworn we had looked at this case. We'll fix ASAP!
