### ISSUE TITLE
Periodic failures install now-cli on TravisCI running Node 6

### ISSUE THREAD

**Issue by Ignigena** [vercel/vercel#615]
During the`postinstall` script, the `latest.assets` is `undefined` which breaks builds. I have tried both installing `now` as a `devDependency` in my `package.json` as well as just installing globally through a `preinstall` hook in my `.travis.yml` file.

Periodically (1 in every 3-4 invocations) the build will pass without issue. Otherwise I get the output below:

```
now@6.2.5 postinstall /home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now
> node download/install.js
> Retrieving the latest CLI version...
TypeError: Cannot read property 'find' of undefined
    at _callee$ (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/download.js:4771:34)
    at tryCatch (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/download.js:14364:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/download.js:14599:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/download.js:14416:21)
    at step (/home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/download.js:5003:30)
    at /home/travis/.nvm/versions/node/v6.10.3/lib/node_modules/now/download/dist/download.js:5014:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.10.3/bin/node" "/home/travis/.nvm/versions/node/v6.10.3/bin/npm" "install" "-g" "now"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

**Comment by leo** [comment]
@igorklopov Any idea?

**Comment by leo** [comment]
We're on it! @igorklopov is sending a PR

**Comment by Ignigena** [comment]
Was this fixed with #625? Want to make sure before I test against the latest build :)

**Comment by igorklopov** [comment]
@Ignigena Yes, that PR addresses your issue. Please try.

**Comment by leo** [comment]
Works for me!
