### ISSUE TITLE
Deploy error with Uppy file upload

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#6363]
When running a build locallyl everything works fine, no errors etc. When trying to deploy to Vercel I get this error:

```

15:42:44.433 | Failed to compile.
-- | --
15:42:44.434 | ModuleNotFoundError: Module not found: Error: Can't resolve '@uppy/core' in '/vercel/path0/pages/account'
15:42:44.434 | &gt; Build error occurred
15:42:44.435 | Error: &gt; Build failed because of webpack errors
15:42:44.435 | at /vercel/path0/node_modules/next/dist/build/index.js:17:924
15:42:44.435 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
15:42:44.454 | npm ERR! code ELIFECYCLE
15:42:44.454 | npm ERR! errno 1
15:42:44.457 | npm ERR! Exit status 1
15:42:44.457 | npm ERR!
15:42:44.457 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
15:42:44.465 | npm ERR! A complete log of this run can be found in:
15:42:44.465 | npm ERR!     /vercel/.npm/_logs/2021-06-16T13_42_44_457Z-debug.log
15:42:44.477 | Error: Command "npm run build" exited with 1


```

In my package.json I have

```
    "@uppy/form": "^1.3.30",
    "@uppy/image-editor": "^0.2.6",
    "@uppy/react": "^1.11.10",
    "@uppy/xhr-upload": "^1.7.4",
```

And in my actual page I have

```
import Uppy from "@uppy/core";
import XHRUpload from "@uppy/xhr-upload";
const ImageEditor = require("@uppy/image-editor");
import { DashboardModal, useUppy } from "@uppy/react";
import "@uppy/core/dist/style.css";
import "@uppy/dashboard/dist/style.css";
import "@uppy/image-editor/dist/style.css";
```

**Comment by leerob** [comment]
Hey! This issue seems to have gone stale. If you're still having issues building and deploying using Uppy, we can reopen this. Thanks!
