### ISSUE TITLE
Deployment Failures

### ISSUE THREAD

**Issue by Adam-Burke** [vercel/vercel#641]
Hi, 

I'm loving now.

I'm just having a fair amount of failed deployments since last night that just hang on 'initializing' in the cli and 'preparing container' in the dashboard. I'm just wondering what I can do to debug this issue. It doesn't seem that the --debug setting in the cli reveals much about the issue just that there is often an unexpected internal error after '[debug] Computing Hashes' and a similar error after [debug] /now/create also quite often but both seem inconsistant.

It seems like it all started when the cil first encountered a Dockerfile in one of my repos but that may be a coincidence. 

edit: But also if I just keep trying eventually they seem to work. Except for my create-react-app which never seem to work. 

edit2: For the failed create-react-app deployments I get the following error on repeated retries until it fails. 

/now/create: 50841.727ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at deployment.retry (/snapshot/home/travis/build/zeit/now-cli/lib/index.js:201:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Adam-Burke** [comment]
Ok I figured it out. I added the local history extension for vs code editor and that seemed to break the deployments.
