### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by MariusAlch** [vercel/vercel#666]
might be related to #663 

```
$ sudo npm install -g now
/usr/bin/now -> /usr/lib/node_modules/now/download/dist/now

> now@6.4.0 postinstall /usr/lib/node_modules/now
> node download/install.js

{ Error: EACCES: permission denied, open '/usr/lib/node_modules/now/download/dist/now'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.writeFileSync (fs.js:1300:33)
    at _callee$ (/usr/lib/node_modules/now/download/dist/download.js:4754:26)
    at tryCatch (/usr/lib/node_modules/now/download/dist/download.js:4997:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/now/download/dist/download.js:5235:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/now/download/dist/download.js:5049:21)
    at step (/usr/lib/node_modules/now/download/dist/download.js:6603:30)
    at /usr/lib/node_modules/now/download/dist/download.js:6621:14
    at Promise (<anonymous>)
    at F (/usr/lib/node_modules/now/download/dist/download.js:3466:28)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/node_modules/now/download/dist/now' }
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! now@6.4.0 postinstall: `node download/install.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the now@6.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marius/.npm/_logs/2017-06-12T17_51_34_480Z-debug.log

```

same thing is shown on 'sudo npm install -g now@6.4.0'

**Comment by matheuss** [comment]
@MariusAlch have you tried this? https://github.com/zeit/now-cli/issues/651#issuecomment-307833039 🙏

**Comment by MariusAlch** [comment]
Ignored [fixing permissions](https://github.com/zeit/now-cli/issues/651#issuecomment-307833039), after that everything is working fine. sorry for duplicate
