### ISSUE TITLE
Can't install Now through terminal

### ISSUE THREAD

**Issue by arturogh** [vercel/vercel#677]
Hi,

After deploying a static site successfully through now using the terminal, I got an alert that there was an update to v7.0 of Now.

Tried doing `sudo npm install -g now` and getting an error.

I get this on terminal
```
Arturos-MBP-3:~ argoicoc$ sudo npm install -g now
Password:
/usr/local/bin/now -> /usr/local/lib/node_modules/now/download/dist/now

> now@7.0.0 postinstall /usr/local/lib/node_modules/now
> node download/install.js

{ Error: EACCES: permission denied, open '/usr/local/lib/node_modules/now/download/dist/now'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at _callee$ (/usr/local/lib/node_modules/now/download/dist/download.js:4754:26)
    at tryCatch (/usr/local/lib/node_modules/now/download/dist/download.js:4997:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/now/download/dist/download.js:5235:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/now/download/dist/download.js:5049:21)
    at step (/usr/local/lib/node_modules/now/download/dist/download.js:6603:30)
    at /usr/local/lib/node_modules/now/download/dist/download.js:6621:14
    at Promise.F (/usr/local/lib/node_modules/now/download/dist/download.js:3466:28)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/now/download/dist/now' }
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! now@7.0.0 postinstall: `node download/install.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the now@7.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arturogoicochea/.npm/_logs/2017-06-15T20_13_57_756Z-debug.log
```

This is the error log I get:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'now' ]
2 info using npm@5.0.3
3 info using node@v6.9.3
4 verbose npm-session 4622bbea74f4a87b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/now 18ms (from cache)
8 silly pacote tag manifest for now@latest fetched in 47ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule now@7.0.0 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── now@7.0.0
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add now@7.0.0
19 silly decomposeActions action count 8
20 silly decomposeActions fetch now@7.0.0
21 silly decomposeActions extract now@7.0.0
22 silly decomposeActions preinstall now@7.0.0
23 silly decomposeActions build now@7.0.0
24 silly decomposeActions install now@7.0.0
25 silly decomposeActions postinstall now@7.0.0
26 silly decomposeActions finalize now@7.0.0
27 silly decomposeActions refresh-package-json now@7.0.0
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /Users/arturogoicochea/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /Users/arturogoicochea/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
32 silly doParallel extract 8
33 silly extract now@7.0.0
34 silly pacote trying now@https://registry.npmjs.org/now/-/now-7.0.0.tgz by hash: sha1-OkztYth7V0V5hK/VDBsfoP/qvts=
35 silly pacote now@https://registry.npmjs.org/now/-/now-7.0.0.tgz extracted to /usr/local/lib/node_modules/.staging/now-b6975e36 by content address 33ms
36 silly doReverseSerial remove 8
37 silly doSerial move 8
38 silly doSerial finalize 8
39 silly finalize /usr/local/lib/node_modules/now
40 silly doParallel refresh-package-json 8
41 silly refresh-package-json /usr/local/lib/node_modules/now
42 silly doParallel preinstall 8
43 silly preinstall now@7.0.0
44 info lifecycle now@7.0.0~preinstall: now@7.0.0
45 silly lifecycle now@7.0.0~preinstall: no script for preinstall, continuing
46 silly doSerial build 8
47 silly build now@7.0.0
48 info linkStuff now@7.0.0
49 silly linkStuff now@7.0.0 has /usr/local/lib/node_modules as its parent node_modules
50 silly linkStuff now@7.0.0 is part of a global install
51 silly linkStuff now@7.0.0 is installed into a global node_modules
52 silly linkStuff now@7.0.0 is installed into the top-level global node_modules
53 verbose linkBins now@7.0.0
54 verbose linkBins [ { now: 'download/dist/now' }, '/usr/local/bin', true ]
55 verbose linkMans now@7.0.0
56 silly doSerial global-link 8
57 silly doParallel update-linked 8
58 silly doSerial install 8
59 silly install now@7.0.0
60 info lifecycle now@7.0.0~install: now@7.0.0
61 silly lifecycle now@7.0.0~install: no script for install, continuing
62 silly doSerial postinstall 8
63 silly postinstall now@7.0.0
64 info lifecycle now@7.0.0~postinstall: now@7.0.0
65 verbose lifecycle now@7.0.0~postinstall: unsafe-perm in lifecycle false
66 verbose lifecycle now@7.0.0~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/now/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
67 verbose lifecycle now@7.0.0~postinstall: CWD: /usr/local/lib/node_modules/now
68 silly lifecycle now@7.0.0~postinstall: Args: [ '-c', 'node download/install.js' ]
69 silly lifecycle now@7.0.0~postinstall: Returned: code: 2  signal: null
70 info lifecycle now@7.0.0~postinstall: Failed to exec postinstall script
71 verbose unlock done using /Users/arturogoicochea/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
72 verbose stack Error: now@7.0.0 postinstall: `node download/install.js`
72 verbose stack Exit status 2
72 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
72 verbose stack     at emitTwo (events.js:106:13)
72 verbose stack     at EventEmitter.emit (events.js:191:7)
72 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
72 verbose stack     at emitTwo (events.js:106:13)
72 verbose stack     at ChildProcess.emit (events.js:191:7)
72 verbose stack     at maybeClose (internal/child_process.js:877:16)
72 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
73 verbose pkgid now@7.0.0
74 verbose cwd /Users/arturogoicochea/Dropbox/designDev/arturogoicochea2017/code-design/Build
75 verbose Darwin 16.6.0
76 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "now"
77 verbose node v6.9.3
78 verbose npm  v5.0.3
79 error code ELIFECYCLE
80 error errno 2
81 error now@7.0.0 postinstall: `node download/install.js`
81 error Exit status 2
82 error Failed at the now@7.0.0 postinstall script.
82 error This is probably not a problem with npm. There is likely additional logging output above.
83 verbose exit [ 2, true ]
```

**Comment by arturogh** [comment]
I tried fixing the npm permissions (https://docs.npmjs.com/getting-started/fixing-npm-permissions ) but that did not work.

In the end downloading and running locally did.

**Comment by leo** [comment]
@igorklopov Another one of these again. Any idea how we can tackle this? Can we avoid opening the file maybe? Hmmmm... 🤔

**Comment by igorklopov** [comment]
The problem may be in `unsafe-perm in lifecycle false`. Please install `now` again specifying `unsafe-perm` explicitly: `sudo npm install -g now --unsafe-perm`

**Comment by arturogh** [comment]
Just tried that @igorklopov ...and it worked! YES! 💪

**Comment by igorklopov** [comment]
Great! Then @leo i think we should catch EACCES and ask user to reinstall `now` specifying `--unsafe-perm`

**Comment by leo** [comment]
@igorklopov That sounds like a good idea! 👍 Want to PR it?

**Comment by igorklopov** [comment]
Yes!

**Comment by Qix-** [comment]
PR open in #683.

**Comment by leo** [comment]
Prompt added in [7.0.2](https://github.com/zeit/now-cli/releases/tag/7.0.2)! 🎉

**Comment by abcd-ca** [comment]
how "unsafe" _is_ it to use this param?
