### ISSUE TITLE
@zeit/cace issue...

### ISSUE THREAD

**Issue by morgs32** [vercel/vercel#714]
After npm install my deploy breaks and here is the log:
```
07/10 05:14 PM (2m)
Installing package classnames@^2.2.5
Installing package cookie-parser@^1.4.3
Installing package cross-env@~1.0.8
Installing package debug@^2.2.0
Installing package envify@^3.4.1
Installing package express@~4.13.4
Installing package firebase@^3.8.0
Installing package firebase-admin@^4.0.4
Installing package history@^4.6.1
Installing package immutable@^3.8.1
Installing package isomorphic-fetch@^2.2.1
Installing package js-cookie@^2.1.3
Installing package lodash@^4.16.2
Installing package lodash.merge@^4.6.0
Installing package material-ui@^0.16.4
Installing package morgan@~1.7.0
Installing package node-sass@~3.7.0
Installing package pm2@^2.5.0
07/10 05:14 PM (2m)
Installing package pretty-error@^2.0.2
07/10 05:14 PM (2m)
Installing package react@^15.6.1
07/10 05:14 PM (2m)
Installing package react-addons-test-utils@~15.4.1
Installing package react-bootstrap@^0.30.7
07/10 05:14 PM (2m)
Installing package react-custom-scrollbars@^4.1.1
07/10 05:14 PM (2m)
Installing package react-dom@~15.4.1
07/10 05:14 PM (2m)
Installing package react-grid-layout@^0.14.4
07/10 05:14 PM (2m)
Installing package react-icons@^2.2.1
Installing package react-modal@^1.7.3
Installing package react-motion@^0.4.5
Installing package react-notification-system@^0.2.11
Installing package react-redux@^5.0.5
Installing package react-redux-loading-bar@^2.6.0
Installing package react-router-dom@^4.1.1
Installing package react-router-redux@5.0.0-alpha.6
Installing package react-select@git+https://…-oauth-basic@github.com/morgs32/react-select.git
07/10 05:14 PM (2m)
Installing package react-stonecutter@^0.3.3
Installing package react-tap-event-plugin@^2.0.0
07/10 05:14 PM (2m)
Installing package redux@^3.6.0
07/10 05:14 PM (2m)
Installing package redux-form@^6.6.0
07/10 05:14 PM (2m)
Installing package redux-logger@^2.6.1
07/10 05:14 PM (2m)
Installing package redux-thunk@~2.1.0
07/10 05:14 PM (2m)
Installing package reselect@^2.5.4
07/10 05:14 PM (2m)
Installing package serialize-javascript@^1.3.0
Installing package smoothscroll@^0.3.0
07/10 05:14 PM (2m)
Installing package sparkpost@^2.1.0
07/10 05:14 PM (2m)
Installing package stackshirts-logos@git+https://…-oauth-basic@github.com/morgs32/stackshirts-logos.git
07/10 05:14 PM (2m)
Installing package stream@0.0.2
07/10 05:14 PM (2m)
Installing package styled-components@^1.4.4
07/10 05:14 PM (2m)
Installing package twitter@^1.7.0
Installing package webshot@^0.18.0
07/10 05:15 PM (1m)
Error Error: Basic authentication must be done with auth option
    at normalizeArguments (/usr/lib/node_modules/@zeit/cace/node_modules/got/index.js:210:10)
    at Function.got.stream (/usr/lib/node_modules/@zeit/cace/node_modules/got/index.js:330:18)
    at _promise2.default.then.r (/usr/lib/node_modules/@zeit/cace/build/lib/fetch.js:1:963)
    at Promise (<anonymous>)
    at F (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
    at fetchFromRegistry (/usr/lib/node_modules/@zeit/cace/build/lib/fetch.js:1:479)
    at /usr/lib/node_modules/@zeit/cace/build/lib/fetch.js:1:3445
    at tryCatch (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/regenerator/runtime.js:121:21)
07/10 05:15 PM (1m)
(node:81) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Basic authentication must be done with auth option
(node:81) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TooTallNate** [comment]
@morgs32 Please hop on the [ZEIT community chat](https://zeit.chat) and DM me your deployment ID and we can figure out why it's falling back to cace in the first place, because that should not be happening.

p.s. I've expunged your oauth token from the logs you posted, but you should consider them exposed and generate new ones.

**Comment by morgs32** [comment]
@TooTallNate it started working later. I was flooding deploys while working out the kinks - first time with this app. Maybe that was the issue?

Damn. Thanks for letting me know.

**Comment by TooTallNate** [comment]
@morgs32 Give me a ping if you experience this again. Gonna close this issue for now.
