### ISSUE TITLE
[now-cli 7.2.4] can not be installed

### ISSUE THREAD

**Issue by e2goon** [vercel/vercel#720]
![](https://user-images.githubusercontent.com/45934/28497069-ebd4c5a0-6fb7-11e7-94c8-255202102130.png)

```
@wmlee ✿ ~  npm i -g now
/Users/wmlee/.nvm/versions/node/v8.2.0/bin/now -> /Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/now

> now@7.2.4 postinstall /Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading now CLI 7.2.4 [====================] 100%
Error: Gateway Time-out https://cdn.zeit.co/releases/now-cli/7.2.4/now-macos
    at _callee$ (/Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/download.js:4808:19)
    at tryCatch (/Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/download.js:5027:40)
    at Generator.invoke [as _invoke] (/Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/download.js:5265:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/download.js:5079:21)
    at step (/Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/download.js:6633:30)
    at /Users/wmlee/.nvm/versions/node/v8.2.0/lib/node_modules/now/download/dist/download.js:6644:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! now@7.2.4 postinstall: `node download/install.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the now@7.2.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wmlee/.npm/_logs/2017-07-23T06_04_33_204Z-debug.log
```

## Steps

1. `npm i -g now`

## Env
```
os: sierra 10.12.5
node: v8.2.0
npm: 5.3.0
```

**Comment by eveningkid** [comment]
Same issue here...

**Comment by matheuss** [comment]
Fixed! Thanks for reporting 🙌

**Comment by e2goon** [comment]
👍
