### ISSUE TITLE
Fails install on Windows

### ISSUE THREAD

**Issue by calebboyd** [vercel/vercel#729]
`npm i now -g` 

On windows, yields

```
C:\Users\User\test>npm i now -g
C:\Program Files\nodejs\now -> C:\Program Files\nodejs\node_modules\now\download\dist\now
 
> now@7.3.0 postinstall C:\Program Files\nodejs\node_modules\now
> node download/install.js
 
> For the source code, check out: https://github.com/zeit/now-cli
 
> Downloading now CLI 7.3.0 [====================] 100%
 
{ Error: ENOENT: no such file or directory, open 'C:\Users\User\AppData\Roaming\npm\now'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at _callee2$ (C:\ProgramData\nvm\v6.11.1\node_modules\now\download\dist\download.js:2138:249)
    at tryCatch (C:\ProgramData\nvm\v6.11.1\node_modules\now\download\dist\download.js:2328:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\ProgramData\nvm\v6.11.1\node_modules\now\download\dist\download.js:2566:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\ProgramData\nvm\v6.11.1\node_modules\now\download\dist\download.js:2380:21)
    at step (C:\ProgramData\nvm\v6.11.1\node_modules\now\download\dist\download.js:3023:30)
    at C:\ProgramData\nvm\v6.11.1\node_modules\now\download\dist\download.js:3034:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\User\\AppData\\Roaming\\npm\\now' }
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "now" "-g"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
 
npm ERR! now@7.3.0 postinstall: `node download/install.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the now@7.3.0 postinstall script 'node download/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the now package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node download/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs now
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls now
npm ERR! There is likely additional logging output above.
 
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\test\npm-debug.log

```
Steps to reproduce:
 - [virtualbox image from microsoft](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines). 
 - [Install Chocolatey](https://chocolatey.org/install)
 - `choco install nvm -y`
 - `nvm install 6.11.1`
 - `nvm use 6.11.1`
 - `npm i now -g`

Fails to install 7.3.0

**Comment by 9andresc** [comment]
Same issue

**Comment by Ailrun** [comment]
Same issue occurs in

- Windows 10
- nodist v0.8.8
- node v8.2.1
- npm@4.0.5
- now@7.3.1

**Comment by isthisstackoverflow** [comment]
Same with

- Windows 8
- now@7.3.1
- npm@5.3.0
- node v8.2.1

Edit: Now working on now@7.3.4.

**Comment by igorklopov** [comment]
Please try again with `now@7.4.0`

**Comment by bsides** [comment]
Updating after 7.3.0, Windows 10
```
npm ERR! path C:\Users\BSIDES\AppData\Roaming\npm\now.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Users\BSIDES\AppData\Roaming\npm\now.cmd: node_modules\now\download\dist\now symlink target is not controlled by npm C:\Users\BSIDES\AppData\Roaming\npm\node_modules\now
npm ERR! File exists: C:\Users\BSIDES\AppData\Roaming\npm\now.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BSIDES\AppData\Roaming\npm-cache\_logs\2017-08-25T15_57_20_122Z-debug.log
```

It may be solved by deleting it manually, I'll try and post back

EDIT: Indeed, update works after deleting `now.cmd` and `now` from `$HOME$\AppData\Roaming\npm` folder

**Comment by calebboyd** [comment]
@bsides Are you using npm 5.4? (if you are i'd suggest reverting to 5.3 on windows)

**Comment by igorklopov** [comment]
@bsides @calebboyd I confirm it can be an issue. I will look into it soon.

**Comment by bsides** [comment]
![node versions](https://puu.sh/xjuX6/043c24a11e.png)
@calebboyd npm 5.3.0, node 8.2.1

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now/pull/56. We're merging zeit/now and zeit/now-cli!

**Comment by flieks** [comment]
is this fixed? I still have this problem after i upgraded from 7.3.0 to 8.2.5
`npm i -g now`
and then 
`now`

**Comment by igorklopov** [comment]
No, it is **not** fixed. And i am still going to fix it. Let me keep it opened 🙂

**Comment by albertosantini** [comment]
Any news?

In `9.0.0-canary.9` there is the issue.

**Comment by leo** [comment]
https://twitter.com/zeithq/status/930180257864437760

**Comment by albertosantini** [comment]
Thanks a lot.
Tested using git bash 2.15.0.windows.1, node 9.1.0 and npm 5.5.1,and  now installed locally. 

It works ok.

```
$ npm i now@8.5.0

> now@8.5.0 postinstall C:\My\Dev\zzz\tobedefined\node_modules\now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 8.5.0 [====================] 100%

npm WARN tobedefined@1.0.0 No repository field.

+ now@8.5.0
updated 1 package in 11.88s
$ npm out
Package  Current  Wanted  Latest  Location
now        8.5.0   8.5.1   8.5.1  tobedefined
$ npm up

> now@8.5.1 postinstall C:\My\Dev\zzz\tobedefined\node_modules\now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 8.5.1 [====================] 100%

npm WARN tobedefined@1.0.0 No repository field.

+ now@8.5.1
added 1 package, removed 2 packages and updated 4 packages in 39.824s
```

**Comment by liuyanghejerry** [comment]
Hi, I think I have problem on installing `now` on WSL.

```shell
root@DESKTOP-DTUUD6B:/mnt/d# npm i -g now
/root/.nvm/versions/node/v8.9.1/bin/now -> /root/.nvm/versions/node/v8.9.1/lib/node_modules/now/download/dist/now

> now@10.1.6 postinstall /root/.nvm/versions/node/v8.9.1/lib/node_modules/now
> node download/install.js

sh: node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! now@10.1.6 postinstall: `node download/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the now@10.1.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-15T16_29_41_068Z-debug.log
```

Content of /root/.npm/_logs/2018-03-15T16_29_41_068Z-debug.log is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'now' ]
2 info using npm@5.7.1
3 info using node@v8.9.1
4 verbose npm-session ebe3990c01db176b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/now 59ms (from cache)
8 silly pacote tag manifest for now@latest fetched in 107ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule now@10.1.6 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── now@10.1.6
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add now@10.1.6
19 silly decomposeActions action count 8
20 silly decomposeActions fetch now@10.1.6
21 silly decomposeActions extract now@10.1.6
22 silly decomposeActions preinstall now@10.1.6
23 silly decomposeActions build now@10.1.6
24 silly decomposeActions install now@10.1.6
25 silly decomposeActions postinstall now@10.1.6
26 silly decomposeActions finalize now@10.1.6
27 silly decomposeActions refresh-package-json now@10.1.6
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /root/.npm/_locks/staging-3b9356e178cfecc1.lock for /root/.nvm/versions/node/v8.9.1/lib/node_modules/.staging
32 silly doParallel extract 1
33 silly extract now@10.1.6
34 silly pacote trying now@latest by hash: sha512-HEZct6veXqaS/z/rnYIdH1gxmQ+JsfbD/ZIcCBNUxVcBk0JeA9RSwCsGJ+TuVWrSnotuhfarDhSVGxFDFZtmsg==
35 silly pacote now@latest extracted to /root/.nvm/versions/node/v8.9.1/lib/node_modules/.staging/now-d8e52a49 by content address 103ms
36 silly doReverseSerial unbuild 8
37 silly doSerial remove 8
38 silly doSerial move 8
39 silly doSerial finalize 8
40 silly finalize /root/.nvm/versions/node/v8.9.1/lib/node_modules/now
41 silly doParallel refresh-package-json 1
42 silly refresh-package-json /root/.nvm/versions/node/v8.9.1/lib/node_modules/now
43 silly doParallel preinstall 1
44 silly preinstall now@10.1.6
45 info lifecycle now@10.1.6~preinstall: now@10.1.6
46 silly doSerial build 8
47 silly build now@10.1.6
48 info linkStuff now@10.1.6
49 silly linkStuff now@10.1.6 has /root/.nvm/versions/node/v8.9.1/lib/node_modules as its parent node_modules
50 silly linkStuff now@10.1.6 is part of a global install
51 silly linkStuff now@10.1.6 is installed into a global node_modules
52 silly linkStuff now@10.1.6 is installed into the top-level global node_modules
53 verbose linkBins now@10.1.6
54 verbose linkBins [ { now: 'download/dist/now' },
54 verbose linkBins   '/root/.nvm/versions/node/v8.9.1/bin',
54 verbose linkBins   true ]
55 verbose linkMans now@10.1.6
56 silly doSerial global-link 8
57 silly doParallel update-linked 0
58 silly doSerial install 8
59 silly install now@10.1.6
60 info lifecycle now@10.1.6~install: now@10.1.6
61 silly doSerial postinstall 8
62 silly postinstall now@10.1.6
63 info lifecycle now@10.1.6~postinstall: now@10.1.6
64 verbose lifecycle now@10.1.6~postinstall: unsafe-perm in lifecycle false
65 verbose lifecycle now@10.1.6~postinstall: PATH: /root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.nvm/versions/node/v8.9.1/lib/node_modules/now/node_modules/.bin:/root/.nvm/versions/node/v8.9.1/lib/node_modules/.bin:/root/.nvm/versions/node/v8.9.1/bin:/root/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Go/bin:/mnt/c/Program Files/nodejs:/mnt/c/Users/liuyanghejerry/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/liuyanghejerry/AppData/Local/atom/bin:/mnt/c/Users/liuyanghejerry/AppData/Local/Programs/Fiddler:/mnt/c/Users/liuyanghejerry/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/liuyanghejerry/AppData/Roaming/npm
66 verbose lifecycle now@10.1.6~postinstall: CWD: /root/.nvm/versions/node/v8.9.1/lib/node_modules/now
67 silly lifecycle now@10.1.6~postinstall: Args: [ '-c', 'node download/install.js' ]
68 info lifecycle now@10.1.6~postinstall: Failed to exec postinstall script
69 verbose unlock done using /root/.npm/_locks/staging-3b9356e178cfecc1.lock for /root/.nvm/versions/node/v8.9.1/lib/node_modules/.staging
70 verbose stack Error: now@10.1.6 postinstall: `node download/install.js`
70 verbose stack spawn ENOENT
70 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
70 verbose stack     at emitTwo (events.js:126:13)
70 verbose stack     at ChildProcess.emit (events.js:214:7)
70 verbose stack     at maybeClose (internal/child_process.js:925:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
71 verbose pkgid now@10.1.6
72 verbose cwd /mnt/d
73 verbose Linux 4.4.0-43-Microsoft
74 verbose argv "/root/.nvm/versions/node/v8.9.1/bin/node" "/root/.nvm/versions/node/v8.9.1/bin/npm" "i" "-g" "now"
75 verbose node v8.9.1
76 verbose npm  v5.7.1
77 error file sh
78 error code ELIFECYCLE
79 error errno ENOENT
80 error syscall spawn
81 error now@10.1.6 postinstall: `node download/install.js`
81 error spawn ENOENT
82 error Failed at the now@10.1.6 postinstall script.
82 error This is probably not a problem with npm. There is likely additional logging output above.
83 verbose exit [ 1, true ]
```

However, I can install it under normal PowerShell with Node.js for Windows.

Any suggestions?
