### ISSUE TITLE
Cli stdout spammed on failed deploy

### ISSUE THREAD

**Issue by vjpr** [vercel/vercel#755]
```
➜  vwp git:(master) ✗ now
> Deploying ~/dev-live/vwp under quantitec
> Using Node.js 8.2.1 (default)
> Ready! https://xxx.now.sh (copied to clipboard) [14s]
> Synced 6 files (44.11kB) [13s]
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 66 main dependencies…
> ✓ Installed 910 modules [31s]
> ▲ npm run build
> > vwp@1.0.0 build /home/nowuser/src
> > next build
> > Using external babel configuration
> > Location: "/home/nowuser/src/.babelrc"
> > Using "webpack" config function defined in next.config.js.
> ▲ npm start
> > vwp@1.0.0 start /home/nowuser/src
> > NODE_ENV=production node server.js
> /home/nowuser/src/server.js:5
> import {koaMiddleware as reactIntlMiddleware} from 'react-intl'
> ^^^^^^
> SyntaxError: Unexpected token import
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:575:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vwp@1.0.0 start: `NODE_ENV=production node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the vwp@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-09-01T20_15_01_807Z-debug.log
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
```

And it just stays open and repeats this.

Should exit on failure.

**Comment by Qix-** [comment]
Hi @vjpr 👋 Sorry for the delay on this.

I believe this has been fixed since this issue was created. I'm going to optimistically close it, but please don't hesitate to reply if you're still seeing this.

Thanks for the issue!

**Comment by Kornil** [comment]
It's still bugged, I'm having this issue with my twitter bot, the bot apparently works but it spams that same message every second anyway.
https://zeit.co/kornil92/twitter-bot/ywwxhhdybx

It says it's still installing modules but if you check the logs you will see it is online spamming and liking tweets.

EDIT:
additional details
https://github.com/Kornil/twitter-bot this is the repo I'm deploying, (requires twitter tokens)

While adding an alias to the above linked `now` project, the build failed, logs are still available and I will not delete it until it is not needed anymore.
I can easily replicate the same error by deploying another copy of the same repo, at the moment this one is deployed and working exactly as the other was before the alias https://zeit.co/kornil92/twitter-bot/crljeahzpd/ meaning that it is stuck on building but it is actually working and spamming error messages on the console.

**Comment by Qix-** [comment]
@Kornil Which version of the CLI are you on?

**Comment by Kornil** [comment]
@Qix-  I just downloaded it a couple of hours ago, 8.4.0

**Comment by Qix-** [comment]
@TooTallNate can you take a look at this?

**Comment by maeligg** [comment]
I'm having the same issue. For me it's actually crashing the build after initially working.
By the way what's the logic behind now requiring an HTTP server ?

**Comment by getricj** [comment]
I'm also affected by this issue with the same output, this is a critical bug since it stops people deploying via create-react-app amongst others from deploying their app's.

Edit: Upon investigating I realised the package-lock.json file was for some reason "Unchanged" and looked out of character, I deleted this file and I was able to deploy my app with no issues.

**Comment by eric-levinson** [comment]
I'm seeing this same bug on my project. 
The script will work in the build faze for about an hour while spamming the error.
![now-project-bug](https://user-images.githubusercontent.com/15990577/32977228-c827b156-cbee-11e7-8a64-ee8c346246d6.png)
The build will eventually fail. 
I've been removing the deployments when they fail but I'll leave this one up for reference.
[https://zeit.co/elevinson/tweetbot-play/tncfkgffqy/logs](https://zeit.co/elevinson/tweetbot-play/tncfkgffqy/logs)

**Comment by sergiodxa** [comment]
We just released a fix to avoid the log being repeated forever thanks to @TooTallNate.
