### ISSUE TITLE
Error: Cannot find module './static'

### ISSUE THREAD

**Issue by leo** [vercel/vercel#764]
_From @rkrueger11 on August 11, 2017 0:36_

When attempting to deploy a static site (Next export), I get the following error:

```
~/x/out (master|✚2…) $ now                                                                                                                                                              6 changed files  master
> Deploying "~/xyz/out" (gcp) (us-central1)
⠋ Building and bundling your app…> Error! An unexpected error occurred!
  Error: Cannot find module './static'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.get static [as static] (/usr/local/lib/node_modules/now/out/serverless/builders/index.js:6:12)
    at build (/usr/local/lib/node_modules/now/out/serverless/build.js:4:23)
    at Object.deploy (/usr/local/lib/node_modules/now/out/providers/gcp/deploy.js:89:25)
    at <anonymous> Error: Cannot find module './static'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.get static [as static] (/usr/local/lib/node_modules/now/out/serverless/builders/index.js:6:12)
    at build (/usr/local/lib/node_modules/now/out/serverless/build.js:4:23)
    at Object.deploy (/usr/local/lib/node_modules/now/out/providers/gcp/deploy.js:89:25)
    at <anonymous>
⠦ Building and bundling your app…^C⏎
```

and it never actually builds or bundles. 😢 

_Copied from original issue: zeit/now#49_

**Comment by leo** [comment]
_From @DonnieWest on August 11, 2017 2:16_

It looks like we're missing the `static.js` file in the https://github.com/zeit/now/tree/master/src/serverless/builders folder. The only one currently available is nodejs. I'm able to replicate it on my end and a workaround for the time being would probably to create a minimal package.json that uses https://github.com/zeit/serve to serve the static files. I _think_ that's what they basically do behind the scenes

**Comment by Qix-** [comment]
Hi @DonnieWest - sorry for the delay here. Are you still seeing this issue?

**Comment by leo** [comment]
No response - closing.
