### ISSUE TITLE
Extrange error in server  (internal/streams/legacy.js:59)

### ISSUE THREAD

**Issue by leo** [vercel/vercel#780]
_From @tomyo on July 17, 2017 20:54_

internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: write EPROTO 140217767479104:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:

    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:800:14)

_Copied from original issue: zeit/now#28_

**Comment by PawanKr2feb** [comment]
What is the fix for this, i am also facing the above issue

**Comment by Qix-** [comment]
Hi @PawanKr2feb and @tomyo - could you provide some more information about the command line you're using?

**Comment by jlahare** [comment]
i am also facing same issue, i am running "npm run build" command, here is the details

D:\plugin\ionic-native>npm run build

> ionic-native@4.5.1 build D:\plugin\ionic-native
> npm run clean && npm run lint && npm run build:core && npm run build:modules


> ionic-native@4.5.1 clean D:\plugin\ionic-native
> rimraf dist .tmp


> ionic-native@4.5.1 lint D:\plugin\ionic-native
> gulp lint

[14:47:34] Using gulpfile D:\plugin\ionic-native\gulpfile.js
[14:47:34] Starting 'lint'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: linter.findConfiguration is not a function
    at D:\plugin\ionic-native\node_modules\gulp-tslint\index.js:101:44
    at wrappedMapper (D:\plugin\ionic-native\node_modules\map-stream\index.js:84:19)
    at Stream.stream.write (D:\plugin\ionic-native\node_modules\map-stream\index.js:96:21)
    at write (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:160:13)
    at emitReadable_ (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
    at DestroyableTransform.Transform._read (D:\plugin\ionic-native\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@4.5.1 lint: `gulp lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-native@4.5.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jayesh.lahare\AppData\Roaming\npm-cache\_logs\2018-01-25T09_17_34_499Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-native@4.5.1 build: `npm run clean && npm run lint && npm run build:core && npm run build:modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-native@4.5.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jayesh.lahare\AppData\Roaming\npm-cache\_logs\2018-01-25T09_17_34_683Z-debug.log

**Comment by GillSatinder** [comment]
Any idea about this issue????

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
