### ISSUE TITLE
now alias error

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#813]
`$ now alias talky.cards -r rules.json`

```
Verifying the DNS settings for talky.cards (see https://zeit.world for help)
> Verification OK!
> Error! Unknown error: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.Now.upsertPathAlias.rules.retry (/snapshot/now-cli/dist/now.js:3581:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

rules.json
```json
{
  "rules": [
    { "pathname": "/app/**",          "dest": "static.talky.cards" },
    { "pathname": "/svg/**",          "dest": "static.talky.cards" },
    { "pathname": "/backgrounds/**",  "dest": "static.talky.cards" },
    { "pathname": "/**",              "dest": "app.talky.cards" },
    { "pathname": "/",                "dest": "app.talky.cards" }
  ]
}
```

**Comment by Qix-** [comment]
HI there 👋 

Apologies for the delay - are you still seeing this error?

**Comment by leo** [comment]
No answer in one year. Closing.
