### ISSUE TITLE
now aws deploy fails with EPIPE error

### ISSUE THREAD

**Issue by christophmayrhofer** [vercel/vercel#842]
I have tried to deploy a nuxt and an adonisjs app to aws. Both fail with the following error:
(and both work fine with now itself)

```
 Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at Socket._writeGeneric (net.js:725:26)
    at Socket._write (net.js:744:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:671:40)
    at Socket.Writable.end (_stream_writable.js:475:10)
    at Socket.end (net.js:441:31)
    at handleInput (C:\snapshot\now-cli\node_modules\clipboardy\node_modules\execa\index.js:62:17)
    at module.exports (C:\snapshot\now-cli\node_modules\clipboardy\node_modules\execa\index.js:247:2)
    at Object.copy (C:\snapshot\now-cli\node_modules\clipboardy\lib\windows.js:10:16)
    at exports.write.input (C:\snapshot\now-cli\node_modules\clipboardy\index.js:28:20)
    at copyToClipboard (C:\snapshot\now-cli\dist\now.js:9058:13)
    at deploy (C:\snapshot\now-cli\dist\now.js:11994:18)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at Socket._writeGeneric (net.js:725:26)
    at Socket._write (net.js:744:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:671:40)
    at Socket.Writable.end (_stream_writable.js:475:10)
    at Socket.end (net.js:441:31)
    at handleInput (C:\snapshot\now-cli\node_modules\clipboardy\node_modules\execa\index.js:62:17)
    at module.exports (C:\snapshot\now-cli\node_modules\clipboardy\node_modules\execa\index.js:247:2)
    at Object.copy (C:\snapshot\now-cli\node_modules\clipboardy\lib\windows.js:10:16)
    at exports.write.input (C:\snapshot\now-cli\node_modules\clipboardy\index.js:28:20)
    at copyToClipboard (C:\snapshot\now-cli\dist\now.js:9058:13)
    at deploy (C:\snapshot\now-cli\dist\now.js:11994:18)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

When I run the deployed lambda function I get:
```

Error: Could not establish a connection to the http server
    at Socket.retry (/var/task/__now_handler.js:77:15)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by christophmayrhofer** [comment]
Just realized that `now aws` produces thae same `Error: Could not establish a connection to the http server` for all apps. Not just nuxt and adonis.

**Comment by larrikinventures** [comment]
I'd be completely unsurprised if it was a PEBKAC, but I'm getting this too. Just using the aws-serverless-express example app with now on AWS.

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
