### ISSUE TITLE
unable to install now

### ISSUE THREAD

**Issue by RedInd-IT** [vercel/vercel#872]
I am unable to install now via npm on my system (Windows 10 Pro 64bit) for a work project, not sure how to proceed. I have provided a snippet below. Latest versions of node and npm installed. Any help is greatly appreciated. Thank you.

```
UNC paths are not supported.  Defaulting to Windows directory.
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Windows\download\install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "now"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! now@8.3.4 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the now@8.3.4 postinstall script 'node download/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.`
```

No debug log was created. Any advice? Thanks.

**Comment by Qix-** [comment]
Hi there - are you still facing this issue?

**Comment by leo** [comment]
https://twitter.com/zeithq/status/930180257864437760
