### ISSUE TITLE
now aws ls throws

### ISSUE THREAD

**Issue by kandros** [vercel/vercel#883]
how to reproduce: `now aws ls`
```
> Error! An unexpected error occurred in provider ls: TypeError: provider[subcommand] is not a function
    at main (/snapshot/now-cli/dist/now.js:9709:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (pkg/prelude/bootstrap.js:1282:13)
    at run (bootstrap_node.js:469:7)
    at startup (bootstrap_node.js:193:9)
    at bootstrap_node.js:584:3
```

**Comment by Qix-** [comment]
HI @kandros - Apologies for the delay; are you still facing this issue?

**Comment by jcdarwin** [comment]
@Qix- I can confirm that this is still an issue -- I got the same thing when trying to list aws deployments:

```
$ now aws ls
> Error! An unexpected error occurred in provider ls: TypeError: provider[subcommand] is not a function
    at main (/snapshot/now-cli/dist/now.js:9709:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (pkg/prelude/bootstrap.js:1282:13)
    at run (bootstrap_node.js:469:7)
    at startup (bootstrap_node.js:193:9)
    at bootstrap_node.js:584:3
```

**Comment by makstr** [comment]
Same here for gcp

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
