### ISSUE TITLE
How to install Now CLI on GitLab CI systems?

### ISSUE THREAD

**Issue by maximtop** [vercel/vercel#890]
`npm install -g now` doesn't work properly.

**Comment by maximtop** [comment]
I manged to install now with flag --unsafe-perm
But I still get errors.
```
$ npm install -g now --unsafe-perm
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.5.0
npm http fetch GET 200 https://registry.npmjs.org/now 480ms
http fetch GET 200 https://registry.npmjs.org/now/-/now-8.3.7.tgz 178ms
npm info lifecycle now@8.3.7~preinstall: now@8.3.7
npm info linkStuff now@8.3.7
/usr/local/bin/now -> /usr/local/lib/node_modules/now/download/dist/now
npm info lifecycle now@8.3.7~install: now@8.3.7
npm info lifecycle now@8.3.7~postinstall: now@8.3.7

> now@8.3.7 postinstall /usr/local/lib/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli



+ now@8.3.7
added 1 package in 4.687s
npm info ok 
$ now --public -t NOW_TOKEN=$NOW_TOKEN -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY S3_BUCKET=$S3_BUCKET
> Error! An unexpected error occurred!
  TypeError: Cannot convert undefined or null to object
    at getUser (/snapshot/now-cli/dist/now.js:7197:10)
    at process._tickCallback (internal/process/next_tick.js:109:7) TypeError: Cannot convert undefined or null to object
    at getUser (/snapshot/now-cli/dist/now.js:7197:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by maximtop** [comment]
I made mistakes in my deploy command. Right command is:
```
- now --public -t $NOW_TOKEN -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e S3_BUCKET
```
Closing issue.
