### ISSUE TITLE
now gcp login with no local Window manager generates error

### ISSUE THREAD

**Issue by ryan-mf** [vercel/vercel#911]
Using Now CLI 8.3.9

I use a Linux VM via SSH for all development, operations, etc use. I'd like to move our now default deployment to GCP (where the rest of our resources are), but because my Linux VM is connected via SSH without an installed Window manager, when I run 'now gcp login' I get this error:
```
host$ now gcp login
> Error! An unexpected error occurred!
  Error: spawn /snapshot/now-cli/node_modules/opn/xdg-open ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (pkg/prelude/bootstrap.js:1282:13)
    at run (bootstrap_node.js:469:7)
    at startup (bootstrap_node.js:193:9)
    at bootstrap_node.js:584:3 Error: spawn /snapshot/now-cli/node_modules/opn/xdg-open ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (pkg/prelude/bootstrap.js:1282:13)
    at run (bootstrap_node.js:469:7)
    at startup (bootstrap_node.js:193:9)
    at bootstrap_node.js:584:3
```

With the Google Cloud SDK, logging into GCP detects you have no local Window manager and just outputs the URL for you to paste into your browser to login with, get the authorization code, and paste back into the SSH session. Can we do the same with Now?

**Comment by DonnieWest** [comment]
Oddly enough I'm getting this exact same error on a full Linux GUI environment with Chrome and Firefox installed even though this worked in the past. I'd be happy to provide any logs necessary

**Comment by matthiasak** [comment]
+1 for this issue. Full Linux Budgie environment.

**Comment by matthiasak** [comment]
@ryan-mf @DonnieWest attempting to fix in the above :point_up_2:

**Comment by Qix-** [comment]
Hi @ryan-mf - I think this was fixed and rolled out; are you still seeing this issue?

@leo can you confirm that this was indeed patched and released?

**Comment by leo** [comment]
Should be working, yes!
