### ISSUE TITLE
Adding a custom domain fails

### ISSUE THREAD

**Issue by ipeychev** [vercel/vercel#932]
Adding a custom domain fails. Here is the output of now-cli. It is the latest version (8.3.7):

$  now domains add h2inaction.info

> Verifying nameservers…
> Verification OK!
> Success! Domain h2inaction.info (OVMogyptH7PSVBHtD08bYgSx) added [4s]

$  now ls
> 2 deployments found [961ms]
h2inaction.info (2 of 2 total)
 url                                      inst #    state                 age
 h2inactioninfo-yefteocvzg.now.sh              1    READY                 16h
 h2inactioninfo-nsnvymsdti.now.sh              0    BUILD_ERROR          108d

$ now alias https://h2inactioninfo-yefteocvzg.now.sh h2inaction.info
> h2inaction.info is a custom domain.
> Verifying the DNS settings for h2inaction.info (see https://zeit.world for help)
{ Error
    at ClientRequest.<anonymous> (/snapshot/now-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://h2inaction.info failed, reason: getaddrinfo ENOTFOUND h2inaction.info h2inaction.info:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
{ Error
    at ClientRequest.<anonymous> (/snapshot/now-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://h2inaction.info failed, reason: getaddrinfo ENOTFOUND h2inaction.info h2inaction.info:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
{ Error
    at ClientRequest.<anonymous> (/snapshot/now-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://h2inaction.info failed, reason: getaddrinfo ENOTFOUND h2inaction.info h2inaction.info:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
{ Error
    at ClientRequest.<anonymous> (/snapshot/now-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://h2inaction.info failed, reason: getaddrinfo ENOTFOUND h2inaction.info h2inaction.info:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
{ Error
    at ClientRequest.<anonymous> (/snapshot/now-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://h2inaction.info failed, reason: getaddrinfo ENOTFOUND h2inaction.info h2inaction.info:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
{ Error
    at ClientRequest.<anonymous> (/snapshot/now-cli/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at connectErrorNT (net.js:1028:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'FetchError',
  message: 'request to http://h2inaction.info failed, reason: getaddrinfo ENOTFOUND h2inaction.info h2inaction.info:80',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
> Error! Unknown error: Error: Failed to fetch "http://h2inaction.info"
Error: Failed to fetch "http://h2inaction.info"
    at module.exports.Now.verifyDomain.domain.retry (/snapshot/now-cli/dist/now.js:4085:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Qix-** [comment]
I'll have @OlliV and @leo verify, but this might boil down to insufficient error messages.

I'll defer to them.

**Comment by OlliV** [comment]
Is this still active?

**Comment by freecates** [comment]
I'm experiencing the same issue due to unproperly DNS propagation. You can check it here:
[https://www.whatsmydns.net/#NS/beneficiosfamiliasnumerosas.org](https://www.whatsmydns.net/#NS/beneficiosfamiliasnumerosas.org)
How many days we must wait?
Thanks.

**Comment by OlliV** [comment]
The domain seems fine. Try `now domains add <yourdomain>`

**Comment by leo** [comment]
This is now resolved!
