### ISSUE TITLE
"Unexpected error. Please try again later." during deployment

### ISSUE THREAD

**Issue by furf** [vercel/vercel#942]
When running `now -d` to deploy my project, I get an unexpected error.

```bash
~/src/project-name 👈  now -d
> Deploying ~/src/project-name under ********
> [debug] Detected `deploymentType` = `npm`
> [debug] Detected `deploymentName` = "project-name"
> [debug] ignoring "/Users/********/src/project-name/.DS_Store"
> [debug] ignoring "/Users/********/src/project-name/node_modules"
> [debug] ignoring "/Users/********/src/project-name/npm-debug.log"
> [debug] ignoring "/Users/********/src/project-name/components/.DS_Store"
> [debug] locating files /Users/********/src/project-name: 40.945ms
> [debug] Getting files: 54.949ms
> [debug] Computing hashes: 102.523ms
> [debug] /now/create: 5302.537ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 5132.542ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 6404.834ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 1921.381ms
> [debug] error: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> Error! Unexpected error. Please try again later. (Unexpected response)
```

Here is my package.json (if it helps).

```json
{
  "name": "project-name",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "micro-dev index.js",
    "start": "micro index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "********",
  "private": true,
  "dependencies": {
    "apollo-server-micro": "^1.1.7",
    "graphql": "^0.11.7",
    "graphql-tools": "^2.5.1",
    "isomorphic-fetch": "^2.2.1",
    "micro": "^9.0.0",
    "micro-cors": "0.0.4",
    "microrouter": "^2.2.3"
  },
  "devDependencies": {
    "micro-dev": "^1.2.3"
  }
}
```

My project is running fine locally using `npm start` and `npm run dev`.

I am also having trouble deploying another project which has previously deployed successfully and continues to run on now.sh.

Is this a network or system error?

**Comment by furf** [comment]
I saw a similar issue which recommended running `nslookup api.zeit.co`. Looks OK to me?

```bash
~/src/project-name 👈  nslookup api.zeit.co
Server:		208.67.222.222
Address:	208.67.222.222#53

Non-authoritative answer:
Name:	api.zeit.co
Address: 54.153.55.116
Name:	api.zeit.co
Address: 52.8.142.115
```

**Comment by sethmcleod** [comment]
I'm also seeing this issue. Attempted to deploy using the Now application with the same results. Not sure if it's related but https://zeit.co/chat also seems to be down.

_macOS_ - **10.12.6**
_node_ - **>=7.3**
_now cli_ - **8.3.10**

**Comment by furf** [comment]
P.S.
OSX 10.12.6
node 8.7.0
now 8.3.10

**Comment by xtalx** [comment]
I'm also experiencing this. 

macOS: 13.1
node: 8.5.0
now: 8.3.10

```sh
tw master ✗ ◒ ➜ now -d
> Deploying ~/Repos/tw under twoism
> [debug] Detected `deploymentType` = `static`
> [debug] Detected `deploymentName` = "tw"
> [debug] ignoring "/Users/tal/Repos/tw/.git"
> [debug] ignoring "/Users/tal/Repos/tw/.gitignore"
> [debug] locating files /Users/tal/Repos/tw: 4.353ms
> [debug] Getting files: 12.939ms
> [debug] Computing hashes: 5.700ms
> [debug] /now/create: 6305.653ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 5059.183ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 6088.791ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 2069.063ms
> [debug] error: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> Error! Unexpected error. Please try again later. (Unexpected response)
```
nslookup
```sh
tw master ✗ ◒ ⍉ ➜ nslookup api.zeit.co
Server:		10.0.6.11
Address:	10.0.6.11#53

Non-authoritative answer:
Name:	api.zeit.co
Address: 52.8.142.115
Name:	api.zeit.co
Address: 54.153.55.116
```

**Comment by furf** [comment]
Looks like a systems/network issue. https://twitter.com/zeit_status

**Comment by leo** [comment]
We're experiencing problems on our platform right now. More details [here](https://twitter.com/zeit_status).

Sorry for the inconvenience caused!

**Comment by johnbrett** [comment]
I'm having this exact problem now, trying to deploy a docker based project. Any ideas on how to debug?

**Comment by johnbrett** [comment]
Also happening if I try deploy a package.json based project. This is the first time I've tried to deploy anything with `now` so not sure if I'm doing something wrong...
