### ISSUE TITLE
Can't deploy since this morning

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#945]
Hi, I'm having trouble to deploy a micro.js application since this morning. This is my output:

> Deploying ~/Projects/Grupo Jolivet/send-email under brielov
> [debug] Detected `deploymentType` = `npm`
> [debug] Detected `deploymentName` = "send-email"
> [debug] ignoring "/Users/brielov/Projects/Grupo Jolivet/send-email/.env"
> [debug] ignoring "/Users/brielov/Projects/Grupo Jolivet/send-email/.git"
> [debug] ignoring "/Users/brielov/Projects/Grupo Jolivet/send-email/.gitignore"
> [debug] ignoring "/Users/brielov/Projects/Grupo Jolivet/send-email/node_modules"
> [debug] locating files /Users/brielov/Projects/Grupo Jolivet/send-email: 1.410ms
> [debug] Getting files: 4.263ms
> [debug] Computing hashes: 18.130ms
> [debug] /now/create: 8419.246ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 5309.066ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 5272.471ms
> [debug] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> [debug] /now/create: 3056.427ms
> [debug] error: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:402:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> Error! Unexpected error. Please try again later. (Unexpected response)

**Comment by leo** [comment]
We're experiencing problems on our platform right now. More details [here](https://twitter.com/zeit_status).

Sorry for the inconvenience caused!
