### ISSUE TITLE
adding credentials fails with an error

### ISSUE THREAD

**Issue by ozzie1998** [vercel/vercel#961]
```js
TypeError: Cannot convert undefined or null to object
    at getUser (/snapshot/now-cli/dist/now.js:7209:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)
``` 

This is after I click on the verification email, it verifies, then I go back to the CLI and it errors out.

**Comment by Qix-** [comment]
Hi - which version of `now` are you running?

**Comment by leo** [comment]
Closing. No response.
