### ISSUE TITLE
alias custom domain :: Error! Unknown error:

### ISSUE THREAD

**Issue by bitcoinvsalts** [vercel/vercel#998]
Trying to alias a custom domain

```
> now alias nimiq-tfdxvferle.now.sh nimik.me
> nimik.me is a custom domain.
> Verifying the DNS settings for nimik.me (see https://zeit.world for help)
> Error! Unknown error: Error: Failed to fetch "http://nimik.me"
Error: Failed to fetch "http://nimik.me"
    at module.exports.Now.verifyDomain.domain.retry (C:\snapshot\now-cli\dist\now.js:4161:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by leo** [comment]
@OlliV Any idea?

**Comment by pranaygp** [comment]
Facing the same issue:
```
$ now alias https://create-next-example-app-fhrcgambes.now.sh frigo.io
> frigo.io is a custom domain.
> Verifying the DNS settings for frigo.io (see https://zeit.world for help)
> Error! Unknown error: Error: Failed to fetch "http://frigo.io"
Error: Failed to fetch "http://frigo.io"
    at module.exports.Now.verifyDomain.domain.retry (/snapshot/now-cli/dist/now.js:4203:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by edsilv** [comment]
Seeing the same error for my domain registered on namecheap.com - nameservers are configured correctly.

**Comment by wichniowski** [comment]
experiencing the same issue, registrar namecheap, dns records pointing to zeit nameservers

**Comment by Qix-** [comment]
@wichniowski @edsilv @pranaygp How long prior to adding the domain did you purchase the domain?

If you'd like, you can join us on Slack at https://zeit.chat and we can help you in realtime, by the way.

**Comment by edsilv** [comment]
I _think_ I solved it by running `now domains add mydomain.com` ...

**Comment by OlliV** [comment]
Closing due to no activity. If you still have the same issue please reopen.
